// HemisX SAST — CI/CD Integration Templates
// Generates ready-to-use workflow files for GitHub Actions, GitLab CI, etc.

export interface CicdConfig {
  failOn:    'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW' | 'NONE'
  scanName?: string
  branch?:   string
}

export function generateGitHubActions(config: CicdConfig): string {
  const stepsRef = '$' + '{{ steps.sast.outputs.result }}'
  const failOn = config.failOn === 'NONE' ? '' : [
    '',
    '      - name: Check SAST Results',
    '        run: |',
    `          CRITICAL=$(echo '${stepsRef}' | jq '.summary.critical')`,
    `          HIGH=$(echo '${stepsRef}' | jq '.summary.high')`,
    `          MEDIUM=$(echo '${stepsRef}' | jq '.summary.medium')`,
    `          LOW=$(echo '${stepsRef}' | jq '.summary.low')`,
    '          echo "Findings: CRITICAL=$CRITICAL HIGH=$HIGH MEDIUM=$MEDIUM LOW=$LOW"',
    config.failOn === 'CRITICAL' ? '          if [ "$CRITICAL" -gt 0 ]; then echo "::error::CRITICAL vulnerabilities found"; exit 1; fi' :
    config.failOn === 'HIGH' ? '          if [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ]; then echo "::error::HIGH+ vulnerabilities found"; exit 1; fi' :
    config.failOn === 'MEDIUM' ? '          if [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ] || [ "$MEDIUM" -gt 0 ]; then echo "::error::MEDIUM+ vulnerabilities found"; exit 1; fi' :
    '          TOTAL=$((CRITICAL + HIGH + MEDIUM + LOW)); if [ "$TOTAL" -gt 0 ]; then echo "::error::Vulnerabilities found"; exit 1; fi',
  ].join('\n')

  return `# HemisX SAST — GitHub Actions Workflow
# Generated by HemisX SAST Scanner
# Add this file to .github/workflows/hemisx-sast.yml

name: HemisX SAST Scan

on:
  push:
    branches: [${config.branch ?? 'main'}]
  pull_request:
    branches: [${config.branch ?? 'main'}]

permissions:
  contents: read
  security-events: write

jobs:
  sast-scan:
    runs-on: ubuntu-latest
    name: Static Application Security Testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Collect source files
        id: collect
        run: |
          # Collect source files (adjust extensions as needed)
          FILES_JSON=$(find . -type f \\( -name "*.js" -o -name "*.ts" -o -name "*.py" -o -name "*.php" -o -name "*.java" -o -name "*.go" -o -name "*.rb" -o -name "*.cs" -o -name "package.json" -o -name "requirements.txt" -o -name "go.mod" \\) \\
            -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/vendor/*" -not -path "*/dist/*" -not -path "*/.next/*" \\
            | head -50 \\
            | while read f; do
                content=$(cat "$f" | python3 -c "import sys,json; print(json.dumps(sys.stdin.read()))")
                echo "{\\"path\\": \\"$f\\", \\"content\\": $content}"
              done \\
            | jq -s '.')
          echo "files=$FILES_JSON" >> $GITHUB_OUTPUT

      - name: Run HemisX SAST
        id: sast
        env:
          HEMISX_API_URL: \${{ secrets.HEMISX_API_URL }}
          HEMISX_API_KEY: \${{ secrets.HEMISX_API_KEY }}
        run: |
          RESULT=$(curl -s -X POST "\${HEMISX_API_URL}/api/sast/scan" \\
            -H "Content-Type: application/json" \\
            -H "Authorization: Bearer \${HEMISX_API_KEY}" \\
            -d "{\\"name\\": \\"${config.scanName ?? 'CI/CD Scan - ${{ github.sha }}'}\\", \\"files\\": \${{ steps.collect.outputs.files }}}")
          echo "result=$RESULT" >> $GITHUB_OUTPUT
          echo "$RESULT" | jq '.summary'

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hemisx-sast-results.sarif
        continue-on-error: true
${failOn}
`
}

export function generateGitLabCi(config: CicdConfig): string {
  return `# HemisX SAST — GitLab CI Pipeline
# Generated by HemisX SAST Scanner
# Add this to .gitlab-ci.yml

hemisx-sast:
  stage: test
  image: curlimages/curl:latest
  variables:
    HEMISX_API_URL: \${HEMISX_API_URL}
    HEMISX_API_KEY: \${HEMISX_API_KEY}
  script:
    - |
      # Collect source files
      FILES=$(find . -type f \\( -name "*.js" -o -name "*.ts" -o -name "*.py" \\) \\
        -not -path "*/node_modules/*" -not -path "*/.git/*" \\
        | head -50 \\
        | while read f; do
            content=$(cat "$f" | python3 -c "import sys,json; print(json.dumps(sys.stdin.read()))")
            echo "{\\"path\\": \\"$f\\", \\"content\\": $content}"
          done \\
        | jq -s '.')
      RESULT=$(curl -s -X POST "\${HEMISX_API_URL}/api/sast/scan" \\
        -H "Content-Type: application/json" \\
        -H "Authorization: Bearer \${HEMISX_API_KEY}" \\
        -d "{\\"name\\": \\"GitLab CI Scan\\", \\"files\\": $FILES}")
      echo "$RESULT" | jq '.summary'
      CRITICAL=$(echo "$RESULT" | jq '.summary.critical')
      ${config.failOn !== 'NONE' ? `if [ "$CRITICAL" -gt 0 ]; then echo "CRITICAL vulnerabilities found!"; exit 1; fi` : 'echo "Scan complete"'}
  artifacts:
    reports:
      sast: hemisx-sast-results.json
  only:
    - merge_requests
    - ${config.branch ?? 'main'}
`
}

export function generatePreCommitHook(): string {
  return `#!/bin/sh
# HemisX SAST — Pre-commit Hook
# Install: cp this file to .git/hooks/pre-commit && chmod +x .git/hooks/pre-commit

echo "[HemisX SAST] Scanning staged files..."

# Collect staged files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\\.(js|ts|py|php|java|go|rb|cs)$' | head -20)

if [ -z "$STAGED_FILES" ]; then
  echo "[HemisX SAST] No scannable files staged."
  exit 0
fi

FILES_JSON="["
FIRST=true
for f in $STAGED_FILES; do
  CONTENT=$(git show ":$f" | python3 -c "import sys,json; print(json.dumps(sys.stdin.read()))")
  if [ "$FIRST" = true ]; then FIRST=false; else FILES_JSON="$FILES_JSON,"; fi
  FILES_JSON="$FILES_JSON{\"path\":\"$f\",\"content\":$CONTENT}"
done
FILES_JSON="$FILES_JSON]"

RESULT=$(curl -s -X POST "\${HEMISX_API_URL:-http://localhost:7777}/api/sast/scan" \\
  -H "Content-Type: application/json" \\
  -d "{\\"name\\":\\"Pre-commit scan\\",\\"files\\":$FILES_JSON}")

CRITICAL=$(echo "$RESULT" | jq -r '.summary.critical // 0')
HIGH=$(echo "$RESULT" | jq -r '.summary.high // 0')

echo "[HemisX SAST] Findings: CRITICAL=$CRITICAL HIGH=$HIGH"

if [ "$CRITICAL" -gt 0 ]; then
  echo "[HemisX SAST] ❌ CRITICAL vulnerabilities found — commit blocked"
  echo "$RESULT" | jq -r '.findings[] | select(.severity == "CRITICAL") | "  → \\(.ruleId): \\(.ruleName) (\\(.filePath):\\(.lineStart))"'
  exit 1
fi

echo "[HemisX SAST] ✓ No critical issues. Commit allowed."
exit 0
`
}
