// src/lib/mock-data/cloud-scanner.ts
import type {
  CloudScan,
  CloudFinding,
  CloudInventory,
  ComplianceScore,
  AttackScenario,
  RemediationItem,
  CloudConnection,
} from '@/lib/types/cloud-scanner'

// ─── Connection ───────────────────────────────────────────────────────────────
export const MOCK_CLOUD_CONNECTION: CloudConnection = {
  id: 'conn-aws-demo-001',
  orgId: 'org-demo',
  provider: 'AWS',
  accountId: '123456789012',
  accountAlias: 'acme-production',
  roleArn: 'arn:aws:iam::123456789012:role/HemisXScannerRole',
  externalId: 'hemisx-ext-abc123',
  regions: ['us-east-1', 'us-west-2', 'eu-west-1'],
  connectedAt: '2026-03-20T08:00:00Z',
  lastScannedAt: '2026-03-23T10:00:00Z',
  status: 'CONNECTED',
}

// ─── Findings ─────────────────────────────────────────────────────────────────
export const MOCK_CLOUD_FINDINGS: CloudFinding[] = [
  // ── IAM CRITICAL ──
  {
    id: 'finding-iam-001',
    checkId: 'IAM-001',
    category: 'IAM',
    severity: 'CRITICAL',
    status: 'OPEN',
    title: 'Root Account Has Active Access Keys',
    resourceId: 'arn:aws:iam::123456789012:root',
    resourceType: 'AWS::IAM::Root',
    resourceName: 'Root Account',
    region: 'global',
    riskNarrative: 'Your AWS root account has active programmatic access keys. The root account has unrestricted access to every resource in your AWS account — there are no IAM permission boundaries that can contain it. If these keys are ever exposed (via a code commit, S3 bucket leak, or employee device), an attacker gains permanent, irrevocable full-account access including the ability to delete all resources, exfiltrate all data, and create backdoor IAM users before you can respond.',
    attackVector: 'Attacker finds root access key in GitHub commit or exposed S3 object → calls aws sts get-caller-identity to validate → creates new IAM admin user → deletes CloudTrail to cover tracks → begins full account takeover.',
    estimatedImpact: 'Full AWS account compromise. Estimated recovery cost: $2.1M+ (includes incident response, data recovery, regulatory fines, customer notification).',
    complianceMappings: [
      { framework: 'CIS', controlId: 'CIS 1.4', controlName: 'Ensure no root account access key exists', status: 'FAIL' },
      { framework: 'PCI_DSS', controlId: 'PCI-DSS 7.1', controlName: 'Limit access to system components', status: 'FAIL' },
      { framework: 'SOC2', controlId: 'CC6.3', controlName: 'Logical access controls', status: 'FAIL' },
    ],
    fixEffort: '5min',
    remediation: {
      summary: 'Delete root account access keys immediately. Root should only be used via console with MFA.',
      console: '1. Sign in as root → My Security Credentials\n2. Expand "Access keys"\n3. Click Delete on each active key\n4. Enable MFA on root if not already done',
      cli: '# Cannot delete root keys via CLI — must use console\n# But verify with:\naws iam get-account-summary | grep AccountAccessKeysPresent',
      terraform: '# Terraform cannot manage root account keys\n# Use AWS Config rule to detect:\nresource "aws_config_rule" "root_account_mfa" {\n  name = "root-account-mfa-enabled"\n  source {\n    owner             = "AWS"\n    source_identifier = "ROOT_ACCOUNT_MFA_ENABLED"\n  }\n}',
      cloudformation: 'AWSTemplateFormatVersion: "2010-09-09"\nResources:\n  RootMFAConfigRule:\n    Type: AWS::Config::ConfigRule\n    Properties:\n      ConfigRuleName: root-account-mfa-enabled\n      Source:\n        Owner: AWS\n        SourceIdentifier: ROOT_ACCOUNT_MFA_ENABLED',
      estimatedMinutes: 5,
    },
    chainIds: ['scenario-001'],
    detectedAt: '2026-03-23T10:05:00Z',
    lastSeenAt: '2026-03-23T10:05:00Z',
  },
  {
    id: 'finding-iam-002',
    checkId: 'IAM-003',
    category: 'IAM',
    severity: 'CRITICAL',
    status: 'OPEN',
    title: 'IAM Users with Console Access and No MFA (4 users)',
    resourceId: 'arn:aws:iam::123456789012:user/john.smith',
    resourceType: 'AWS::IAM::User',
    resourceName: 'john.smith, sarah.jones, dev-deploy, ci-bot',
    region: 'global',
    riskNarrative: '4 IAM users have AWS Console access but no Multi-Factor Authentication. A compromised password — from phishing, credential stuffing, or a leaked .env file — gives an attacker full access to all services these users can access. Without MFA, there is no second factor to stop account takeover.',
    attackVector: 'Attacker purchases credential dump from dark web → tests against AWS console → john.smith password works → accesses S3 buckets, RDS databases, and Lambda functions with no MFA challenge.',
    estimatedImpact: 'Account takeover for 4 users. If any hold admin or S3 access: full data breach potential. Est. $340K per breach (IBM 2024).',
    complianceMappings: [
      { framework: 'CIS', controlId: 'CIS 1.10', controlName: 'Ensure MFA is enabled for all IAM users with console access', status: 'FAIL' },
      { framework: 'PCI_DSS', controlId: 'PCI-DSS 8.3.1', controlName: 'MFA for all non-console administrative access', status: 'FAIL' },
      { framework: 'HIPAA', controlId: 'HIPAA 164.312(d)', controlName: 'Person or entity authentication', status: 'FAIL' },
    ],
    fixEffort: '1hr',
    remediation: {
      summary: 'Enforce MFA for all IAM users with console access. Use IAM policy to deny all actions when MFA not present.',
      console: '1. IAM → Users → select user\n2. Security credentials tab → Assigned MFA device → Manage\n3. Follow virtual MFA setup\n4. Repeat for all 4 users',
      cli: 'aws iam create-virtual-mfa-device --virtual-mfa-device-name john.smith-mfa --outfile /tmp/QRCode.png --bootstrap-method QRCodePNG\n# Then have user scan QR code and activate',
      terraform: 'resource "aws_iam_policy" "require_mfa" {\n  name = "RequireMFA"\n  policy = jsonencode({\n    Version = "2012-10-17"\n    Statement = [{\n      Sid    = "DenyWithoutMFA"\n      Effect = "Deny"\n      NotAction = ["iam:CreateVirtualMFADevice", "iam:EnableMFADevice", "sts:GetSessionToken"]\n      Resource = "*"\n      Condition = {\n        BoolIfExists = { "aws:MultiFactorAuthPresent" = "false" }\n      }\n    }]\n  })\n}',
      cloudformation: 'AWSTemplateFormatVersion: "2010-09-09"\nResources:\n  RequireMFAPolicy:\n    Type: AWS::IAM::ManagedPolicy\n    Properties:\n      ManagedPolicyName: RequireMFA\n      PolicyDocument:\n        Version: "2012-10-17"\n        Statement:\n          - Sid: DenyWithoutMFA\n            Effect: Deny\n            NotAction:\n              - iam:CreateVirtualMFADevice\n              - iam:EnableMFADevice\n              - sts:GetSessionToken\n            Resource: "*"\n            Condition:\n              BoolIfExists:\n                "aws:MultiFactorAuthPresent": "false"',
      estimatedMinutes: 60,
    },
    chainIds: ['scenario-001'],
    detectedAt: '2026-03-23T10:05:00Z',
    lastSeenAt: '2026-03-23T10:05:00Z',
  },
  // ── DATA CRITICAL ──
  {
    id: 'finding-data-001',
    checkId: 'DATA-001',
    category: 'DATA',
    severity: 'CRITICAL',
    status: 'OPEN',
    title: 'S3 Bucket "prod-customer-uploads" Publicly Readable',
    resourceId: 'arn:aws:s3:::prod-customer-uploads',
    resourceType: 'AWS::S3::Bucket',
    resourceName: 'prod-customer-uploads',
    region: 'us-east-1',
    riskNarrative: 'Your S3 bucket prod-customer-uploads is publicly readable by anyone on the internet with no authentication required. This bucket contains 14,832 objects including customer profile photos, government ID documents, and signed contracts. Any person can enumerate the bucket with aws s3 ls and download all content in minutes. This data likely contains PII covered by GDPR and CCPA.',
    attackVector: 'curl https://prod-customer-uploads.s3.amazonaws.com → lists all objects → wget in a loop → full data exfiltration in ~8 minutes. No credentials required.',
    estimatedImpact: 'PII data breach affecting all customers. GDPR fine up to 4% annual revenue. Est. total cost: $1.2M (fines + notification + remediation).',
    complianceMappings: [
      { framework: 'CIS', controlId: 'CIS 2.1.5', controlName: 'Ensure S3 buckets are not publicly accessible', status: 'FAIL' },
      { framework: 'PCI_DSS', controlId: 'PCI-DSS 3.4', controlName: 'Protect stored cardholder data', status: 'FAIL' },
      { framework: 'SOC2', controlId: 'CC6.1', controlName: 'Logical and physical access controls', status: 'FAIL' },
      { framework: 'HIPAA', controlId: 'HIPAA 164.312(a)', controlName: 'Access control', status: 'FAIL' },
    ],
    fixEffort: '5min',
    remediation: {
      summary: 'Enable S3 Block Public Access at both bucket and account level. Review bucket policy for any explicit Allow to \'*\'.',
      console: '1. S3 → prod-customer-uploads → Permissions\n2. Block public access → Edit → Enable all 4 checkboxes → Save\n3. Also set at account level: S3 → Block Public Access (account settings)',
      cli: 'aws s3api put-public-access-block \\\n  --bucket prod-customer-uploads \\\n  --public-access-block-configuration \\\n  "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"',
      terraform: 'resource "aws_s3_bucket_public_access_block" "prod_customer_uploads" {\n  bucket = "prod-customer-uploads"\n  block_public_acls       = true\n  block_public_policy     = true\n  ignore_public_acls      = true\n  restrict_public_buckets = true\n}',
      cloudformation: 'AWSTemplateFormatVersion: "2010-09-09"\nResources:\n  ProdCustomerUploadsBlock:\n    Type: AWS::S3::BucketPolicy\n    Properties:\n      Bucket: prod-customer-uploads\n      PolicyDocument:\n        Statement:\n          - Effect: Deny\n            Principal: "*"\n            Action: "s3:GetObject"\n            Resource: "arn:aws:s3:::prod-customer-uploads/*"\n            Condition:\n              Bool:\n                "aws:SecureTransport": "false"',
      estimatedMinutes: 5,
    },
    chainIds: ['scenario-001', 'scenario-002'],
    detectedAt: '2026-03-23T10:08:00Z',
    lastSeenAt: '2026-03-23T10:08:00Z',
  },
  {
    id: 'finding-data-002',
    checkId: 'DATA-003',
    category: 'DATA',
    severity: 'HIGH',
    status: 'OPEN',
    title: 'RDS Instance "prod-postgres" Publicly Accessible',
    resourceId: 'arn:aws:rds:us-east-1:123456789012:db:prod-postgres',
    resourceType: 'AWS::RDS::DBInstance',
    resourceName: 'prod-postgres',
    region: 'us-east-1',
    riskNarrative: 'Your production PostgreSQL database is directly accessible from the internet on port 5432. While authentication is still required, a publicly accessible database is exposed to brute-force attacks, SQL injection probes, and exploitation of any future PostgreSQL CVEs. Databases should never be directly internet-accessible — they should only be reachable from within your VPC.',
    attackVector: 'nmap scan discovers open port 5432 → attacker runs pg_brute or Hydra against it → weak password found → full database access.',
    estimatedImpact: 'Database credential brute force leading to full data exfiltration. Est. $680K breach cost.',
    complianceMappings: [
      { framework: 'CIS', controlId: 'CIS 2.3.1', controlName: 'Ensure RDS instances are not publicly accessible', status: 'FAIL' },
      { framework: 'PCI_DSS', controlId: 'PCI-DSS 1.3', controlName: 'Prohibit direct public access to cardholder data environment', status: 'FAIL' },
    ],
    fixEffort: '1hr',
    remediation: {
      summary: 'Disable public accessibility on RDS instance. Ensure it\'s in a private subnet with no internet gateway route.',
      console: '1. RDS → Databases → prod-postgres → Modify\n2. Connectivity → Public access → No\n3. Apply immediately',
      cli: 'aws rds modify-db-instance \\\n  --db-instance-identifier prod-postgres \\\n  --no-publicly-accessible \\\n  --apply-immediately',
      terraform: 'resource "aws_db_instance" "prod_postgres" {\n  # ... existing config ...\n  publicly_accessible = false\n  db_subnet_group_name = aws_db_subnet_group.private.name\n}',
      cloudformation: 'ProdPostgres:\n  Type: AWS::RDS::DBInstance\n  Properties:\n    PubliclyAccessible: false\n    DBSubnetGroupName: !Ref PrivateSubnetGroup',
      estimatedMinutes: 30,
    },
    chainIds: ['scenario-002'],
    detectedAt: '2026-03-23T10:08:00Z',
    lastSeenAt: '2026-03-23T10:08:00Z',
  },
  // ── NETWORK CRITICAL ──
  {
    id: 'finding-net-001',
    checkId: 'NET-001',
    category: 'NETWORK',
    severity: 'CRITICAL',
    status: 'OPEN',
    title: 'Security Group Allows SSH from 0.0.0.0/0 (3 groups)',
    resourceId: 'sg-0abc123,sg-0def456,sg-0ghi789',
    resourceType: 'AWS::EC2::SecurityGroup',
    resourceName: 'web-servers-sg, bastion-sg, dev-sg',
    region: 'us-east-1',
    riskNarrative: '3 security groups allow inbound SSH (port 22) from any IP address on the internet. This exposes your EC2 instances to automated SSH brute-force attacks, which run constantly across the entire IPv4 space. Shodan and similar scanners have already indexed these open ports. If any EC2 instance runs an outdated OpenSSH version, this becomes a zero-click exploit vector.',
    attackVector: 'Masscan finds open port 22 → Hydra brute-forces SSH with rockyou.txt → gain shell access → enumerate instance role → find S3 credentials in instance metadata.',
    estimatedImpact: 'EC2 instance compromise → lateral movement → potential full environment takeover. Est. $890K.',
    complianceMappings: [
      { framework: 'CIS', controlId: 'CIS 5.2', controlName: 'Ensure no security groups allow ingress from 0.0.0.0/0 to SSH', status: 'FAIL' },
      { framework: 'PCI_DSS', controlId: 'PCI-DSS 1.3.1', controlName: 'Restrict inbound traffic to only that which is necessary', status: 'FAIL' },
    ],
    fixEffort: '5min',
    remediation: {
      summary: 'Restrict SSH to specific IP ranges (your office/VPN CIDR). Use AWS Systems Manager Session Manager as SSH alternative with no open ports.',
      console: '1. EC2 → Security Groups → select group\n2. Inbound rules → Edit → change 0.0.0.0/0 to your IP/CIDR\n3. Or delete the rule and use SSM Session Manager',
      cli: '# Remove the overly-broad rule\naws ec2 revoke-security-group-ingress \\\n  --group-id sg-0abc123 \\\n  --protocol tcp \\\n  --port 22 \\\n  --cidr 0.0.0.0/0\n\n# Add restricted rule (replace with your CIDR)\naws ec2 authorize-security-group-ingress \\\n  --group-id sg-0abc123 \\\n  --protocol tcp \\\n  --port 22 \\\n  --cidr 203.0.113.0/24',
      terraform: 'resource "aws_security_group_rule" "ssh_restricted" {\n  type              = "ingress"\n  from_port         = 22\n  to_port           = 22\n  protocol          = "tcp"\n  cidr_blocks       = ["203.0.113.0/24"]  # Replace with your CIDR\n  security_group_id = aws_security_group.web_servers.id\n}',
      cloudformation: 'WebServersSG:\n  Type: AWS::EC2::SecurityGroup\n  Properties:\n    SecurityGroupIngress:\n      - IpProtocol: tcp\n        FromPort: 22\n        ToPort: 22\n        CidrIp: 203.0.113.0/24  # Replace with your CIDR',
      estimatedMinutes: 10,
    },
    chainIds: ['scenario-002'],
    detectedAt: '2026-03-23T10:12:00Z',
    lastSeenAt: '2026-03-23T10:12:00Z',
  },
  {
    id: 'finding-net-002',
    checkId: 'NET-004',
    category: 'NETWORK',
    severity: 'HIGH',
    status: 'OPEN',
    title: 'VPC Flow Logs Disabled (2 VPCs)',
    resourceId: 'vpc-0abc123,vpc-0def456',
    resourceType: 'AWS::EC2::VPC',
    resourceName: 'prod-vpc, staging-vpc',
    region: 'us-east-1',
    riskNarrative: 'VPC Flow Logs are disabled on your production and staging VPCs. Flow logs capture all network traffic metadata — without them, you have zero visibility into who is connecting to your infrastructure, failed connection attempts, or data exfiltration patterns. This is the network equivalent of turning off your security cameras.',
    attackVector: 'Attacker exfiltrates data over HTTPS to an external server — without flow logs, this goes completely undetected. Incident response after a breach becomes forensically impossible.',
    estimatedImpact: 'Blind to all network-based attacks. DFIR costs increase 3x without flow logs. Direct compliance violation.',
    complianceMappings: [
      { framework: 'CIS', controlId: 'CIS 3.9', controlName: 'Ensure VPC flow logging is enabled in all VPCs', status: 'FAIL' },
      { framework: 'SOC2', controlId: 'CC7.2', controlName: 'Monitor system components for anomalies', status: 'FAIL' },
    ],
    fixEffort: '5min',
    remediation: {
      summary: 'Enable VPC Flow Logs to CloudWatch Logs or S3 for all VPCs. Retain logs for minimum 90 days.',
      console: '1. VPC → Your VPCs → select VPC → Flow logs tab\n2. Create flow log → All traffic → CloudWatch Logs\n3. Create new log group: /aws/vpc/flowlogs/prod',
      cli: 'aws ec2 create-flow-logs \\\n  --resource-type VPC \\\n  --resource-ids vpc-0abc123 \\\n  --traffic-type ALL \\\n  --log-destination-type cloud-watch-logs \\\n  --log-group-name /aws/vpc/flowlogs/prod \\\n  --deliver-logs-permission-arn arn:aws:iam::123456789012:role/FlowLogsRole',
      terraform: 'resource "aws_flow_log" "prod_vpc" {\n  vpc_id          = aws_vpc.prod.id\n  traffic_type    = "ALL"\n  iam_role_arn    = aws_iam_role.flow_logs.arn\n  log_destination = aws_cloudwatch_log_group.flow_logs.arn\n}',
      cloudformation: 'ProdVPCFlowLog:\n  Type: AWS::EC2::FlowLog\n  Properties:\n    ResourceId: !Ref ProdVPC\n    ResourceType: VPC\n    TrafficType: ALL\n    LogDestinationType: cloud-watch-logs\n    LogGroupName: /aws/vpc/flowlogs/prod',
      estimatedMinutes: 10,
    },
    chainIds: [],
    detectedAt: '2026-03-23T10:12:00Z',
    lastSeenAt: '2026-03-23T10:12:00Z',
  },
  {
    id: 'finding-iam-003',
    checkId: 'IAM-007',
    category: 'IAM',
    severity: 'HIGH',
    status: 'OPEN',
    title: 'IAM Policy with Wildcard "*" Actions on S3',
    resourceId: 'arn:aws:iam::123456789012:policy/AppServerPolicy',
    resourceType: 'AWS::IAM::Policy',
    resourceName: 'AppServerPolicy',
    region: 'global',
    riskNarrative: 'The AppServerPolicy grants s3:* (all S3 actions) on * (all buckets). Your application server only needs to read from one bucket, but this policy gives it permission to read, write, delete, and make public every S3 bucket in your account. If the application is compromised (e.g., via the SQL injection found in your SAST scan), the attacker inherits these permissions.',
    attackVector: 'SSRF vulnerability on app server → attacker calls IMDSv1 → gets instance role credentials → uses s3:* to list and download all buckets → full data exfiltration.',
    estimatedImpact: 'Data exfiltration from all S3 buckets if app server is compromised. Combines with DATA-001 for critical chain.',
    complianceMappings: [
      { framework: 'CIS', controlId: 'CIS 1.16', controlName: 'Ensure IAM policies are attached only to groups or roles', status: 'PARTIAL' },
      { framework: 'SOC2', controlId: 'CC6.3', controlName: 'Role-based access control', status: 'FAIL' },
    ],
    fixEffort: '1hr',
    remediation: {
      summary: 'Scope the IAM policy to only the specific S3 actions and bucket your app actually needs.',
      console: '1. IAM → Policies → AppServerPolicy → Edit\n2. Replace s3:* with specific actions: s3:GetObject, s3:PutObject\n3. Replace * with specific bucket ARN',
      cli: '# Create a new scoped policy\naws iam create-policy \\\n  --policy-name AppServerPolicyScoped \\\n  --policy-document \'{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:GetObject","s3:PutObject"],"Resource":"arn:aws:s3:::prod-app-assets/*"}]}\'',
      terraform: 'resource "aws_iam_policy" "app_server" {\n  name = "AppServerPolicy"\n  policy = jsonencode({\n    Version = "2012-10-17"\n    Statement = [{\n      Effect   = "Allow"\n      Action   = ["s3:GetObject", "s3:PutObject"]\n      Resource = "arn:aws:s3:::prod-app-assets/*"\n    }]\n  })\n}',
      cloudformation: 'AppServerPolicy:\n  Type: AWS::IAM::ManagedPolicy\n  Properties:\n    PolicyDocument:\n      Version: "2012-10-17"\n      Statement:\n        - Effect: Allow\n          Action:\n            - s3:GetObject\n            - s3:PutObject\n          Resource: arn:aws:s3:::prod-app-assets/*',
      estimatedMinutes: 30,
    },
    chainIds: ['scenario-001'],
    detectedAt: '2026-03-23T10:05:00Z',
    lastSeenAt: '2026-03-23T10:05:00Z',
  },
  {
    id: 'finding-data-003',
    checkId: 'DATA-006',
    category: 'DATA',
    severity: 'HIGH',
    status: 'OPEN',
    title: 'RDS Automated Backups Disabled',
    resourceId: 'arn:aws:rds:us-east-1:123456789012:db:prod-postgres',
    resourceType: 'AWS::RDS::DBInstance',
    resourceName: 'prod-postgres',
    region: 'us-east-1',
    riskNarrative: 'Automated backups are disabled on your production PostgreSQL database. Ransomware attacks increasingly target databases — encrypting or deleting data and demanding payment. Without backups, a successful ransomware attack on your database means permanent data loss with no recovery option.',
    attackVector: 'Attacker gains DB access → runs DROP TABLE on all tables → demands ransom. Without backups, data is unrecoverable.',
    estimatedImpact: 'Permanent data loss in ransomware scenario. Business continuity failure. Est. $2M+ recovery cost.',
    complianceMappings: [
      { framework: 'CIS', controlId: 'CIS 2.3.2', controlName: 'Ensure RDS automated backups are enabled', status: 'FAIL' },
      { framework: 'PCI_DSS', controlId: 'PCI-DSS 12.10.1', controlName: 'Incident response and recovery plans', status: 'PARTIAL' },
    ],
    fixEffort: '5min',
    remediation: {
      summary: 'Enable automated backups with minimum 7-day retention. Set backup window during low-traffic hours.',
      console: '1. RDS → prod-postgres → Modify\n2. Backup → Backup retention period → 7 days\n3. Apply immediately',
      cli: 'aws rds modify-db-instance \\\n  --db-instance-identifier prod-postgres \\\n  --backup-retention-period 7 \\\n  --preferred-backup-window "02:00-03:00" \\\n  --apply-immediately',
      terraform: 'resource "aws_db_instance" "prod_postgres" {\n  backup_retention_period = 7\n  backup_window           = "02:00-03:00"\n}',
      cloudformation: 'ProdPostgres:\n  Type: AWS::RDS::DBInstance\n  Properties:\n    BackupRetentionPeriod: 7\n    PreferredBackupWindow: "02:00-03:00"',
      estimatedMinutes: 5,
    },
    chainIds: [],
    detectedAt: '2026-03-23T10:08:00Z',
    lastSeenAt: '2026-03-23T10:08:00Z',
  },
  {
    id: 'finding-iam-004',
    checkId: 'IAM-005',
    category: 'IAM',
    severity: 'MEDIUM',
    status: 'OPEN',
    title: 'CloudTrail Not Enabled in All Regions',
    resourceId: 'arn:aws:cloudtrail:us-east-1:123456789012:trail/main-trail',
    resourceType: 'AWS::CloudTrail::Trail',
    resourceName: 'main-trail',
    region: 'global',
    riskNarrative: 'Your CloudTrail only covers us-east-1. Attackers who discover this commonly create resources in uncovered regions (us-west-2, eu-west-1) to operate undetected. API calls in those regions — creating backdoor IAM users, launching EC2 instances, exfiltrating data — leave no audit trail.',
    attackVector: 'Attacker compromises credentials → checks CloudTrail coverage → pivots to eu-west-1 → creates backdoor IAM admin user → all activity invisible.',
    estimatedImpact: 'Forensic blindspot enabling persistent undetected access. Incident response failure.',
    complianceMappings: [
      { framework: 'CIS', controlId: 'CIS 3.1', controlName: 'Ensure CloudTrail is enabled in all regions', status: 'FAIL' },
      { framework: 'SOC2', controlId: 'CC7.2', controlName: 'System monitoring', status: 'PARTIAL' },
    ],
    fixEffort: '5min',
    remediation: {
      summary: 'Enable multi-region CloudTrail with log file validation.',
      console: '1. CloudTrail → Trails → main-trail → Edit\n2. Enable "Apply trail to all regions"\n3. Enable log file validation',
      cli: 'aws cloudtrail update-trail \\\n  --name main-trail \\\n  --is-multi-region-trail \\\n  --enable-log-file-validation',
      terraform: 'resource "aws_cloudtrail" "main" {\n  name                          = "main-trail"\n  s3_bucket_name                = aws_s3_bucket.cloudtrail.id\n  is_multi_region_trail         = true\n  enable_log_file_validation    = true\n  include_global_service_events = true\n}',
      cloudformation: 'MainTrail:\n  Type: AWS::CloudTrail::Trail\n  Properties:\n    TrailName: main-trail\n    IsMultiRegionTrail: true\n    EnableLogFileValidation: true\n    IncludeGlobalServiceEvents: true\n    IsLogging: true',
      estimatedMinutes: 5,
    },
    chainIds: [],
    detectedAt: '2026-03-23T10:05:00Z',
    lastSeenAt: '2026-03-23T10:05:00Z',
  },
]

// ─── Attack Scenarios ─────────────────────────────────────────────────────────
export const MOCK_ATTACK_SCENARIOS: AttackScenario[] = [
  {
    id: 'scenario-001',
    title: 'Credential Compromise → Full Account Takeover',
    severity: 'CRITICAL',
    likelihood: 'HIGH',
    narrative: 'An attacker phishes or brute-forces an IAM user with no MFA (finding IAM-003). Once inside, they discover the overly-permissive AppServerPolicy (finding IAM-007) which grants s3:* on all buckets. They exfiltrate data from prod-customer-uploads (finding DATA-001). Because CloudTrail is not multi-region (finding IAM-005), they create a backdoor IAM admin user in eu-west-1 and maintain persistent access even after the compromised user\'s password is reset.',
    steps: [
      { seq: 1, action: 'Phish/brute-force IAM user with no MFA', findingId: 'finding-iam-002', technique: 'Valid Accounts (T1078)' },
      { seq: 2, action: 'Enumerate IAM permissions and discover wildcard S3 policy', findingId: 'finding-iam-003', technique: 'Cloud Infrastructure Discovery (T1580)' },
      { seq: 3, action: 'Exfiltrate all data from public S3 bucket', findingId: 'finding-data-001', technique: 'Data from Cloud Storage (T1530)' },
      { seq: 4, action: 'Create backdoor IAM admin in uncovered region', findingId: 'finding-iam-004', technique: 'Create Account (T1136)' },
    ],
    findingIds: ['finding-iam-002', 'finding-iam-003', 'finding-data-001', 'finding-iam-004'],
    estimatedBreachCost: 2100000,
    affectedDataTypes: ['PII', 'Customer Records', 'Financial Data'],
    complianceImpact: ['PCI_DSS', 'SOC2', 'HIPAA'],
  },
  {
    id: 'scenario-002',
    title: 'External Attack → Database Exfiltration',
    severity: 'CRITICAL',
    likelihood: 'HIGH',
    narrative: 'An attacker uses Masscan to discover open SSH (finding NET-001) and PostgreSQL ports (finding DATA-002). They brute-force the PostgreSQL database directly over the internet. With no VPC flow logs (finding NET-002) the attack goes undetected. They dump the entire database, which is not encrypted. Recovery is impossible because automated backups are disabled (finding DATA-003).',
    steps: [
      { seq: 1, action: 'Masscan discovers open ports 22 and 5432', findingId: 'finding-net-001', technique: 'Network Service Scanning (T1046)' },
      { seq: 2, action: 'Brute-force publicly accessible RDS instance', findingId: 'finding-data-002', technique: 'Brute Force (T1110)' },
      { seq: 3, action: 'Dump entire database — attack invisible without flow logs', findingId: 'finding-net-002', technique: 'Data from Databases (T1213)' },
      { seq: 4, action: 'Delete database tables — no backups to recover from', findingId: 'finding-data-003', technique: 'Data Destruction (T1485)' },
    ],
    findingIds: ['finding-net-001', 'finding-data-002', 'finding-net-002', 'finding-data-003'],
    estimatedBreachCost: 1800000,
    affectedDataTypes: ['Database Records', 'Customer Data', 'Application Data'],
    complianceImpact: ['PCI_DSS', 'SOC2'],
  },
]

// ─── Inventory ─────────────────────────────────────────────────────────────────
export const MOCK_CLOUD_INVENTORY: CloudInventory = {
  ec2Instances: [
    { id: 'i-0abc123', arn: 'arn:aws:ec2:us-east-1:123456789012:instance/i-0abc123', name: 'web-server-01', type: 'AWS::EC2::Instance', region: 'us-east-1', tags: { Environment: 'prod', Team: 'platform' }, securityStatus: 'CRITICAL', findingIds: ['finding-net-001'] },
    { id: 'i-0def456', arn: 'arn:aws:ec2:us-east-1:123456789012:instance/i-0def456', name: 'api-server-01', type: 'AWS::EC2::Instance', region: 'us-east-1', tags: { Environment: 'prod', Team: 'backend' }, securityStatus: 'WARNING', findingIds: ['finding-iam-003'] },
    { id: 'i-0ghi789', arn: 'arn:aws:ec2:us-east-1:123456789012:instance/i-0ghi789', name: 'bastion-host', type: 'AWS::EC2::Instance', region: 'us-east-1', tags: { Environment: 'prod', Role: 'bastion' }, securityStatus: 'CRITICAL', findingIds: ['finding-net-001'] },
  ],
  s3Buckets: [
    { id: 'prod-customer-uploads', arn: 'arn:aws:s3:::prod-customer-uploads', name: 'prod-customer-uploads', type: 'AWS::S3::Bucket', region: 'global', tags: { Environment: 'prod', DataClass: 'PII' }, securityStatus: 'CRITICAL', findingIds: ['finding-data-001'] },
    { id: 'prod-app-assets', arn: 'arn:aws:s3:::prod-app-assets', name: 'prod-app-assets', type: 'AWS::S3::Bucket', region: 'global', tags: { Environment: 'prod' }, securityStatus: 'CLEAN', findingIds: [] },
    { id: 'prod-logs', arn: 'arn:aws:s3:::prod-logs', name: 'prod-logs', type: 'AWS::S3::Bucket', region: 'global', tags: { Environment: 'prod', Purpose: 'logs' }, securityStatus: 'CLEAN', findingIds: [] },
  ],
  rdsInstances: [
    { id: 'prod-postgres', arn: 'arn:aws:rds:us-east-1:123456789012:db:prod-postgres', name: 'prod-postgres', type: 'AWS::RDS::DBInstance', region: 'us-east-1', tags: { Environment: 'prod', Engine: 'postgres' }, securityStatus: 'CRITICAL', findingIds: ['finding-data-002', 'finding-data-003'] },
  ],
  iamUsers: [
    { id: 'john.smith', arn: 'arn:aws:iam::123456789012:user/john.smith', name: 'john.smith', type: 'AWS::IAM::User', region: 'global', tags: {}, securityStatus: 'CRITICAL', findingIds: ['finding-iam-002'] },
    { id: 'sarah.jones', arn: 'arn:aws:iam::123456789012:user/sarah.jones', name: 'sarah.jones', type: 'AWS::IAM::User', region: 'global', tags: {}, securityStatus: 'CRITICAL', findingIds: ['finding-iam-002'] },
    { id: 'ci-bot', arn: 'arn:aws:iam::123456789012:user/ci-bot', name: 'ci-bot', type: 'AWS::IAM::User', region: 'global', tags: { Purpose: 'cicd' }, securityStatus: 'WARNING', findingIds: ['finding-iam-002'] },
  ],
  iamRoles: [
    { id: 'AppServerRole', arn: 'arn:aws:iam::123456789012:role/AppServerRole', name: 'AppServerRole', type: 'AWS::IAM::Role', region: 'global', tags: {}, securityStatus: 'WARNING', findingIds: ['finding-iam-003'] },
    { id: 'HemisXScannerRole', arn: 'arn:aws:iam::123456789012:role/HemisXScannerRole', name: 'HemisXScannerRole', type: 'AWS::IAM::Role', region: 'global', tags: { Purpose: 'security-scan' }, securityStatus: 'CLEAN', findingIds: [] },
  ],
  lambdaFunctions: [
    { id: 'prod-payment-processor', arn: 'arn:aws:lambda:us-east-1:123456789012:function:prod-payment-processor', name: 'prod-payment-processor', type: 'AWS::Lambda::Function', region: 'us-east-1', tags: { Environment: 'prod' }, securityStatus: 'CLEAN', findingIds: [] },
  ],
  securityGroups: [
    { id: 'sg-0abc123', arn: 'arn:aws:ec2:us-east-1:123456789012:security-group/sg-0abc123', name: 'web-servers-sg', type: 'AWS::EC2::SecurityGroup', region: 'us-east-1', tags: {}, securityStatus: 'CRITICAL', findingIds: ['finding-net-001'] },
    { id: 'sg-0def456', arn: 'arn:aws:ec2:us-east-1:123456789012:security-group/sg-0def456', name: 'bastion-sg', type: 'AWS::EC2::SecurityGroup', region: 'us-east-1', tags: {}, securityStatus: 'CRITICAL', findingIds: ['finding-net-001'] },
  ],
  vpcs: [
    { id: 'vpc-0abc123', arn: 'arn:aws:ec2:us-east-1:123456789012:vpc/vpc-0abc123', name: 'prod-vpc', type: 'AWS::EC2::VPC', region: 'us-east-1', tags: { Environment: 'prod' }, securityStatus: 'WARNING', findingIds: ['finding-net-002'] },
    { id: 'vpc-0def456', arn: 'arn:aws:ec2:us-east-1:123456789012:vpc/vpc-0def456', name: 'staging-vpc', type: 'AWS::EC2::VPC', region: 'us-east-1', tags: { Environment: 'staging' }, securityStatus: 'WARNING', findingIds: ['finding-net-002'] },
  ],
  totalResources: 17,
}

// ─── Compliance Scores ────────────────────────────────────────────────────────
export const MOCK_COMPLIANCE_SCORES: ComplianceScore[] = [
  {
    framework: 'CIS',
    score: 42,
    passed: 38,
    failed: 27,
    total: 65,
    gaps: [
      { controlId: 'CIS 1.4', controlName: 'No root account access key', status: 'FAIL', findingIds: ['finding-iam-001'], severity: 'CRITICAL' },
      { controlId: 'CIS 1.10', controlName: 'MFA enabled for all console users', status: 'FAIL', findingIds: ['finding-iam-002'], severity: 'CRITICAL' },
      { controlId: 'CIS 2.1.5', controlName: 'S3 buckets not publicly accessible', status: 'FAIL', findingIds: ['finding-data-001'], severity: 'CRITICAL' },
      { controlId: 'CIS 2.3.1', controlName: 'RDS not publicly accessible', status: 'FAIL', findingIds: ['finding-data-002'], severity: 'HIGH' },
      { controlId: 'CIS 3.1', controlName: 'CloudTrail enabled in all regions', status: 'FAIL', findingIds: ['finding-iam-004'], severity: 'MEDIUM' },
      { controlId: 'CIS 3.9', controlName: 'VPC flow logging enabled', status: 'FAIL', findingIds: ['finding-net-002'], severity: 'HIGH' },
      { controlId: 'CIS 5.2', controlName: 'No SG ingress from 0.0.0.0/0 to SSH', status: 'FAIL', findingIds: ['finding-net-001'], severity: 'CRITICAL' },
    ],
  },
  {
    framework: 'PCI_DSS',
    score: 38,
    passed: 22,
    failed: 14,
    total: 36,
    gaps: [
      { controlId: 'PCI-DSS 7.1', controlName: 'Limit access to system components', status: 'FAIL', findingIds: ['finding-iam-001'], severity: 'CRITICAL' },
      { controlId: 'PCI-DSS 8.3.1', controlName: 'MFA for non-console admin access', status: 'FAIL', findingIds: ['finding-iam-002'], severity: 'CRITICAL' },
      { controlId: 'PCI-DSS 1.3', controlName: 'Prohibit direct public access to CDE', status: 'FAIL', findingIds: ['finding-data-002'], severity: 'HIGH' },
      { controlId: 'PCI-DSS 3.4', controlName: 'Protect stored cardholder data', status: 'FAIL', findingIds: ['finding-data-001'], severity: 'CRITICAL' },
      { controlId: 'PCI-DSS 1.3.1', controlName: 'Restrict inbound traffic', status: 'FAIL', findingIds: ['finding-net-001'], severity: 'CRITICAL' },
    ],
  },
  {
    framework: 'SOC2',
    score: 55,
    passed: 31,
    failed: 19,
    total: 50,
    gaps: [
      { controlId: 'CC6.3', controlName: 'Logical access controls', status: 'FAIL', findingIds: ['finding-iam-002', 'finding-iam-003'], severity: 'CRITICAL' },
      { controlId: 'CC6.1', controlName: 'Access restriction', status: 'FAIL', findingIds: ['finding-data-001'], severity: 'CRITICAL' },
      { controlId: 'CC7.2', controlName: 'System monitoring', status: 'FAIL', findingIds: ['finding-iam-004', 'finding-net-002'], severity: 'MEDIUM' },
    ],
  },
  {
    framework: 'HIPAA',
    score: 61,
    passed: 28,
    failed: 12,
    total: 40,
    gaps: [
      { controlId: 'HIPAA 164.312(d)', controlName: 'Person/entity authentication', status: 'FAIL', findingIds: ['finding-iam-002'], severity: 'CRITICAL' },
      { controlId: 'HIPAA 164.312(a)', controlName: 'Access control', status: 'FAIL', findingIds: ['finding-data-001'], severity: 'CRITICAL' },
    ],
  },
]

// ─── Remediation Queue ────────────────────────────────────────────────────────
export const MOCK_REMEDIATION_QUEUE: RemediationItem[] = [
  { priority: 1, findingId: 'finding-iam-001', title: 'Delete root account access keys', severity: 'CRITICAL', effort: '5min', estimatedMinutes: 5, impactScore: 98, category: 'IAM', status: 'OPEN' },
  { priority: 2, findingId: 'finding-data-001', title: 'Block public access on prod-customer-uploads S3 bucket', severity: 'CRITICAL', effort: '5min', estimatedMinutes: 5, impactScore: 96, category: 'DATA', status: 'OPEN' },
  { priority: 3, findingId: 'finding-net-001', title: 'Restrict SSH security groups from 0.0.0.0/0', severity: 'CRITICAL', effort: '5min', estimatedMinutes: 10, impactScore: 93, category: 'NETWORK', status: 'OPEN' },
  { priority: 4, findingId: 'finding-iam-004', title: 'Enable multi-region CloudTrail', severity: 'MEDIUM', effort: '5min', estimatedMinutes: 5, impactScore: 88, category: 'IAM', status: 'OPEN' },
  { priority: 5, findingId: 'finding-net-002', title: 'Enable VPC Flow Logs on prod and staging VPCs', severity: 'HIGH', effort: '5min', estimatedMinutes: 10, impactScore: 85, category: 'NETWORK', status: 'OPEN' },
  { priority: 6, findingId: 'finding-data-002', title: 'Disable public access on prod-postgres RDS', severity: 'HIGH', effort: '1hr', estimatedMinutes: 30, impactScore: 82, category: 'DATA', status: 'OPEN' },
  { priority: 7, findingId: 'finding-iam-002', title: 'Enforce MFA for all IAM console users', severity: 'CRITICAL', effort: '1hr', estimatedMinutes: 60, impactScore: 79, category: 'IAM', status: 'OPEN' },
  { priority: 8, findingId: 'finding-data-003', title: 'Enable RDS automated backups (7-day retention)', severity: 'HIGH', effort: '5min', estimatedMinutes: 5, impactScore: 75, category: 'DATA', status: 'OPEN' },
  { priority: 9, findingId: 'finding-iam-003', title: 'Remove wildcard S3 permissions from AppServerPolicy', severity: 'HIGH', effort: '1hr', estimatedMinutes: 30, impactScore: 70, category: 'IAM', status: 'OPEN' },
]

// ─── Full Scan ─────────────────────────────────────────────────────────────────
export const MOCK_CLOUD_SCAN: CloudScan = {
  id: 'scan-aws-demo-001',
  connectionId: 'conn-aws-demo-001',
  accountId: '123456789012',
  accountAlias: 'acme-production',
  status: 'COMPLETED',
  progress: 100,
  currentPhase: 'completed',
  startedAt: '2026-03-23T10:00:00Z',
  completedAt: '2026-03-23T10:04:32Z',
  duration: 272000,
  riskScore: 78,
  riskLevel: 'CRITICAL',
  summary: {
    totalFindings: 9,
    critical: 4,
    high: 4,
    medium: 1,
    low: 0,
    info: 0,
    byCategory: { IAM: 4, DATA: 3, NETWORK: 2 },
    estimatedBreachCost: 3900000,
    resourcesScanned: 17,
    checksRun: 65,
    checksPassed: 56,
    checksFailed: 9,
  },
  findings: MOCK_CLOUD_FINDINGS,
  inventory: MOCK_CLOUD_INVENTORY,
  complianceScores: MOCK_COMPLIANCE_SCORES,
  attackScenarios: MOCK_ATTACK_SCENARIOS,
  remediationQueue: MOCK_REMEDIATION_QUEUE,
}

// ─── For import dropdown ───────────────────────────────────────────────────────
export const MOCK_PAST_SCANS = [
  { id: 'scan-aws-demo-001', accountAlias: 'acme-production', date: '2026-03-23', findingsCount: 9, riskScore: 78 },
  { id: 'scan-aws-demo-002', accountAlias: 'acme-staging', date: '2026-03-20', findingsCount: 4, riskScore: 42 },
]
