import type { DastScan, DastFinding } from '@/lib/types'

export const MOCK_DAST_SCANS: DastScan[] = [
  {
    id: 'dast-scan-001',
    orgId: 'org-acme',
    name: 'Production API Audit',
    targetUrl: 'https://api.acme-corp.com',
    scanProfile: 'full',
    status: 'COMPLETED',
    progress: 100,
    currentPhase: 'complete',
    riskScore: 72,
    endpointsDiscovered: 156,
    endpointsTested: 148,
    payloadsSent: 3420,
    criticalCount: 3,
    highCount: 5,
    mediumCount: 8,
    lowCount: 4,
    infoCount: 2,
    executiveSummary: 'The security assessment of api.acme-corp.com revealed 22 findings across 148 tested endpoints. Three critical vulnerabilities were identified including SQL injection in the authentication module and an SSRF vulnerability in the file import feature. Immediate remediation is recommended for all critical and high-severity issues. The application shows strong TLS configuration but lacks adequate input validation on multiple API endpoints.',
    reportUrl: null,
    startedAt: '2026-03-14T08:00:00Z',
    completedAt: '2026-03-14T08:42:00Z',
    createdAt: '2026-03-14T07:55:00Z',
  },
  {
    id: 'dast-scan-002',
    orgId: 'org-acme',
    name: 'Staging Web App',
    targetUrl: 'https://staging.acme-corp.com',
    scanProfile: 'quick',
    status: 'COMPLETED',
    progress: 100,
    currentPhase: 'complete',
    riskScore: 35,
    endpointsDiscovered: 42,
    endpointsTested: 38,
    payloadsSent: 890,
    criticalCount: 0,
    highCount: 2,
    mediumCount: 3,
    lowCount: 5,
    infoCount: 1,
    executiveSummary: null,
    reportUrl: null,
    startedAt: '2026-03-13T14:10:00Z',
    completedAt: '2026-03-13T14:28:00Z',
    createdAt: '2026-03-13T14:05:00Z',
  },
]

export const MOCK_DAST_FINDINGS: DastFinding[] = [
  {
    id: 'f-001',
    scanId: 'dast-scan-001',
    type: 'sql_injection',
    owaspCategory: 'A03:2021 Injection',
    cweId: 'CWE-89',
    severity: 'CRITICAL',
    cvssScore: 9.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    riskScore: 98,
    title: 'SQL Injection in Authentication Endpoint',
    description: 'The /api/auth/login endpoint is vulnerable to SQL injection through the username parameter. An attacker can bypass authentication, extract sensitive data, or modify database records.',
    businessImpact: 'Full database compromise is possible. An attacker could exfiltrate all user credentials, PII, and financial records. This could lead to regulatory penalties, data breach notifications, and significant reputational damage.',
    affectedUrl: 'https://api.acme-corp.com/api/auth/login',
    affectedParameter: 'username',
    payload: "' OR 1=1 --",
    remediation: 'Use parameterized queries or prepared statements. Never concatenate user input directly into SQL queries.',
    remediationCode: JSON.stringify({
      vulnerableCode: "const query = `SELECT * FROM users WHERE username = '${req.body.username}'`;\nconst result = await db.query(query);",
      remediatedCode: "const query = 'SELECT * FROM users WHERE username = $1';\nconst result = await db.query(query, [req.body.username]);",
      explanation: 'Parameterized queries separate SQL logic from data, preventing injection attacks.',
      dependencies: [],
      testingGuidance: 'Try submitting SQL metacharacters in the username field and verify they are treated as literal strings.',
    }),
    pciDssRefs: ['6.5.1'],
    soc2Refs: ['CC6.1'],
    mitreAttackIds: ['T1190'],
    confidenceScore: 95,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'f-002',
    scanId: 'dast-scan-001',
    type: 'ssrf',
    owaspCategory: 'A10:2021 SSRF',
    cweId: 'CWE-918',
    severity: 'CRITICAL',
    cvssScore: 8.6,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:N/A:N',
    riskScore: 86,
    title: 'Server-Side Request Forgery in File Import',
    description: 'The /api/imports/url endpoint allows server-side requests to arbitrary internal addresses via the url parameter. An attacker can scan internal networks, access cloud metadata services, and read internal resources.',
    businessImpact: 'Could enable access to internal services, AWS metadata (IMDSv1), and sensitive configuration. Potential for full cloud account compromise via exposed IAM credentials.',
    affectedUrl: 'https://api.acme-corp.com/api/imports/url',
    affectedParameter: 'url',
    payload: 'http://169.254.169.254/latest/meta-data/iam/security-credentials/',
    remediation: 'Validate and whitelist allowed URL schemes and hosts. Block requests to private IP ranges and cloud metadata endpoints.',
    remediationCode: null,
    pciDssRefs: ['6.5.9'],
    soc2Refs: ['CC6.1', 'CC6.6'],
    mitreAttackIds: ['T1190', 'T1552'],
    confidenceScore: 90,
    status: 'OPEN',
    isConfirmed: false,
  },
  {
    id: 'f-003',
    scanId: 'dast-scan-001',
    type: 'xss_reflected',
    owaspCategory: 'A03:2021 Injection',
    cweId: 'CWE-79',
    severity: 'CRITICAL',
    cvssScore: 6.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N',
    riskScore: 61,
    title: 'Reflected XSS in Search Results',
    description: 'The search parameter on /search is reflected in the response without proper encoding, allowing execution of arbitrary JavaScript in victim browsers.',
    businessImpact: 'Session hijacking, credential theft, and phishing attacks against authenticated users. Could be chained with other vulnerabilities for greater impact.',
    affectedUrl: 'https://api.acme-corp.com/search',
    affectedParameter: 'q',
    payload: '<script>alert(document.cookie)</script>',
    remediation: 'HTML-encode all user input before rendering in response. Implement Content-Security-Policy headers.',
    remediationCode: JSON.stringify({
      vulnerableCode: 'res.send(`<p>Results for: ${req.query.q}</p>`);',
      remediatedCode: 'const escaped = escapeHtml(req.query.q);\nres.send(`<p>Results for: ${escaped}</p>`);',
      explanation: 'HTML entity encoding prevents the browser from interpreting user input as executable markup.',
      dependencies: [],
      testingGuidance: 'Submit HTML tags and verify they appear as plain text in the response.',
    }),
    pciDssRefs: ['6.5.7'],
    soc2Refs: ['CC6.1'],
    mitreAttackIds: ['T1189'],
    confidenceScore: 85,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'f-004',
    scanId: 'dast-scan-001',
    type: 'broken_access_control',
    owaspCategory: 'A01:2021 Broken Access Control',
    cweId: 'CWE-639',
    severity: 'HIGH',
    cvssScore: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N',
    riskScore: 75,
    title: 'IDOR on User Profile API',
    description: 'The /api/users/:id endpoint allows authenticated users to access other users profile data by modifying the ID parameter without proper authorization checks.',
    businessImpact: 'Any authenticated user can access personal information of all other users, including email addresses, phone numbers, and account details.',
    affectedUrl: 'https://api.acme-corp.com/api/users/12345',
    affectedParameter: 'id',
    payload: null,
    remediation: 'Implement object-level authorization checks to verify the requesting user has permission to access the requested resource.',
    remediationCode: null,
    pciDssRefs: ['6.5.4'],
    soc2Refs: ['CC6.1', 'CC6.3'],
    mitreAttackIds: ['T1078'],
    confidenceScore: 80,
    status: 'OPEN',
    isConfirmed: false,
  },
  {
    id: 'f-005',
    scanId: 'dast-scan-001',
    type: 'security_misconfiguration',
    owaspCategory: 'A05:2021 Security Misconfiguration',
    cweId: 'CWE-693',
    severity: 'HIGH',
    cvssScore: 5.3,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N',
    riskScore: 53,
    title: 'Missing Security Headers',
    description: 'Several security headers are missing: Content-Security-Policy, X-Content-Type-Options, Strict-Transport-Security, X-Frame-Options.',
    businessImpact: 'Increases attack surface for clickjacking, MIME-type confusion, and downgrade attacks.',
    affectedUrl: 'https://api.acme-corp.com/',
    affectedParameter: null,
    payload: null,
    remediation: 'Add security headers: Content-Security-Policy, X-Content-Type-Options: nosniff, Strict-Transport-Security, X-Frame-Options: DENY.',
    remediationCode: null,
    pciDssRefs: ['6.5.10'],
    soc2Refs: ['CC6.6'],
    mitreAttackIds: [],
    confidenceScore: 100,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'f-006',
    scanId: 'dast-scan-001',
    type: 'information_disclosure',
    owaspCategory: 'A05:2021 Security Misconfiguration',
    cweId: 'CWE-200',
    severity: 'MEDIUM',
    cvssScore: 4.3,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:N/A:N',
    riskScore: 43,
    title: 'Stack Trace Exposed in Error Responses',
    description: 'API error responses include full stack traces with file paths, library versions, and internal function names.',
    businessImpact: 'Reveals internal architecture details that aid attackers in crafting targeted exploits.',
    affectedUrl: 'https://api.acme-corp.com/api/nonexistent',
    affectedParameter: null,
    payload: null,
    remediation: 'Configure error handling to return generic error messages in production. Log detailed errors server-side only.',
    remediationCode: null,
    pciDssRefs: ['6.5.5'],
    soc2Refs: [],
    mitreAttackIds: ['T1592'],
    confidenceScore: 95,
    status: 'ACKNOWLEDGED',
    isConfirmed: true,
  },
  {
    id: 'f-007',
    scanId: 'dast-scan-001',
    type: 'csrf',
    owaspCategory: 'A01:2021 Broken Access Control',
    cweId: 'CWE-352',
    severity: 'MEDIUM',
    cvssScore: 6.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N',
    riskScore: 65,
    title: 'Cross-Site Request Forgery on Settings Update',
    description: 'The /api/settings/update endpoint does not validate CSRF tokens, allowing attackers to forge state-changing requests.',
    businessImpact: 'An attacker could trick users into changing their account settings, email address, or password through malicious links.',
    affectedUrl: 'https://api.acme-corp.com/api/settings/update',
    affectedParameter: null,
    payload: null,
    remediation: 'Implement anti-CSRF tokens for all state-changing operations. Use SameSite cookie attribute.',
    remediationCode: null,
    pciDssRefs: ['6.5.9'],
    soc2Refs: ['CC6.1'],
    mitreAttackIds: [],
    confidenceScore: 75,
    status: 'OPEN',
    isConfirmed: false,
  },
]
