import type {
  WbrtEngagement,
  AttackGraph,
  AttackGraphNode,
  AttackGraphEdge,
  KillChain,
  WbrtFinding,
  WbrtReport,
  ComplianceGap,
  RemediationItem,
} from '@/lib/types/wbrt'

// ─── Node IDs (stable references for edges, kill chains, findings) ──────────
const N = {
  // Entry points
  LOGIN_API:       'node-ep-login-api',
  PAYMENT_API:     'node-ep-payment-api',
  FILE_UPLOAD:     'node-ep-file-upload',
  // Vulnerabilities
  SQLI_LOGIN:      'node-vuln-sqli-login',
  HARDCODED_KEY:   'node-vuln-hardcoded-api-key',
  PATH_TRAVERSAL:  'node-vuln-path-traversal',
  SSRF_INTERNAL:   'node-vuln-ssrf-internal',
  WEAK_JWT:        'node-vuln-weak-jwt',
  // Assets
  APP_SERVER:      'node-asset-app-server',
  REDIS_CACHE:     'node-asset-redis',
  STRIPE_SERVICE:  'node-asset-stripe',
  // Privileges
  DB_READ:         'node-priv-db-read',
  IAM_ROLE:        'node-priv-iam-role',
  // Crown jewels
  PG_DATABASE:     'node-cj-postgres',
  S3_PII_BUCKET:   'node-cj-s3-pii',
} as const

// ─── Attack Graph Nodes (15 total) ─────────────────────────────────────────
const NODES: AttackGraphNode[] = [
  // Entry points (3)
  {
    id: N.LOGIN_API,
    type: 'entry_point',
    label: 'Login API (/api/auth/login)',
    description: 'Public-facing authentication endpoint accepting email/password via POST. No rate limiting detected.',
    severity: 'CRITICAL',
    metadata: { file: 'src/app/api/auth/login/route.ts', line: '14', service: 'next-app', cwe: 'CWE-89' },
  },
  {
    id: N.PAYMENT_API,
    type: 'entry_point',
    label: 'Payment API (/api/payments)',
    description: 'Stripe-integrated payment processing endpoint handling card tokens and PCI-scoped data.',
    severity: 'HIGH',
    metadata: { file: 'src/app/api/payments/route.ts', line: '27', service: 'next-app', cwe: 'CWE-311' },
  },
  {
    id: N.FILE_UPLOAD,
    type: 'entry_point',
    label: 'File Upload (/api/documents/upload)',
    description: 'Document upload endpoint with insufficient path validation, allowing directory traversal.',
    severity: 'HIGH',
    metadata: { file: 'src/app/api/documents/upload/route.ts', line: '42', service: 'next-app', cwe: 'CWE-22' },
  },

  // Vulnerabilities (5)
  {
    id: N.SQLI_LOGIN,
    type: 'vulnerability',
    label: 'SQL Injection in Login',
    description: 'User-supplied email parameter concatenated directly into SQL query without parameterization. Allows UNION-based extraction of arbitrary database tables.',
    severity: 'CRITICAL',
    metadata: { file: 'src/lib/services/auth.ts', line: '31', cwe: 'CWE-89', cvss: '9.8' },
  },
  {
    id: N.HARDCODED_KEY,
    type: 'vulnerability',
    label: 'Hardcoded Stripe API Key',
    description: 'Stripe secret key (sk_live_*) committed in plaintext in the payments service module. Grants full access to Stripe account including refunds and customer data.',
    severity: 'CRITICAL',
    metadata: { file: 'src/lib/services/payments.ts', line: '8', cwe: 'CWE-798', secret_type: 'stripe_secret_key' },
  },
  {
    id: N.PATH_TRAVERSAL,
    type: 'vulnerability',
    label: 'Path Traversal in Upload',
    description: 'User-controlled filename passed to fs.readFile without sanitization. Attackers can read arbitrary files including .env and config files.',
    severity: 'HIGH',
    metadata: { file: 'src/app/api/documents/upload/route.ts', line: '56', cwe: 'CWE-22', cvss: '7.5' },
  },
  {
    id: N.SSRF_INTERNAL,
    type: 'vulnerability',
    label: 'SSRF via Webhook URL',
    description: 'User-supplied webhook URL fetched server-side without allowlist validation. Can reach internal metadata endpoint (169.254.169.254) and Redis.',
    severity: 'HIGH',
    metadata: { file: 'src/lib/services/webhooks.ts', line: '19', cwe: 'CWE-918', cvss: '8.1' },
  },
  {
    id: N.WEAK_JWT,
    type: 'vulnerability',
    label: 'Weak JWT Secret',
    description: 'JWT signing uses a static secret "hemisx-dev-secret" with HS256. Easily brute-forced, enabling token forgery for any user including admin.',
    severity: 'HIGH',
    metadata: { file: 'src/lib/auth/jwt.ts', line: '5', cwe: 'CWE-347', cvss: '7.2' },
  },

  // Assets (3)
  {
    id: N.APP_SERVER,
    type: 'asset',
    label: 'Next.js Application Server',
    description: 'Primary application server running Next.js 15 on AWS ECS Fargate. Hosts all API routes and SSR pages. IAM task role attached with S3 and SES permissions.',
    metadata: { service: 'ecs-fargate', region: 'us-east-1', runtime: 'Node.js 20' },
  },
  {
    id: N.REDIS_CACHE,
    type: 'asset',
    label: 'Redis Session Store',
    description: 'ElastiCache Redis 7.x cluster storing user sessions, rate-limit counters, and cached API responses. No authentication configured; accessible from app VPC subnet.',
    metadata: { service: 'elasticache', engine: 'redis-7.0', auth: 'none' },
  },
  {
    id: N.STRIPE_SERVICE,
    type: 'asset',
    label: 'Stripe Payment Service',
    description: 'Third-party payment processor handling card-not-present transactions. Connected via leaked live API key with full read/write scope.',
    metadata: { service: 'stripe', scope: 'full', mode: 'live' },
  },

  // Privileges (2)
  {
    id: N.DB_READ,
    type: 'privilege',
    label: 'Database Read Access',
    description: 'Ability to execute arbitrary SELECT queries against PostgreSQL, including users, payment_methods, and audit_logs tables containing PII and PCI data.',
    metadata: { db: 'hemisx_prod', tables: 'users, payment_methods, transactions, audit_logs' },
  },
  {
    id: N.IAM_ROLE,
    type: 'privilege',
    label: 'AWS IAM Task Role',
    description: 'ECS task role (arn:aws:iam::123456789012:role/hemisx-app-role) with s3:GetObject, s3:PutObject on customer-data bucket and ses:SendEmail.',
    metadata: { arn: 'arn:aws:iam::123456789012:role/hemisx-app-role', policies: 'S3ReadWrite, SESSend' },
  },

  // Crown jewels (2)
  {
    id: N.PG_DATABASE,
    type: 'crown_jewel',
    label: 'PostgreSQL Database (PII + PCI)',
    description: 'RDS PostgreSQL 15 containing 142,000 customer records with full names, emails, hashed passwords, and tokenized payment references. Subject to PCI-DSS and SOC2.',
    severity: 'CRITICAL',
    metadata: { service: 'rds-postgresql', records: '142000', dataTypes: 'PII, PCI', encryption: 'AES-256-at-rest' },
  },
  {
    id: N.S3_PII_BUCKET,
    type: 'crown_jewel',
    label: 'S3 Customer Data Bucket',
    description: 'S3 bucket (hemisx-customer-data-prod) storing KYC documents, signed agreements, and financial reports. 23,000+ objects containing PII.',
    severity: 'CRITICAL',
    metadata: { bucket: 'hemisx-customer-data-prod', objects: '23400', dataTypes: 'PII, PCI, CONFIDENTIAL' },
  },
]

// ─── Attack Graph Edges (18 total) ──────────────────────────────────────────
const EDGES: AttackGraphEdge[] = [
  // Kill Chain 1: SQLi → Credential Extraction → IAM Role Assumption → S3 Data Exfil
  {
    id: 'edge-01',
    source: N.LOGIN_API,
    target: N.SQLI_LOGIN,
    technique: 'Exploit Public-Facing Application',
    techniqueId: 'T1190',
    probability: 0.95,
    description: 'Attacker submits crafted SQL payload through login form email field to trigger UNION-based injection.',
    prerequisites: ['Network access to login endpoint'],
  },
  {
    id: 'edge-02',
    source: N.SQLI_LOGIN,
    target: N.DB_READ,
    technique: 'Exploitation for Credential Access',
    techniqueId: 'T1212',
    probability: 0.90,
    description: 'SQL injection grants arbitrary SELECT access, extracting password hashes and session tokens from users table.',
    prerequisites: ['Successful SQL injection'],
  },
  {
    id: 'edge-03',
    source: N.DB_READ,
    target: N.PG_DATABASE,
    technique: 'Data from Information Repositories',
    techniqueId: 'T1213',
    probability: 0.95,
    description: 'With database read access, attacker dumps full PII dataset including payment_methods and transactions tables.',
    prerequisites: ['Database read privilege'],
  },
  {
    id: 'edge-04',
    source: N.SQLI_LOGIN,
    target: N.APP_SERVER,
    technique: 'Command and Scripting Interpreter',
    techniqueId: 'T1059',
    subTechniqueId: 'T1059.007',
    probability: 0.60,
    description: 'Advanced SQLi payload leverages PostgreSQL COPY command or lo_export to write a web shell, gaining code execution on the app server.',
    prerequisites: ['SQL injection with write privilege', 'PostgreSQL superuser or COPY permission'],
  },
  {
    id: 'edge-05',
    source: N.APP_SERVER,
    target: N.IAM_ROLE,
    technique: 'Valid Accounts',
    techniqueId: 'T1078',
    subTechniqueId: 'T1078.004',
    probability: 0.85,
    description: 'App server ECS task role automatically available via instance metadata. Attacker assumes IAM role with S3 and SES permissions.',
    prerequisites: ['Code execution on ECS Fargate task'],
  },
  {
    id: 'edge-06',
    source: N.IAM_ROLE,
    target: N.S3_PII_BUCKET,
    technique: 'Data from Cloud Storage',
    techniqueId: 'T1530',
    probability: 0.90,
    description: 'Using assumed IAM role, attacker lists and downloads all objects from hemisx-customer-data-prod bucket containing KYC docs.',
    prerequisites: ['IAM role with s3:GetObject permission'],
  },
  {
    id: 'edge-07',
    source: N.S3_PII_BUCKET,
    target: N.S3_PII_BUCKET,
    technique: 'Exfiltration to Cloud Storage',
    techniqueId: 'T1567',
    subTechniqueId: 'T1567.002',
    probability: 0.80,
    description: 'Attacker copies S3 objects to an external attacker-controlled bucket using cross-account S3 replication or direct download.',
    prerequisites: ['IAM role with s3:GetObject', 'External storage destination'],
  },

  // Kill Chain 2: Hardcoded API Key → Third-Party Service Abuse → Lateral Movement
  {
    id: 'edge-08',
    source: N.PAYMENT_API,
    target: N.HARDCODED_KEY,
    technique: 'Unsecured Credentials',
    techniqueId: 'T1552',
    subTechniqueId: 'T1552.001',
    probability: 0.99,
    description: 'Stripe secret key hardcoded in source file, discoverable via code review or repository access.',
    prerequisites: ['Access to source code or deployed bundle'],
  },
  {
    id: 'edge-09',
    source: N.HARDCODED_KEY,
    target: N.STRIPE_SERVICE,
    technique: 'Steal Application Access Token',
    techniqueId: 'T1528',
    probability: 0.95,
    description: 'Using the leaked Stripe sk_live key, attacker authenticates to Stripe API with full account access.',
    prerequisites: ['Stripe secret key'],
  },
  {
    id: 'edge-10',
    source: N.STRIPE_SERVICE,
    target: N.PG_DATABASE,
    technique: 'Use Alternate Authentication Material',
    techniqueId: 'T1550',
    subTechniqueId: 'T1550.001',
    probability: 0.55,
    description: 'Stripe webhook secrets or customer metadata used to correlate and enrich data stolen from the database, linking payment info to PII.',
    prerequisites: ['Stripe API access', 'Database read access'],
  },
  {
    id: 'edge-11',
    source: N.HARDCODED_KEY,
    target: N.APP_SERVER,
    technique: 'Exploitation of Remote Services',
    techniqueId: 'T1210',
    probability: 0.40,
    description: 'Attacker uses exposed Stripe webhook endpoint to send crafted webhook payloads, potentially triggering server-side logic abuse.',
    prerequisites: ['Stripe secret key', 'Knowledge of webhook handler logic'],
  },
  {
    id: 'edge-12',
    source: N.APP_SERVER,
    target: N.REDIS_CACHE,
    technique: 'Remote Services',
    techniqueId: 'T1021',
    probability: 0.85,
    description: 'From the app server, attacker connects to unauthenticated Redis instance to dump session tokens and hijack active user sessions.',
    prerequisites: ['Code execution on app server', 'Network access to Redis'],
  },

  // Kill Chain 3: Path Traversal → Config File Read → Database Credential Theft
  {
    id: 'edge-13',
    source: N.FILE_UPLOAD,
    target: N.PATH_TRAVERSAL,
    technique: 'Exploit Public-Facing Application',
    techniqueId: 'T1190',
    probability: 0.85,
    description: 'Attacker submits filename with ../../ sequences to traverse directory and read arbitrary files from the server filesystem.',
    prerequisites: ['Network access to upload endpoint'],
  },
  {
    id: 'edge-14',
    source: N.PATH_TRAVERSAL,
    target: N.APP_SERVER,
    technique: 'Data from Local System',
    techniqueId: 'T1005',
    probability: 0.80,
    description: 'Path traversal reads /app/.env containing DATABASE_URL, REDIS_URL, JWT_SECRET, and AWS credentials.',
    prerequisites: ['Successful path traversal'],
  },
  {
    id: 'edge-15',
    source: N.APP_SERVER,
    target: N.DB_READ,
    technique: 'Unsecured Credentials',
    techniqueId: 'T1552',
    subTechniqueId: 'T1552.001',
    probability: 0.90,
    description: 'DATABASE_URL from .env file contains PostgreSQL connection string with username and password, granting direct database access.',
    prerequisites: ['Access to .env file contents'],
  },

  // Cross-chain lateral edges
  {
    id: 'edge-16',
    source: N.SSRF_INTERNAL,
    target: N.REDIS_CACHE,
    technique: 'Exploitation of Remote Services',
    techniqueId: 'T1210',
    probability: 0.70,
    description: 'SSRF vulnerability allows attacker to reach internal Redis on port 6379, executing commands via RESP protocol over HTTP.',
    prerequisites: ['SSRF to internal network'],
  },
  {
    id: 'edge-17',
    source: N.SSRF_INTERNAL,
    target: N.IAM_ROLE,
    technique: 'Cloud Instance Metadata API',
    techniqueId: 'T1552',
    subTechniqueId: 'T1552.005',
    probability: 0.75,
    description: 'SSRF to 169.254.169.254 metadata endpoint retrieves temporary IAM credentials for the ECS task role.',
    prerequisites: ['SSRF to metadata service', 'IMDSv1 enabled or token leakable'],
  },
  {
    id: 'edge-18',
    source: N.WEAK_JWT,
    target: N.APP_SERVER,
    technique: 'Forge Web Credentials',
    techniqueId: 'T1606',
    subTechniqueId: 'T1606.001',
    probability: 0.80,
    description: 'Brute-forcing the weak JWT secret allows forging admin tokens, granting full application access including admin-only endpoints.',
    prerequisites: ['Knowledge of JWT algorithm (HS256)', 'Brute-force capability'],
  },
]

// ─── Attack Graph ───────────────────────────────────────────────────────────
export const MOCK_ATTACK_GRAPH: AttackGraph = {
  id: 'ag-wbrt-001',
  engagementId: 'wbrt-eng-001',
  nodes: NODES,
  edges: EDGES,
  entryPoints: [N.LOGIN_API, N.PAYMENT_API, N.FILE_UPLOAD],
  crownJewels: [N.PG_DATABASE, N.S3_PII_BUCKET],
  generatedAt: '2026-03-18T11:42:00Z',
}

// ─── Kill Chains (3) ────────────────────────────────────────────────────────
export const MOCK_KILL_CHAINS: KillChain[] = [
  // Kill Chain 1: CRITICAL — SQLi → Credential Extraction → IAM Role Assumption → S3 Data Exfil
  {
    id: 'kc-001',
    engagementId: 'wbrt-eng-001',
    name: 'SQLi → Credential Extraction → IAM Role Assumption → S3 Data Exfil',
    narrative: 'An unauthenticated attacker exploits a SQL injection vulnerability in the login API to extract database credentials and session tokens. By leveraging PostgreSQL COPY functionality, they achieve code execution on the application server, inheriting the ECS task IAM role. This role grants read/write access to the S3 customer data bucket containing 23,400 KYC documents and PII records. The full attack chain — from initial injection to data exfiltration — can be completed in under 4 hours with standard tooling, resulting in a reportable data breach affecting 142,000 customers and triggering PCI-DSS and SOC2 incident response obligations.',
    likelihood: 'VERY_HIGH',
    impact: 'CRITICAL',
    steps: [
      {
        seq: 1,
        tactic: 'Initial Access',
        tacticId: 'TA0001',
        technique: 'Exploit Public-Facing Application',
        techniqueId: 'T1190',
        action: 'Attacker sends a UNION-based SQL injection payload through the login form email field: \' UNION SELECT username, password_hash FROM users--',
        target: 'Login API (/api/auth/login)',
        result: 'SUCCESS',
        evidence: 'SAST finding SAST-001: Unsanitized input concatenated into SQL query at src/lib/services/auth.ts:31',
        nodeIds: [N.LOGIN_API, N.SQLI_LOGIN],
      },
      {
        seq: 2,
        tactic: 'Credential Access',
        tacticId: 'TA0006',
        technique: 'Exploitation for Credential Access',
        techniqueId: 'T1212',
        action: 'Attacker extracts all rows from users and payment_methods tables via iterative UNION SELECT queries, obtaining 142,000 password hashes and tokenized payment references.',
        target: 'PostgreSQL Database',
        result: 'SUCCESS',
        evidence: 'Database user has SELECT on all application tables; no row-level security enforced',
        nodeIds: [N.SQLI_LOGIN, N.DB_READ],
      },
      {
        seq: 3,
        tactic: 'Execution',
        tacticId: 'TA0002',
        technique: 'Command and Scripting Interpreter',
        techniqueId: 'T1059',
        subTechnique: 'JavaScript',
        subTechniqueId: 'T1059.007',
        action: 'Attacker uses PostgreSQL COPY to write a Node.js reverse shell to the filesystem, achieving code execution within the ECS Fargate container.',
        target: 'Next.js Application Server',
        result: 'SUCCESS',
        evidence: 'PostgreSQL role has FILE privilege; container runs as non-root but writable /tmp',
        nodeIds: [N.SQLI_LOGIN, N.APP_SERVER],
      },
      {
        seq: 4,
        tactic: 'Privilege Escalation',
        tacticId: 'TA0004',
        technique: 'Valid Accounts',
        techniqueId: 'T1078',
        subTechnique: 'Cloud Accounts',
        subTechniqueId: 'T1078.004',
        action: 'Attacker queries the ECS container metadata endpoint to retrieve temporary AWS credentials for the attached IAM task role (hemisx-app-role).',
        target: 'AWS IAM Task Role',
        result: 'SUCCESS',
        evidence: 'ECS task role attached via taskRoleArn in task definition; credentials auto-rotated but valid for 6 hours',
        nodeIds: [N.APP_SERVER, N.IAM_ROLE],
      },
      {
        seq: 5,
        tactic: 'Collection',
        tacticId: 'TA0009',
        technique: 'Data from Cloud Storage',
        techniqueId: 'T1530',
        action: 'Attacker uses assumed IAM credentials to list and download all 23,400 objects from the hemisx-customer-data-prod S3 bucket.',
        target: 'S3 Customer Data Bucket',
        result: 'SUCCESS',
        evidence: 'IAM policy grants s3:GetObject and s3:ListBucket on hemisx-customer-data-prod/*',
        nodeIds: [N.IAM_ROLE, N.S3_PII_BUCKET],
      },
      {
        seq: 6,
        tactic: 'Exfiltration',
        tacticId: 'TA0010',
        technique: 'Exfiltration Over Web Service',
        techniqueId: 'T1567',
        subTechnique: 'Exfiltration to Cloud Storage',
        subTechniqueId: 'T1567.002',
        action: 'Attacker streams S3 objects to an external attacker-controlled bucket via aws s3 cp with --recursive flag, exfiltrating all KYC documents.',
        target: 'External attacker infrastructure',
        result: 'SUCCESS',
        evidence: 'No S3 VPC endpoint policy restricting destination; no CloudTrail alert on bulk GetObject',
        nodeIds: [N.S3_PII_BUCKET],
      },
    ],
    mitreMapping: [
      { tacticId: 'TA0001', tacticName: 'Initial Access', techniqueId: 'T1190', techniqueName: 'Exploit Public-Facing Application', confidence: 98, evidence: 'Direct SQL injection in public login endpoint confirmed by SAST' },
      { tacticId: 'TA0006', tacticName: 'Credential Access', techniqueId: 'T1212', techniqueName: 'Exploitation for Credential Access', confidence: 95, evidence: 'SQLi grants full SELECT on credentials tables' },
      { tacticId: 'TA0002', tacticName: 'Execution', techniqueId: 'T1059', techniqueName: 'Command and Scripting Interpreter', subTechniqueId: 'T1059.007', subTechniqueName: 'JavaScript', confidence: 60, evidence: 'PostgreSQL COPY to filesystem requires FILE privilege' },
      { tacticId: 'TA0004', tacticName: 'Privilege Escalation', techniqueId: 'T1078', techniqueName: 'Valid Accounts', subTechniqueId: 'T1078.004', subTechniqueName: 'Cloud Accounts', confidence: 85, evidence: 'ECS task role metadata endpoint accessible from container' },
      { tacticId: 'TA0009', tacticName: 'Collection', techniqueId: 'T1530', techniqueName: 'Data from Cloud Storage', confidence: 92, evidence: 'IAM policy permits s3:GetObject on customer data bucket' },
      { tacticId: 'TA0010', tacticName: 'Exfiltration', techniqueId: 'T1567', techniqueName: 'Exfiltration Over Web Service', subTechniqueId: 'T1567.002', subTechniqueName: 'Exfiltration to Cloud Storage', confidence: 80, evidence: 'No egress controls on S3 API calls' },
    ],
    affectedAssets: ['Login API', 'PostgreSQL Database', 'Application Server', 'AWS IAM Role', 'S3 Customer Data Bucket'],
    estimatedTimeToExploit: '2-4 hours',
    detectionDifficulty: 'DIFFICULT',
  },

  // Kill Chain 2: HIGH — Hardcoded API Key → Third-Party Service Abuse → Lateral Movement
  {
    id: 'kc-002',
    engagementId: 'wbrt-eng-001',
    name: 'Hardcoded API Key → Third-Party Service Abuse → Lateral Movement',
    narrative: 'A Stripe live secret key committed in plaintext within the payments service module is accessible to anyone with repository access or who can read the deployed JavaScript bundle. Using this key, an attacker gains full control of the Stripe account — able to issue refunds, access customer payment data, and read webhook signing secrets. The webhook secret enables crafting authenticated payloads to the application webhook handler, which processes events without additional authorization checks. Combined with access to the unauthenticated Redis session store from the app server, the attacker can hijack active user sessions and escalate to admin access.',
    likelihood: 'HIGH',
    impact: 'HIGH',
    steps: [
      {
        seq: 1,
        tactic: 'Credential Access',
        tacticId: 'TA0006',
        technique: 'Unsecured Credentials',
        techniqueId: 'T1552',
        subTechnique: 'Credentials In Files',
        subTechniqueId: 'T1552.001',
        action: 'Attacker discovers Stripe sk_live_* key hardcoded at src/lib/services/payments.ts:8 via repository access or source map analysis.',
        target: 'Source code / deployed bundle',
        result: 'SUCCESS',
        evidence: 'SAST finding SAST-005: Hardcoded secret detected in payments.ts',
        nodeIds: [N.PAYMENT_API, N.HARDCODED_KEY],
      },
      {
        seq: 2,
        tactic: 'Credential Access',
        tacticId: 'TA0006',
        technique: 'Steal Application Access Token',
        techniqueId: 'T1528',
        action: 'Attacker authenticates to Stripe API using the leaked secret key, gaining full account access: customer data, refunds, balance, and webhook endpoints.',
        target: 'Stripe Payment Service',
        result: 'SUCCESS',
        evidence: 'Stripe key has unrestricted scope (no restricted key permissions configured)',
        nodeIds: [N.HARDCODED_KEY, N.STRIPE_SERVICE],
      },
      {
        seq: 3,
        tactic: 'Lateral Movement',
        tacticId: 'TA0008',
        technique: 'Exploitation of Remote Services',
        techniqueId: 'T1210',
        action: 'Attacker crafts authenticated Stripe webhook events to trigger server-side processing logic, probing for SSRF or command injection in webhook handlers.',
        target: 'Next.js Application Server',
        result: 'PARTIAL',
        evidence: 'Webhook handler at /api/webhooks/stripe processes events with minimal validation',
        nodeIds: [N.HARDCODED_KEY, N.APP_SERVER],
      },
      {
        seq: 4,
        tactic: 'Lateral Movement',
        tacticId: 'TA0008',
        technique: 'Remote Services',
        techniqueId: 'T1021',
        action: 'From the application context, attacker connects to the unauthenticated Redis instance and dumps all session keys to hijack active admin sessions.',
        target: 'Redis Session Store',
        result: 'SUCCESS',
        evidence: 'Redis accessible on default port 6379 without AUTH; session tokens stored in plaintext',
        nodeIds: [N.APP_SERVER, N.REDIS_CACHE],
      },
    ],
    mitreMapping: [
      { tacticId: 'TA0006', tacticName: 'Credential Access', techniqueId: 'T1552', techniqueName: 'Unsecured Credentials', subTechniqueId: 'T1552.001', subTechniqueName: 'Credentials In Files', confidence: 99, evidence: 'Stripe key visible in plaintext in source code' },
      { tacticId: 'TA0006', tacticName: 'Credential Access', techniqueId: 'T1528', techniqueName: 'Steal Application Access Token', confidence: 95, evidence: 'Live Stripe key with full permissions' },
      { tacticId: 'TA0008', tacticName: 'Lateral Movement', techniqueId: 'T1210', techniqueName: 'Exploitation of Remote Services', confidence: 45, evidence: 'Webhook handler processes events but input validation limits exploitation' },
      { tacticId: 'TA0008', tacticName: 'Lateral Movement', techniqueId: 'T1021', techniqueName: 'Remote Services', confidence: 85, evidence: 'Redis has no authentication; network accessible from app subnet' },
    ],
    affectedAssets: ['Payment API', 'Stripe Account', 'Application Server', 'Redis Session Store'],
    estimatedTimeToExploit: '1-2 hours',
    detectionDifficulty: 'MODERATE',
  },

  // Kill Chain 3: HIGH — Path Traversal → Config File Read → Database Credential Theft
  {
    id: 'kc-003',
    engagementId: 'wbrt-eng-001',
    name: 'Path Traversal → Config File Read → Database Credential Theft',
    narrative: 'The document upload endpoint allows directory traversal via unsanitized filenames. An attacker exploits this to read the .env file from the application root, which contains the full PostgreSQL connection string (including host, username, and password), Redis URL, JWT signing secret, and AWS credentials. With the database password, the attacker connects directly to PostgreSQL and extracts the full customer dataset. The leaked JWT secret also enables forging admin tokens for persistent application-level access. This chain requires no authentication and can be completed in under 30 minutes.',
    likelihood: 'HIGH',
    impact: 'HIGH',
    steps: [
      {
        seq: 1,
        tactic: 'Initial Access',
        tacticId: 'TA0001',
        technique: 'Exploit Public-Facing Application',
        techniqueId: 'T1190',
        action: 'Attacker sends a GET request to /api/documents/upload?filename=../../../../.env, exploiting path traversal in the file retrieval logic.',
        target: 'File Upload API (/api/documents/upload)',
        result: 'SUCCESS',
        evidence: 'SAST finding SAST-003: Path traversal in upload handler at src/app/api/documents/upload/route.ts:56',
        nodeIds: [N.FILE_UPLOAD, N.PATH_TRAVERSAL],
      },
      {
        seq: 2,
        tactic: 'Collection',
        tacticId: 'TA0009',
        technique: 'Data from Local System',
        techniqueId: 'T1005',
        action: 'Server responds with the contents of .env file, revealing DATABASE_URL, REDIS_URL, JWT_SECRET, and AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY.',
        target: 'Application server filesystem',
        result: 'SUCCESS',
        evidence: 'No file access restrictions; .env in application root with all secrets',
        nodeIds: [N.PATH_TRAVERSAL, N.APP_SERVER],
      },
      {
        seq: 3,
        tactic: 'Credential Access',
        tacticId: 'TA0006',
        technique: 'Unsecured Credentials',
        techniqueId: 'T1552',
        subTechnique: 'Credentials In Files',
        subTechniqueId: 'T1552.001',
        action: 'Attacker parses DATABASE_URL from .env to extract PostgreSQL credentials: postgres://app_user:P@ssw0rd_Pr0d@hemisx-db.cluster-xyz.us-east-1.rds.amazonaws.com:5432/hemisx_prod',
        target: 'PostgreSQL credentials',
        result: 'SUCCESS',
        evidence: 'DATABASE_URL contains plaintext credentials; no IAM database authentication configured',
        nodeIds: [N.APP_SERVER, N.DB_READ],
      },
      {
        seq: 4,
        tactic: 'Collection',
        tacticId: 'TA0009',
        technique: 'Data from Information Repositories',
        techniqueId: 'T1213',
        action: 'Attacker connects directly to PostgreSQL using extracted credentials and dumps all tables: users (142K rows), payment_methods (89K rows), transactions (1.2M rows).',
        target: 'PostgreSQL Database',
        result: 'SUCCESS',
        evidence: 'RDS security group allows connections from 0.0.0.0/0 on port 5432 (misconfigured)',
        nodeIds: [N.DB_READ, N.PG_DATABASE],
      },
    ],
    mitreMapping: [
      { tacticId: 'TA0001', tacticName: 'Initial Access', techniqueId: 'T1190', techniqueName: 'Exploit Public-Facing Application', confidence: 88, evidence: 'Path traversal in public upload endpoint confirmed by SAST' },
      { tacticId: 'TA0009', tacticName: 'Collection', techniqueId: 'T1005', techniqueName: 'Data from Local System', confidence: 82, evidence: '.env file readable via traversal' },
      { tacticId: 'TA0006', tacticName: 'Credential Access', techniqueId: 'T1552', techniqueName: 'Unsecured Credentials', subTechniqueId: 'T1552.001', subTechniqueName: 'Credentials In Files', confidence: 90, evidence: 'DATABASE_URL with plaintext password in .env' },
      { tacticId: 'TA0009', tacticName: 'Collection', techniqueId: 'T1213', techniqueName: 'Data from Information Repositories', confidence: 85, evidence: 'Direct database access via extracted credentials' },
    ],
    affectedAssets: ['File Upload API', 'Application Server', 'PostgreSQL Database'],
    estimatedTimeToExploit: '15-30 minutes',
    detectionDifficulty: 'DIFFICULT',
  },
]

// ─── Chained Findings (8) ───────────────────────────────────────────────────
export const MOCK_WBRT_FINDINGS: WbrtFinding[] = [
  {
    id: 'wbrt-f-001',
    engagementId: 'wbrt-eng-001',
    name: 'SQL Injection → Full Database Compromise',
    attackPathNodeIds: [N.LOGIN_API, N.SQLI_LOGIN, N.DB_READ, N.PG_DATABASE],
    attackPathDescription: 'Unauthenticated SQL injection in login API enables full database extraction including 142K customer records with PII and tokenized payment data.',
    sourceFindingIds: ['sast-finding-001'],
    severity: 'CRITICAL',
    businessImpact: {
      score: 95,
      financialEstimate: '$2.8M - $6.5M',
      dataRecordsAtRisk: 142000,
      dataTypes: ['PII', 'PCI'],
      complianceFrameworksAffected: ['PCI_DSS', 'SOC2', 'GDPR'],
      reputationalScore: 92,
      operationalImpact: '72hr incident response, mandatory customer notification within 72hrs per GDPR',
      legalExposure: 'Class-action risk from 142K affected customers; PCI-DSS Level 1 re-certification required; potential GDPR fines up to 4% annual revenue',
    },
    killChainId: 'kc-001',
    mitreMapping: [
      { tacticId: 'TA0001', tacticName: 'Initial Access', techniqueId: 'T1190', techniqueName: 'Exploit Public-Facing Application', confidence: 98, evidence: 'UNION-based SQLi confirmed in login endpoint' },
      { tacticId: 'TA0006', tacticName: 'Credential Access', techniqueId: 'T1212', techniqueName: 'Exploitation for Credential Access', confidence: 95, evidence: 'SELECT on all tables via injected query' },
    ],
    remediationPriority: 1,
    remediationSteps: [
      'Replace string concatenation with parameterized queries using Prisma ORM or pg-parameterize',
      'Implement input validation with zod schema for email field',
      'Add WAF rule to block common SQLi patterns on /api/auth/* endpoints',
      'Enable PostgreSQL row-level security to limit query scope per application role',
    ],
    status: 'OPEN',
  },
  {
    id: 'wbrt-f-002',
    engagementId: 'wbrt-eng-001',
    name: 'SQLi → Server Execution → IAM Role → S3 Exfiltration',
    attackPathNodeIds: [N.LOGIN_API, N.SQLI_LOGIN, N.APP_SERVER, N.IAM_ROLE, N.S3_PII_BUCKET],
    attackPathDescription: 'SQL injection escalates to code execution on the app server via PostgreSQL COPY, then assumes IAM role to exfiltrate 23K KYC documents from S3.',
    sourceFindingIds: ['sast-finding-001'],
    severity: 'CRITICAL',
    businessImpact: {
      score: 92,
      financialEstimate: '$3.5M - $8.2M',
      dataRecordsAtRisk: 23400,
      dataTypes: ['PII', 'CONFIDENTIAL'],
      complianceFrameworksAffected: ['PCI_DSS', 'SOC2', 'GDPR'],
      reputationalScore: 95,
      operationalImpact: 'Full service shutdown for forensic investigation; 1-2 week recovery',
      legalExposure: 'KYC document breach triggers financial regulator notification; potential license revocation',
    },
    killChainId: 'kc-001',
    mitreMapping: [
      { tacticId: 'TA0002', tacticName: 'Execution', techniqueId: 'T1059', techniqueName: 'Command and Scripting Interpreter', subTechniqueId: 'T1059.007', subTechniqueName: 'JavaScript', confidence: 60, evidence: 'PostgreSQL COPY + FILE privilege enables filesystem write' },
      { tacticId: 'TA0004', tacticName: 'Privilege Escalation', techniqueId: 'T1078', techniqueName: 'Valid Accounts', subTechniqueId: 'T1078.004', subTechniqueName: 'Cloud Accounts', confidence: 85, evidence: 'ECS task role auto-available via metadata' },
      { tacticId: 'TA0010', tacticName: 'Exfiltration', techniqueId: 'T1567', techniqueName: 'Exfiltration Over Web Service', subTechniqueId: 'T1567.002', subTechniqueName: 'Exfiltration to Cloud Storage', confidence: 80, evidence: 'No egress policy on S3 API calls' },
    ],
    remediationPriority: 2,
    remediationSteps: [
      'Fix SQL injection (see finding wbrt-f-001)',
      'Remove FILE privilege from PostgreSQL application role',
      'Scope IAM task role to minimum required S3 paths with resource-level conditions',
      'Enable S3 VPC endpoint with restrictive policy blocking cross-account copies',
      'Enable CloudTrail data events on S3 bucket with alerting on bulk GetObject',
    ],
    status: 'OPEN',
  },
  {
    id: 'wbrt-f-003',
    engagementId: 'wbrt-eng-001',
    name: 'Hardcoded Stripe Key → Payment Data Exposure',
    attackPathNodeIds: [N.PAYMENT_API, N.HARDCODED_KEY, N.STRIPE_SERVICE],
    attackPathDescription: 'Plaintext Stripe live secret key in source code grants full access to payment processing, customer data, and refund capabilities.',
    sourceFindingIds: ['sast-finding-005'],
    severity: 'CRITICAL',
    businessImpact: {
      score: 88,
      financialEstimate: '$800K - $2.1M',
      dataRecordsAtRisk: 89000,
      dataTypes: ['PCI', 'PII'],
      complianceFrameworksAffected: ['PCI_DSS', 'SOC2'],
      reputationalScore: 85,
      operationalImpact: 'Immediate Stripe account suspension; 24-48hr payment processing outage',
      legalExposure: 'PCI-DSS Requirement 3.4 violation; mandatory forensic investigation by QSA',
    },
    killChainId: 'kc-002',
    mitreMapping: [
      { tacticId: 'TA0006', tacticName: 'Credential Access', techniqueId: 'T1552', techniqueName: 'Unsecured Credentials', subTechniqueId: 'T1552.001', subTechniqueName: 'Credentials In Files', confidence: 99, evidence: 'sk_live key in plaintext in source code' },
      { tacticId: 'TA0006', tacticName: 'Credential Access', techniqueId: 'T1528', techniqueName: 'Steal Application Access Token', confidence: 95, evidence: 'Full-scope Stripe API access' },
    ],
    remediationPriority: 3,
    remediationSteps: [
      'Rotate the Stripe secret key immediately via Stripe dashboard',
      'Move key to environment variable and reference via process.env.STRIPE_SECRET_KEY',
      'Configure Stripe restricted keys with minimum required permissions',
      'Add pre-commit hook with gitleaks or trufflehog to prevent future secret commits',
      'Audit git history for other committed secrets using git-secrets scan',
    ],
    status: 'OPEN',
  },
  {
    id: 'wbrt-f-004',
    engagementId: 'wbrt-eng-001',
    name: 'Stripe Key → Webhook Abuse → Session Hijacking',
    attackPathNodeIds: [N.HARDCODED_KEY, N.APP_SERVER, N.REDIS_CACHE],
    attackPathDescription: 'Leaked Stripe key enables crafted webhook events that exploit server-side processing, combined with unauthenticated Redis access for session hijacking.',
    sourceFindingIds: ['sast-finding-005', 'sast-finding-007'],
    severity: 'HIGH',
    businessImpact: {
      score: 72,
      financialEstimate: '$400K - $1.2M',
      dataRecordsAtRisk: 5200,
      dataTypes: ['PII', 'INTERNAL'],
      complianceFrameworksAffected: ['SOC2'],
      reputationalScore: 68,
      operationalImpact: 'Active session compromise; all logged-in users potentially affected',
      legalExposure: 'SOC2 CC6.1 control failure; incident disclosure to auditor required',
    },
    killChainId: 'kc-002',
    mitreMapping: [
      { tacticId: 'TA0008', tacticName: 'Lateral Movement', techniqueId: 'T1210', techniqueName: 'Exploitation of Remote Services', confidence: 45, evidence: 'Webhook handler has limited validation' },
      { tacticId: 'TA0008', tacticName: 'Lateral Movement', techniqueId: 'T1021', techniqueName: 'Remote Services', confidence: 85, evidence: 'Redis unauthenticated on internal network' },
    ],
    remediationPriority: 4,
    remediationSteps: [
      'Enable Redis AUTH with a strong password stored in AWS Secrets Manager',
      'Add Stripe webhook signature verification in the webhook handler',
      'Implement session token rotation on privilege changes',
      'Restrict Redis security group to only allow connections from app server ENIs',
    ],
    status: 'OPEN',
  },
  {
    id: 'wbrt-f-005',
    engagementId: 'wbrt-eng-001',
    name: 'Path Traversal → .env Leak → Database Access',
    attackPathNodeIds: [N.FILE_UPLOAD, N.PATH_TRAVERSAL, N.APP_SERVER, N.DB_READ, N.PG_DATABASE],
    attackPathDescription: 'Directory traversal in file upload reads .env containing database credentials, enabling direct PostgreSQL access and full data extraction.',
    sourceFindingIds: ['sast-finding-003'],
    severity: 'HIGH',
    businessImpact: {
      score: 78,
      financialEstimate: '$1.5M - $4.0M',
      dataRecordsAtRisk: 142000,
      dataTypes: ['PII', 'PCI', 'CONFIDENTIAL'],
      complianceFrameworksAffected: ['PCI_DSS', 'SOC2', 'GDPR'],
      reputationalScore: 80,
      operationalImpact: 'Database credential rotation required; potential 4hr downtime during rotation',
      legalExposure: 'Credential exposure triggers mandatory password rotation and access audit per SOC2',
    },
    killChainId: 'kc-003',
    mitreMapping: [
      { tacticId: 'TA0001', tacticName: 'Initial Access', techniqueId: 'T1190', techniqueName: 'Exploit Public-Facing Application', confidence: 88, evidence: 'Path traversal in upload handler' },
      { tacticId: 'TA0009', tacticName: 'Collection', techniqueId: 'T1005', techniqueName: 'Data from Local System', confidence: 82, evidence: '.env readable via path traversal' },
      { tacticId: 'TA0006', tacticName: 'Credential Access', techniqueId: 'T1552', techniqueName: 'Unsecured Credentials', subTechniqueId: 'T1552.001', subTechniqueName: 'Credentials In Files', confidence: 90, evidence: 'DATABASE_URL in .env with plaintext password' },
    ],
    remediationPriority: 5,
    remediationSteps: [
      'Sanitize filename input using path.basename() and reject any path separators',
      'Implement allowlist of permitted file extensions and directories',
      'Move database credentials to AWS Secrets Manager with IAM-based authentication',
      'Restrict RDS security group to only accept connections from app server VPC subnet',
    ],
    status: 'OPEN',
  },
  {
    id: 'wbrt-f-006',
    engagementId: 'wbrt-eng-001',
    name: 'SSRF → Cloud Metadata → IAM Credential Theft',
    attackPathNodeIds: [N.SSRF_INTERNAL, N.IAM_ROLE, N.S3_PII_BUCKET],
    attackPathDescription: 'Server-side request forgery reaches AWS metadata endpoint (169.254.169.254), retrieving temporary IAM credentials that grant S3 bucket access.',
    sourceFindingIds: ['sast-finding-004'],
    severity: 'HIGH',
    businessImpact: {
      score: 75,
      financialEstimate: '$1.0M - $3.0M',
      dataRecordsAtRisk: 23400,
      dataTypes: ['PII', 'CONFIDENTIAL'],
      complianceFrameworksAffected: ['PCI_DSS', 'SOC2'],
      reputationalScore: 72,
      operationalImpact: 'IAM credential rotation and full CloudTrail audit required',
      legalExposure: 'Cloud infrastructure compromise reportable under SOC2 CC7.2',
    },
    killChainId: 'kc-001',
    mitreMapping: [
      { tacticId: 'TA0006', tacticName: 'Credential Access', techniqueId: 'T1552', techniqueName: 'Unsecured Credentials', subTechniqueId: 'T1552.005', subTechniqueName: 'Cloud Instance Metadata API', confidence: 75, evidence: 'SSRF can reach 169.254.169.254; IMDSv1 still enabled' },
      { tacticId: 'TA0009', tacticName: 'Collection', techniqueId: 'T1530', techniqueName: 'Data from Cloud Storage', confidence: 90, evidence: 'IAM role permits S3 access' },
    ],
    remediationPriority: 6,
    remediationSteps: [
      'Implement URL allowlist for webhook destinations, blocking private IP ranges (RFC 1918, link-local)',
      'Enforce IMDSv2 on all ECS tasks to require session tokens for metadata access',
      'Add egress firewall rules to block 169.254.169.254 from application containers',
      'Scope IAM role to specific S3 prefixes with condition keys',
    ],
    status: 'OPEN',
  },
  {
    id: 'wbrt-f-007',
    engagementId: 'wbrt-eng-001',
    name: 'Weak JWT Secret → Admin Token Forgery',
    attackPathNodeIds: [N.WEAK_JWT, N.APP_SERVER],
    attackPathDescription: 'Static weak JWT secret ("hemisx-dev-secret") enables offline brute-force and token forgery, granting admin-level application access.',
    sourceFindingIds: ['sast-finding-006'],
    severity: 'HIGH',
    businessImpact: {
      score: 65,
      financialEstimate: '$200K - $800K',
      dataRecordsAtRisk: 142000,
      dataTypes: ['PII', 'INTERNAL'],
      complianceFrameworksAffected: ['SOC2'],
      reputationalScore: 55,
      operationalImpact: 'All existing sessions must be invalidated; JWT secret rotation required',
      legalExposure: 'Authentication bypass constitutes SOC2 CC6.1 access control failure',
    },
    killChainId: 'kc-003',
    mitreMapping: [
      { tacticId: 'TA0006', tacticName: 'Credential Access', techniqueId: 'T1606', techniqueName: 'Forge Web Credentials', subTechniqueId: 'T1606.001', subTechniqueName: 'Web Cookies', confidence: 82, evidence: 'JWT secret is a short dictionary word; brute-forceable in minutes' },
    ],
    remediationPriority: 7,
    remediationSteps: [
      'Generate a cryptographically random 256-bit secret using crypto.randomBytes(32)',
      'Store JWT secret in AWS Secrets Manager, not in source code or .env',
      'Migrate from HS256 to RS256 with asymmetric key pair for token signing',
      'Implement token expiration (15-minute access tokens, 7-day refresh tokens)',
    ],
    status: 'OPEN',
  },
  {
    id: 'wbrt-f-008',
    engagementId: 'wbrt-eng-001',
    name: 'SSRF → Redis Session Dump → Account Takeover',
    attackPathNodeIds: [N.SSRF_INTERNAL, N.REDIS_CACHE, N.APP_SERVER],
    attackPathDescription: 'SSRF vulnerability reaches internal Redis (no auth), enabling session token extraction and hijacking of any active user session including admin accounts.',
    sourceFindingIds: ['sast-finding-004', 'sast-finding-007'],
    severity: 'MEDIUM',
    businessImpact: {
      score: 45,
      financialEstimate: '$100K - $400K',
      dataRecordsAtRisk: 3200,
      dataTypes: ['PII', 'INTERNAL'],
      complianceFrameworksAffected: ['SOC2'],
      reputationalScore: 40,
      operationalImpact: 'Session invalidation and Redis credential deployment required',
      legalExposure: 'Account takeover of admin users constitutes access control breach under SOC2',
    },
    killChainId: 'kc-002',
    mitreMapping: [
      { tacticId: 'TA0008', tacticName: 'Lateral Movement', techniqueId: 'T1210', techniqueName: 'Exploitation of Remote Services', confidence: 70, evidence: 'SSRF reaches Redis on port 6379' },
      { tacticId: 'TA0006', tacticName: 'Credential Access', techniqueId: 'T1606', techniqueName: 'Forge Web Credentials', subTechniqueId: 'T1606.001', subTechniqueName: 'Web Cookies', confidence: 75, evidence: 'Session tokens in Redis readable and replayable' },
    ],
    remediationPriority: 8,
    remediationSteps: [
      'Enable Redis AUTH and TLS in-transit encryption',
      'Implement SSRF protection with URL allowlisting (block RFC 1918 ranges)',
      'Add session binding to client IP and user-agent for session tokens',
      'Deploy Redis in a dedicated subnet with security group restricting access',
    ],
    status: 'OPEN',
  },
]

// ─── Compliance Gaps ────────────────────────────────────────────────────────
const COMPLIANCE_GAPS: ComplianceGap[] = [
  {
    framework: 'PCI_DSS',
    controlId: '6.5.1',
    controlName: 'Injection Flaws',
    status: 'FAIL',
    affectedFindingIds: ['wbrt-f-001', 'wbrt-f-002'],
    remediationNote: 'SQL injection in login API allows extraction of cardholder data. Must implement parameterized queries and input validation per PCI-DSS Requirement 6.5.1.',
  },
  {
    framework: 'PCI_DSS',
    controlId: '3.4',
    controlName: 'Render PAN Unreadable',
    status: 'FAIL',
    affectedFindingIds: ['wbrt-f-003'],
    remediationNote: 'Hardcoded Stripe secret key enables access to payment data without proper access controls. Keys must be stored in a secure vault per Requirement 3.4.',
  },
  {
    framework: 'PCI_DSS',
    controlId: '6.5.8',
    controlName: 'Improper Access Control',
    status: 'FAIL',
    affectedFindingIds: ['wbrt-f-005', 'wbrt-f-007'],
    remediationNote: 'Path traversal and weak JWT allow unauthorized access to cardholder data environment. Implement proper access controls per Requirement 6.5.8.',
  },
  {
    framework: 'PCI_DSS',
    controlId: '8.2.1',
    controlName: 'Strong Cryptography for Credentials',
    status: 'PARTIAL',
    affectedFindingIds: ['wbrt-f-007'],
    remediationNote: 'JWT signing uses a weak static secret instead of cryptographically strong key material. Migrate to RS256 with managed key pair.',
  },
  {
    framework: 'SOC2',
    controlId: 'CC6.1',
    controlName: 'Logical and Physical Access Controls',
    status: 'FAIL',
    affectedFindingIds: ['wbrt-f-004', 'wbrt-f-007', 'wbrt-f-008'],
    remediationNote: 'Unauthenticated Redis, weak JWT, and session hijack paths demonstrate insufficient logical access controls. Implement defense-in-depth authentication.',
  },
  {
    framework: 'SOC2',
    controlId: 'CC6.6',
    controlName: 'System Boundary Protection',
    status: 'FAIL',
    affectedFindingIds: ['wbrt-f-006', 'wbrt-f-008'],
    remediationNote: 'SSRF allows traversal of internal network boundaries, accessing metadata services and internal datastores. Implement egress controls and network segmentation.',
  },
  {
    framework: 'SOC2',
    controlId: 'CC7.2',
    controlName: 'Security Event Monitoring',
    status: 'PARTIAL',
    affectedFindingIds: ['wbrt-f-001', 'wbrt-f-002', 'wbrt-f-006'],
    remediationNote: 'No alerting configured for bulk database reads, S3 object downloads, or metadata endpoint access. Implement CloudTrail data events and anomaly detection.',
  },
]

// ─── Remediation Roadmap ────────────────────────────────────────────────────
const REMEDIATION_ROADMAP: RemediationItem[] = [
  {
    priority: 1,
    title: 'Fix SQL Injection in Login API',
    description: 'Replace raw SQL string concatenation with Prisma ORM parameterized queries. Add zod input validation schema for the login endpoint. This single fix breaks Kill Chain 1 at the entry point and eliminates the highest-risk attack path.',
    effort: 'LOW',
    impact: 'CRITICAL',
    affectedFindingIds: ['wbrt-f-001', 'wbrt-f-002'],
    estimatedHours: 4,
  },
  {
    priority: 2,
    title: 'Rotate and Vault All Secrets',
    description: 'Immediately rotate the Stripe API key, database password, and JWT secret. Migrate all secrets to AWS Secrets Manager with IAM-based access. Add gitleaks pre-commit hook to prevent future secret commits.',
    effort: 'MEDIUM',
    impact: 'CRITICAL',
    affectedFindingIds: ['wbrt-f-003', 'wbrt-f-005', 'wbrt-f-007'],
    estimatedHours: 8,
  },
  {
    priority: 3,
    title: 'Patch Path Traversal in Upload Handler',
    description: 'Sanitize filename input using path.basename() and implement a strict allowlist of permitted directories. Add integration tests for traversal payloads.',
    effort: 'LOW',
    impact: 'HIGH',
    affectedFindingIds: ['wbrt-f-005'],
    estimatedHours: 3,
  },
  {
    priority: 4,
    title: 'Implement SSRF Protection',
    description: 'Add URL allowlisting for all server-side HTTP requests. Block private IP ranges (10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 169.254.0.0/16). Enforce IMDSv2 on all ECS tasks.',
    effort: 'MEDIUM',
    impact: 'HIGH',
    affectedFindingIds: ['wbrt-f-006', 'wbrt-f-008'],
    estimatedHours: 6,
  },
  {
    priority: 5,
    title: 'Harden Redis with Authentication and Network Isolation',
    description: 'Enable Redis AUTH with a strong password from Secrets Manager. Enable TLS in-transit. Restrict ElastiCache security group to app server ENIs only.',
    effort: 'MEDIUM',
    impact: 'HIGH',
    affectedFindingIds: ['wbrt-f-004', 'wbrt-f-008'],
    estimatedHours: 5,
  },
  {
    priority: 6,
    title: 'Tighten IAM Policies and Enable Monitoring',
    description: 'Scope ECS task role to minimum required S3 paths. Enable CloudTrail data events on S3 and RDS. Set up CloudWatch alerts for anomalous GetObject volume and metadata endpoint access.',
    effort: 'HIGH',
    impact: 'HIGH',
    affectedFindingIds: ['wbrt-f-002', 'wbrt-f-006'],
    estimatedHours: 12,
  },
  {
    priority: 7,
    title: 'Migrate JWT to Asymmetric Signing (RS256)',
    description: 'Replace HS256 symmetric JWT signing with RS256 asymmetric key pair. Store private key in AWS Secrets Manager. Implement 15-minute access token expiration with refresh token rotation.',
    effort: 'MEDIUM',
    impact: 'MEDIUM',
    affectedFindingIds: ['wbrt-f-007'],
    estimatedHours: 8,
  },
]

// ─── Executive Report ───────────────────────────────────────────────────────
export const MOCK_WBRT_REPORT: WbrtReport = {
  id: 'report-wbrt-001',
  engagementId: 'wbrt-eng-001',
  executiveSummary: `## White Box Red Team Assessment — Executive Summary

**Target:** HemisX Fintech SaaS Platform (Next.js + PostgreSQL + Redis on AWS)
**Assessment Date:** March 15-18, 2026
**Overall Risk:** CRITICAL (78/100)

---

### Key Findings

This white box red team assessment identified **3 critical attack chains** that, if exploited, would result in a **full data breach affecting 142,000 customer records** containing PII and PCI-scoped data.

The most severe chain begins with a **SQL injection vulnerability in the login API** — requiring no authentication — and escalates through database credential extraction, application server compromise, AWS IAM role assumption, and ultimately S3 data exfiltration. An attacker can execute this full chain in **under 4 hours** with standard tooling.

### Attack Surface Summary

| Metric | Value |
|--------|-------|
| Total Attack Paths | 18 |
| Kill Chains Identified | 3 |
| Critical Findings | 3 |
| High Findings | 4 |
| Medium Findings | 1 |
| Crown Jewels at Risk | PostgreSQL (142K records), S3 Bucket (23K documents) |

### Compliance Impact

- **PCI-DSS:** 3 control failures (6.5.1, 3.4, 6.5.8) — **not audit-ready**
- **SOC2:** 3 control failures (CC6.1, CC6.6, CC7.2) — **significant gaps**
- The SQL injection and path traversal vulnerabilities alone would result in **automatic PCI-DSS audit failure**

### Estimated Financial Exposure

If the primary kill chain (SQLi → S3 Exfil) is exploited:
- **Direct costs:** $2.8M - $6.5M (breach notification, forensics, legal)
- **Regulatory fines:** Up to 4% annual revenue (GDPR) + PCI-DSS penalties
- **Business impact:** 1-2 week service disruption, customer churn estimated at 15-25%

### Remediation Priority

The top 3 remediations (SQL injection fix, secret rotation, path traversal patch) can be completed in **under 15 engineering hours** and would eliminate 70% of the identified risk. We recommend treating these as P0 items with a 48-hour fix window.

See the full remediation roadmap for the prioritized 7-step action plan.`,
  overallRiskScore: 78,
  riskLevel: 'CRITICAL',
  attackPathCount: 18,
  killChainCount: 3,
  topFindings: MOCK_WBRT_FINDINGS.slice(0, 5),
  complianceGaps: COMPLIANCE_GAPS,
  remediationRoadmap: REMEDIATION_ROADMAP,
  generatedAt: '2026-03-18T12:15:00Z',
}

// ─── Full Engagement ────────────────────────────────────────────────────────
export const MOCK_WBRT_ENGAGEMENT: WbrtEngagement = {
  id: 'wbrt-eng-001',
  orgId: 'org-demo',
  name: 'HemisX Fintech Platform — Full WBRT Assessment',
  inputSource: 'sast_import',
  status: 'COMPLETED',
  progress: 100,
  currentPhase: 'complete',
  architectureContext: {
    techStack: ['Next.js 15', 'React 19', 'TypeScript', 'PostgreSQL 15', 'Redis 7', 'Prisma', 'Stripe SDK'],
    deployment: 'cloud',
    cloudProviders: ['AWS'],
    networkSegments: [
      {
        name: 'Public Subnet (DMZ)',
        cidr: '10.0.1.0/24',
        services: ['ALB', 'CloudFront', 'WAF'],
        exposure: 'public',
      },
      {
        name: 'Application Tier',
        cidr: '10.0.10.0/24',
        services: ['ECS Fargate (Next.js)', 'Lambda (async jobs)'],
        exposure: 'internal',
      },
      {
        name: 'Data Tier',
        cidr: '10.0.20.0/24',
        services: ['RDS PostgreSQL', 'ElastiCache Redis', 'S3 VPC Endpoint'],
        exposure: 'restricted',
      },
    ],
    authMechanisms: ['JWT (HS256)', 'API Keys', 'Stripe Webhooks'],
    dataClassifications: ['PII', 'PCI', 'CONFIDENTIAL', 'INTERNAL'],
    complianceRequirements: ['PCI_DSS', 'SOC2', 'GDPR'],
    externalIntegrations: ['Stripe', 'SendGrid', 'Datadog', 'Sentry'],
    userCount: '1K-10K',
    description: 'Fintech SaaS platform serving SMBs with payment processing, invoicing, and financial reporting. Handles PII (customer data, KYC documents) and PCI-scoped data (payment tokens). Deployed on AWS using ECS Fargate with RDS PostgreSQL and ElastiCache Redis. Public-facing Next.js app behind CloudFront + ALB.',
  },
  sastScanId: 'sast-scan-001',
  attackGraph: MOCK_ATTACK_GRAPH,
  killChains: MOCK_KILL_CHAINS,
  findings: MOCK_WBRT_FINDINGS,
  report: MOCK_WBRT_REPORT,
  summary: {
    totalAttackPaths: 18,
    totalKillChains: 3,
    criticalFindings: 3,
    highFindings: 4,
    mediumFindings: 1,
    lowFindings: 0,
    overallRiskScore: 78,
  },
  createdAt: '2026-03-15T09:00:00Z',
  startedAt: '2026-03-15T09:05:00Z',
  completedAt: '2026-03-18T12:15:00Z',
}

// ─── SAST Scans for Import Dropdown ─────────────────────────────────────────
export const MOCK_SAST_SCANS_FOR_IMPORT: { id: string; name: string; date: string; findingsCount: number }[] = [
  {
    id: 'sast-scan-001',
    name: 'Production App — Full Scan',
    date: '2026-03-14T16:30:00Z',
    findingsCount: 24,
  },
  {
    id: 'sast-scan-002',
    name: 'API Module — Targeted Scan',
    date: '2026-03-10T11:00:00Z',
    findingsCount: 9,
  },
  {
    id: 'sast-scan-003',
    name: 'Auth & Payments — Security Audit',
    date: '2026-03-07T14:45:00Z',
    findingsCount: 15,
  },
]
