// src/lib/cloud-scanner/checks/data-checks.ts
import type { CloudCheck } from '@/lib/types/cloud-scanner'

export const DATA_CHECKS: CloudCheck[] = [
  { id: 'DATA-001', category: 'DATA', title: 'S3 Bucket Publicly Readable', description: 'S3 buckets must not allow public read access.', severity: 'CRITICAL', resourceType: 'AWS::S3::Bucket', fixEffort: '5min', estimatedMinutes: 5, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 2.1.5', controlName: 'Ensure S3 buckets are not publicly accessible' }, { framework: 'PCI_DSS', controlId: 'PCI-DSS 3.4', controlName: 'Protect stored cardholder data' }] },
  { id: 'DATA-002', category: 'DATA', title: 'S3 Block Public Access Not Enabled at Account Level', description: 'Account-level Block Public Access prevents any bucket from becoming public.', severity: 'HIGH', resourceType: 'AWS::S3::AccountPublicAccessBlock', fixEffort: '5min', estimatedMinutes: 5, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 2.1.4', controlName: 'Ensure S3 Block Public Access is enabled at account level' }] },
  { id: 'DATA-003', category: 'DATA', title: 'RDS Instance Publicly Accessible', description: 'RDS instances should never be directly internet-accessible.', severity: 'CRITICAL', resourceType: 'AWS::RDS::DBInstance', fixEffort: '1hr', estimatedMinutes: 30, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 2.3.1', controlName: 'Ensure RDS instances are not publicly accessible' }, { framework: 'PCI_DSS', controlId: 'PCI-DSS 1.3', controlName: 'Prohibit direct public access to CDE' }] },
  { id: 'DATA-004', category: 'DATA', title: 'RDS Instance No Encryption at Rest', description: 'RDS storage must be encrypted to protect data at rest.', severity: 'HIGH', resourceType: 'AWS::RDS::DBInstance', fixEffort: '1day', estimatedMinutes: 240, complianceMappings: [{ framework: 'PCI_DSS', controlId: 'PCI-DSS 3.5', controlName: 'Protect encryption keys used to protect stored data' }, { framework: 'HIPAA', controlId: 'HIPAA 164.312(a)(2)(iv)', controlName: 'Encryption and decryption' }] },
  { id: 'DATA-005', category: 'DATA', title: 'EBS Volume Not Encrypted', description: 'EBS volumes containing application data must be encrypted.', severity: 'MEDIUM', resourceType: 'AWS::EC2::Volume', fixEffort: '1hr', estimatedMinutes: 60, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 2.2.1', controlName: 'Ensure EBS volume encryption is enabled by default' }] },
  { id: 'DATA-006', category: 'DATA', title: 'RDS Automated Backups Disabled', description: 'Automated backups provide recovery from data loss and ransomware.', severity: 'HIGH', resourceType: 'AWS::RDS::DBInstance', fixEffort: '5min', estimatedMinutes: 5, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 2.3.2', controlName: 'Ensure RDS automated backups are enabled' }] },
  { id: 'DATA-007', category: 'DATA', title: 'RDS Deletion Protection Disabled', description: 'Deletion protection prevents accidental or malicious database deletion.', severity: 'MEDIUM', resourceType: 'AWS::RDS::DBInstance', fixEffort: '5min', estimatedMinutes: 5, complianceMappings: [{ framework: 'SOC2', controlId: 'CC9.2', controlName: 'Risk mitigation activities' }] },
  { id: 'DATA-008', category: 'DATA', title: 'S3 Bucket Encryption Disabled', description: 'S3 server-side encryption protects data at rest.', severity: 'MEDIUM', resourceType: 'AWS::S3::Bucket', fixEffort: '5min', estimatedMinutes: 5, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 2.1.1', controlName: 'Ensure S3 Bucket Policy is set to deny HTTP requests' }] },
  { id: 'DATA-009', category: 'DATA', title: 'S3 Bucket Access Logging Disabled', description: 'Access logging records all requests made to S3 buckets.', severity: 'LOW', resourceType: 'AWS::S3::Bucket', fixEffort: '5min', estimatedMinutes: 10, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 2.1.3', controlName: 'Ensure S3 bucket logging is enabled' }] },
  { id: 'DATA-010', category: 'DATA', title: 'KMS Key Rotation Disabled', description: 'Automatic rotation of KMS keys limits the impact of key compromise.', severity: 'MEDIUM', resourceType: 'AWS::KMS::Key', fixEffort: '5min', estimatedMinutes: 5, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 3.8', controlName: 'Ensure rotation for customer created CMKs is enabled' }] },
]
