// src/lib/cloud-scanner/checks/iam-checks.ts
import type { CloudCheck } from '@/lib/types/cloud-scanner'

export const IAM_CHECKS: CloudCheck[] = [
  { id: 'IAM-001', category: 'IAM', title: 'Root Account Has Active Access Keys', description: 'Root account should never have programmatic access keys.', severity: 'CRITICAL', resourceType: 'AWS::IAM::Root', fixEffort: '5min', estimatedMinutes: 5, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 1.4', controlName: 'Ensure no root account access key exists' }, { framework: 'PCI_DSS', controlId: 'PCI-DSS 7.1', controlName: 'Limit access to system components' }] },
  { id: 'IAM-002', category: 'IAM', title: 'Root Account Has No MFA', description: 'Root account must have MFA enabled at all times.', severity: 'CRITICAL', resourceType: 'AWS::IAM::Root', fixEffort: '5min', estimatedMinutes: 5, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 1.5', controlName: 'Ensure MFA is enabled for the root account' }] },
  { id: 'IAM-003', category: 'IAM', title: 'IAM Users with Console Access and No MFA', description: 'All IAM users with console access must have MFA.', severity: 'CRITICAL', resourceType: 'AWS::IAM::User', fixEffort: '1hr', estimatedMinutes: 60, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 1.10', controlName: 'Ensure MFA is enabled for all IAM users with console access' }, { framework: 'PCI_DSS', controlId: 'PCI-DSS 8.3.1', controlName: 'MFA for non-console admin access' }] },
  { id: 'IAM-004', category: 'IAM', title: 'IAM User Has Unused Credentials (90+ days)', description: 'Credentials unused for 90+ days indicate stale accounts that should be disabled.', severity: 'HIGH', resourceType: 'AWS::IAM::User', fixEffort: '5min', estimatedMinutes: 10, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 1.12', controlName: 'Ensure credentials unused for 90+ days are disabled' }] },
  { id: 'IAM-005', category: 'IAM', title: 'CloudTrail Not Multi-Region', description: 'CloudTrail must cover all regions to prevent blind spots.', severity: 'MEDIUM', resourceType: 'AWS::CloudTrail::Trail', fixEffort: '5min', estimatedMinutes: 5, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 3.1', controlName: 'Ensure CloudTrail is enabled in all regions' }, { framework: 'SOC2', controlId: 'CC7.2', controlName: 'System monitoring' }] },
  { id: 'IAM-006', category: 'IAM', title: 'AWS Config Not Enabled', description: 'AWS Config must be enabled for compliance tracking.', severity: 'MEDIUM', resourceType: 'AWS::Config::ConfigurationRecorder', fixEffort: '1hr', estimatedMinutes: 30, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 3.5', controlName: 'Ensure AWS Config is enabled in all regions' }] },
  { id: 'IAM-007', category: 'IAM', title: 'IAM Policy with Wildcard Actions', description: 'Policies with s3:* or ec2:* grant excessive permissions.', severity: 'HIGH', resourceType: 'AWS::IAM::Policy', fixEffort: '1hr', estimatedMinutes: 45, complianceMappings: [{ framework: 'SOC2', controlId: 'CC6.3', controlName: 'Role-based access control' }] },
  { id: 'IAM-008', category: 'IAM', title: 'IAM Password Policy Insufficient', description: 'Password policy must enforce length, complexity, and rotation.', severity: 'MEDIUM', resourceType: 'AWS::IAM::PasswordPolicy', fixEffort: '5min', estimatedMinutes: 5, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 1.8', controlName: 'Ensure IAM password policy requires minimum length of 14' }] },
  { id: 'IAM-009', category: 'IAM', title: 'IAM Access Analyzer Not Enabled', description: 'Access Analyzer identifies resources shared with external entities.', severity: 'LOW', resourceType: 'AWS::AccessAnalyzer::Analyzer', fixEffort: '5min', estimatedMinutes: 5, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 1.21', controlName: 'Ensure IAM Access Analyzer is enabled' }] },
  { id: 'IAM-010', category: 'IAM', title: 'CloudTrail Log File Validation Disabled', description: 'Log file validation detects tampering with CloudTrail logs.', severity: 'LOW', resourceType: 'AWS::CloudTrail::Trail', fixEffort: '5min', estimatedMinutes: 5, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 3.2', controlName: 'Ensure CloudTrail log file validation is enabled' }] },
]
