// src/lib/cloud-scanner/checks/network-checks.ts
import type { CloudCheck } from '@/lib/types/cloud-scanner'

export const NETWORK_CHECKS: CloudCheck[] = [
  { id: 'NET-001', category: 'NETWORK', title: 'Security Group Allows SSH from 0.0.0.0/0', description: 'SSH should never be open to the entire internet.', severity: 'CRITICAL', resourceType: 'AWS::EC2::SecurityGroup', fixEffort: '5min', estimatedMinutes: 10, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 5.2', controlName: 'Ensure no security groups allow ingress from 0.0.0.0/0 to SSH' }, { framework: 'PCI_DSS', controlId: 'PCI-DSS 1.3.1', controlName: 'Restrict inbound traffic' }] },
  { id: 'NET-002', category: 'NETWORK', title: 'Security Group Allows RDP from 0.0.0.0/0', description: 'RDP should never be open to the entire internet.', severity: 'CRITICAL', resourceType: 'AWS::EC2::SecurityGroup', fixEffort: '5min', estimatedMinutes: 10, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 5.3', controlName: 'Ensure no security groups allow ingress from 0.0.0.0/0 to RDP' }] },
  { id: 'NET-003', category: 'NETWORK', title: 'Security Group Allows DB Ports from 0.0.0.0/0', description: 'Database ports (3306, 5432, 1433, 27017) should not be internet-accessible.', severity: 'CRITICAL', resourceType: 'AWS::EC2::SecurityGroup', fixEffort: '5min', estimatedMinutes: 10, complianceMappings: [{ framework: 'PCI_DSS', controlId: 'PCI-DSS 1.3.2', controlName: 'Restrict outbound traffic to only that which is necessary' }] },
  { id: 'NET-004', category: 'NETWORK', title: 'VPC Flow Logs Disabled', description: 'VPC Flow Logs capture all network traffic metadata for detection and forensics.', severity: 'HIGH', resourceType: 'AWS::EC2::VPC', fixEffort: '5min', estimatedMinutes: 10, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 3.9', controlName: 'Ensure VPC flow logging is enabled in all VPCs' }, { framework: 'SOC2', controlId: 'CC7.2', controlName: 'Monitor system components for anomalies' }] },
  { id: 'NET-005', category: 'NETWORK', title: 'EC2 Instance IMDSv1 Enabled', description: 'IMDSv1 allows SSRF attacks to steal instance credentials. Enforce IMDSv2.', severity: 'HIGH', resourceType: 'AWS::EC2::Instance', fixEffort: '5min', estimatedMinutes: 15, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 5.6', controlName: 'Ensure EC2 instances use IMDSv2' }] },
  { id: 'NET-006', category: 'NETWORK', title: 'ELB Access Logging Disabled', description: 'Load balancer access logs capture all HTTP requests for forensics.', severity: 'LOW', resourceType: 'AWS::ElasticLoadBalancingV2::LoadBalancer', fixEffort: '5min', estimatedMinutes: 10, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 3.11', controlName: 'Ensure ELB access logging is enabled' }] },
  { id: 'NET-007', category: 'NETWORK', title: 'ELB Has HTTP Listener Without HTTPS Redirect', description: 'HTTP traffic should be redirected to HTTPS to prevent eavesdropping.', severity: 'MEDIUM', resourceType: 'AWS::ElasticLoadBalancingV2::Listener', fixEffort: '5min', estimatedMinutes: 10, complianceMappings: [{ framework: 'PCI_DSS', controlId: 'PCI-DSS 4.2.1', controlName: 'Strong cryptography for data-in-transit' }] },
  { id: 'NET-008', category: 'NETWORK', title: 'Resources in Default VPC', description: 'Default VPCs have permissive settings. Resources should use custom VPCs.', severity: 'LOW', resourceType: 'AWS::EC2::VPC', fixEffort: '1day', estimatedMinutes: 480, complianceMappings: [{ framework: 'CIS', controlId: 'CIS 5.1', controlName: 'Ensure no Network ACLs allow ingress from 0.0.0.0/0 to ports 22 or 3389' }] },
  { id: 'NET-009', category: 'NETWORK', title: 'CloudFront Distribution Without WAF', description: 'WAF protects CloudFront distributions from common web exploits.', severity: 'MEDIUM', resourceType: 'AWS::CloudFront::Distribution', fixEffort: '1hr', estimatedMinutes: 60, complianceMappings: [{ framework: 'PCI_DSS', controlId: 'PCI-DSS 6.4.1', controlName: 'Deploy automated technical controls to protect against web-based attacks' }] },
  { id: 'NET-010', category: 'NETWORK', title: 'ACM Certificate Expiring Within 30 Days', description: 'Expiring certificates cause service outages and trust errors.', severity: 'HIGH', resourceType: 'AWS::CertificateManager::Certificate', fixEffort: '1hr', estimatedMinutes: 30, complianceMappings: [{ framework: 'SOC2', controlId: 'CC9.1', controlName: 'Risk assessment' }] },
]
