#!/usr/bin/env node
/**
 * HemisX SAST — PDF Report Generator (standalone)
 *
 * Runs outside Turbopack so pdfkit's __dirname-based font loading works.
 * Usage: echo '{"report":{...}}' | node scripts/generate-pdf.cjs
 * Outputs raw PDF bytes to stdout.
 */

'use strict'

const PDFDocument = require('pdfkit')

// ─── Color palette ──────────────────────────────────────────────────────────

const COLORS = {
  bg:          '#0a0d0f',
  card:        '#111519',
  border:      '#1e252e',
  textPrimary: '#e0e6ee',
  textDim:     '#5a6a7a',
  accent:      '#c792ea',
  critical:    '#ef5a5a',
  high:        '#ffa032',
  medium:      '#f2d156',
  low:         '#5ab0ff',
  pass:        '#64ffda',
  white:       '#ffffff',
  black:       '#000000',
}

const GRADE_COLORS = { A: '#64ffda', B: '#5ab0ff', C: '#f2d156', D: '#ffa032', F: '#ef5a5a' }
const SEV_COLORS   = { CRITICAL: COLORS.critical, HIGH: COLORS.high, MEDIUM: COLORS.medium, LOW: COLORS.low, INFO: COLORS.textDim }

// ─── Helpers ────────────────────────────────────────────────────────────────

function sectionHeader(doc, title) {
  const w = doc.page.width
  doc.rect(0, 0, w, 75).fill('#0d1117')
  doc.font('Helvetica').fontSize(8).fillColor(COLORS.accent)
  doc.text('HEMISX SAST', 50, 25, { width: w - 100 })
  doc.font('Helvetica-Bold').fontSize(16).fillColor(COLORS.white)
  doc.text(title, 50, 42, { width: w - 100 })
}

function sectionSubheader(doc, title, y) {
  doc.font('Helvetica-Bold').fontSize(10).fillColor(COLORS.accent)
  doc.text(title, 50, y, { width: doc.page.width - 100 })
  doc.moveTo(50, y + 16).lineTo(doc.page.width - 50, y + 16).strokeColor('#e0e0e0').lineWidth(0.5).stroke()
}

function drawFooter(doc, page, total) {
  const w = doc.page.width
  const h = doc.page.height
  doc.font('Helvetica').fontSize(7).fillColor('#999999')
  doc.text(`Page ${page} of ${total}`, 50, h - 30, { width: w - 100, align: 'center' })
  doc.text('Generated by HemisX SAST · CONFIDENTIAL', 50, h - 20, { width: w - 100, align: 'center' })
}

// ─── Page renderers ─────────────────────────────────────────────────────────

function drawCoverPage(doc, report) {
  const w = doc.page.width
  const h = doc.page.height

  doc.rect(0, 0, w, 280).fill('#0d1117')

  doc.font('Helvetica-Bold').fontSize(14).fillColor(COLORS.accent)
  doc.text('HEMISX', 50, 60, { width: w - 100 })
  doc.font('Helvetica').fontSize(9).fillColor(COLORS.textDim)
  doc.text('SECURITY ASSESSMENT PLATFORM', 50, 78, { width: w - 100 })

  doc.moveTo(50, 110).lineTo(w - 50, 110).strokeColor(COLORS.accent).lineWidth(0.5).stroke()

  doc.font('Helvetica-Bold').fontSize(28).fillColor(COLORS.white)
  doc.text('Security Assessment', 50, 135, { width: w - 100 })
  doc.text('Report', 50, 170, { width: w - 100 })

  doc.font('Helvetica').fontSize(14).fillColor(COLORS.accent)
  doc.text(report.scanInfo.scanName, 50, 215, { width: w - 100 })

  const gradeColor = GRADE_COLORS[report.riskScore.grade] || COLORS.textDim
  doc.roundedRect(w - 150, 130, 90, 90, 4).strokeColor(gradeColor).lineWidth(2).stroke()
  doc.font('Helvetica-Bold').fontSize(48).fillColor(gradeColor)
  doc.text(report.riskScore.grade, w - 150, 140, { width: 90, align: 'center' })
  doc.font('Helvetica').fontSize(10).fillColor(COLORS.textDim)
  doc.text(`${report.riskScore.overall}/100`, w - 150, 200, { width: 90, align: 'center' })

  const metaY = 320
  doc.font('Helvetica').fontSize(10).fillColor('#444444')
  const meta = [
    ['Generated',   new Date(report.generatedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })],
    ['Language',    report.scanInfo.language],
    ['Files',       String(report.scanInfo.filesScanned)],
    ['Lines',       report.scanInfo.linesOfCode.toLocaleString()],
    ['Duration',    `${report.scanInfo.duration}ms`],
    ['Scan ID',     report.scanInfo.scanId.slice(0, 8) + '...'],
  ]

  meta.forEach(([label, value], i) => {
    const y = metaY + i * 28
    doc.font('Helvetica-Bold').fontSize(9).fillColor('#666666')
    doc.text(label.toUpperCase(), 50, y, { width: 120 })
    doc.font('Helvetica').fontSize(10).fillColor('#333333')
    doc.text(value, 170, y, { width: 300 })
  })

  doc.font('Helvetica').fontSize(8).fillColor('#999999')
  doc.text(
    'CONFIDENTIAL — This report contains sensitive security assessment information. Distribution should be limited to authorized personnel only.',
    50, h - 80, { width: w - 100, align: 'center' }
  )
}

function drawExecutiveSummary(doc, report) {
  const w = doc.page.width
  sectionHeader(doc, 'EXECUTIVE SUMMARY')

  doc.font('Helvetica').fontSize(11).fillColor('#333333')
  doc.text(report.executiveSummary, 50, 110, { width: w - 100, lineGap: 4 })

  const boxY = doc.y + 30
  const severities = [
    { label: 'CRITICAL', count: 0, color: COLORS.critical },
    { label: 'HIGH',     count: 0, color: COLORS.high },
    { label: 'MEDIUM',   count: 0, color: COLORS.medium },
    { label: 'LOW',      count: 0, color: COLORS.low },
  ]

  for (const risk of report.topRisks) {
    const s = severities.find(s => s.label === risk.severity)
    if (s) s.count++
  }
  for (const item of report.remediationPlan) {
    const s = severities.find(s => s.label === item.impact)
    if (s) s.count = Math.max(s.count, item.findingCount)
  }

  const boxWidth = (w - 100 - 30) / 4
  severities.forEach((sev, i) => {
    const x = 50 + i * (boxWidth + 10)
    doc.rect(x, boxY, boxWidth, 60).fillAndStroke('#fafafa', '#e0e0e0')
    doc.font('Helvetica-Bold').fontSize(24).fillColor(sev.color)
    doc.text(String(sev.count), x, boxY + 8, { width: boxWidth, align: 'center' })
    doc.font('Helvetica').fontSize(8).fillColor('#666666')
    doc.text(sev.label, x, boxY + 40, { width: boxWidth, align: 'center' })
  })

  const tableY = boxY + 90
  sectionSubheader(doc, 'SCAN DETAILS', tableY)

  const details = [
    ['Scan Name',     report.scanInfo.scanName],
    ['Language',      report.scanInfo.language],
    ['Files Scanned', String(report.scanInfo.filesScanned)],
    ['Lines of Code', report.scanInfo.linesOfCode.toLocaleString()],
    ['Duration',      `${report.scanInfo.duration}ms`],
    ['Completed',     new Date(report.scanInfo.completedAt).toLocaleString()],
    ['Risk Grade',    `${report.riskScore.grade} (${report.riskScore.overall}/100)`],
  ]

  details.forEach(([label, value], i) => {
    const y = tableY + 25 + i * 22
    const bg = i % 2 === 0 ? '#f8f8f8' : '#ffffff'
    doc.rect(50, y, w - 100, 20).fill(bg)
    doc.font('Helvetica-Bold').fontSize(9).fillColor('#555555')
    doc.text(label, 60, y + 5, { width: 150 })
    doc.font('Helvetica').fontSize(9).fillColor('#333333')
    doc.text(value, 220, y + 5, { width: w - 280 })
  })
}

function drawRiskBreakdown(doc, report) {
  const w = doc.page.width
  sectionHeader(doc, 'RISK BREAKDOWN BY CATEGORY')

  const categories = [
    { label: 'Injection',      score: report.riskScore.breakdown.injection },
    { label: 'Cryptography',   score: report.riskScore.breakdown.cryptography },
    { label: 'Authentication', score: report.riskScore.breakdown.authentication },
    { label: 'Secrets',        score: report.riskScore.breakdown.secrets },
    { label: 'Dependencies',   score: report.riskScore.breakdown.dependencies },
    { label: 'Configuration',  score: report.riskScore.breakdown.configuration },
  ]

  const barMaxWidth = w - 250
  categories.forEach((cat, i) => {
    const y = 110 + i * 55
    const barWidth = Math.max(2, (cat.score / 100) * barMaxWidth)
    const barColor = cat.score >= 70 ? COLORS.critical : cat.score >= 40 ? COLORS.high : cat.score >= 20 ? COLORS.medium : '#64ffda'

    doc.font('Helvetica-Bold').fontSize(10).fillColor('#333333')
    doc.text(cat.label, 50, y, { width: 130 })
    doc.font('Helvetica').fontSize(9).fillColor('#666666')
    doc.text(`${cat.score}/100`, 50, y + 16, { width: 130 })

    doc.rect(190, y + 2, barMaxWidth, 16).fill('#f0f0f0')
    doc.rect(190, y + 2, barWidth, 16).fill(barColor)

    if (cat.score > 10) {
      doc.font('Helvetica-Bold').fontSize(8).fillColor('#ffffff')
      doc.text(String(cat.score), 190 + barWidth - 25, y + 5, { width: 22, align: 'right' })
    }
  })

  const gaugeY = 110 + categories.length * 55 + 40
  sectionSubheader(doc, 'OVERALL RISK ASSESSMENT', gaugeY)

  const gradeColor = GRADE_COLORS[report.riskScore.grade] || COLORS.textDim
  const centerX = w / 2
  const centerY = gaugeY + 80
  doc.circle(centerX, centerY, 40).strokeColor(gradeColor).lineWidth(3).stroke()
  doc.font('Helvetica-Bold').fontSize(36).fillColor(gradeColor)
  doc.text(report.riskScore.grade, centerX - 20, centerY - 18, { width: 40, align: 'center' })
  doc.font('Helvetica').fontSize(10).fillColor('#666666')
  doc.text(`Score: ${report.riskScore.overall}/100`, centerX - 50, centerY + 30, { width: 100, align: 'center' })
  doc.text(`Trend: ${report.riskScore.trend}`, centerX - 50, centerY + 45, { width: 100, align: 'center' })
}

function drawTopRisks(doc, report) {
  const w = doc.page.width
  sectionHeader(doc, 'TOP SECURITY RISKS')

  if (report.topRisks.length === 0) {
    doc.font('Helvetica').fontSize(11).fillColor('#666666')
    doc.text('No significant risks were identified.', 50, 110, { width: w - 100 })
    return
  }

  let y = 110
  for (const risk of report.topRisks) {
    if (y > 700) { doc.addPage(); y = 50 }

    const sevColor = SEV_COLORS[risk.severity] || COLORS.textDim

    doc.rect(50, y, w - 100, 24).fill('#f5f5f5')
    doc.font('Helvetica-Bold').fontSize(9).fillColor(sevColor)
    doc.text(`#${risk.rank}  ${risk.severity}`, 60, y + 7, { width: 100 })
    doc.font('Helvetica-Bold').fontSize(9).fillColor('#333333')
    doc.text(risk.finding, 160, y + 7, { width: w - 280 })
    doc.font('Helvetica').fontSize(8).fillColor('#888888')
    doc.text(risk.cwe, w - 120, y + 7, { width: 70, align: 'right' })
    y += 28

    doc.font('Helvetica').fontSize(9).fillColor('#555555')
    doc.text(`Category: ${risk.category}  |  Effort: ${risk.effort}`, 60, y, { width: w - 120 })
    y += 16

    doc.font('Helvetica').fontSize(9).fillColor('#444444')
    doc.text(`Impact: ${risk.impact}`, 60, y, { width: w - 120, lineGap: 2 })
    y = doc.y + 8

    doc.font('Helvetica').fontSize(9).fillColor('#2e7d32')
    doc.text(`Fix: ${risk.remediation}`, 60, y, { width: w - 120, lineGap: 2 })
    y = doc.y + 16

    doc.moveTo(50, y).lineTo(w - 50, y).strokeColor('#e0e0e0').lineWidth(0.5).stroke()
    y += 12
  }
}

function drawRemediationPlan(doc, report) {
  const w = doc.page.width
  sectionHeader(doc, 'REMEDIATION ROADMAP')

  if (report.remediationPlan.length === 0) {
    doc.font('Helvetica').fontSize(11).fillColor('#666666')
    doc.text('No remediation items identified.', 50, 110, { width: w - 100 })
    return
  }

  const cols = [
    { label: 'P',        x: 50,  w: 25 },
    { label: 'CATEGORY', x: 80,  w: 100 },
    { label: 'ACTION',   x: 185, w: 210 },
    { label: '#',        x: 400, w: 25 },
    { label: 'EFFORT',   x: 430, w: 55 },
    { label: 'IMPACT',   x: 490, w: 55 },
  ]

  let y = 110
  doc.rect(50, y, w - 100, 20).fill('#333333')
  for (const col of cols) {
    doc.font('Helvetica-Bold').fontSize(7).fillColor('#ffffff')
    doc.text(col.label, col.x + 4, y + 6, { width: col.w - 8 })
  }
  y += 22

  for (const item of report.remediationPlan) {
    if (y > 740) { doc.addPage(); y = 50 }

    const bg = item.priority === 1 ? '#fff5f5' : item.priority === 2 ? '#fff8e1' : '#f5f5f5'
    const rowH = 28
    doc.rect(50, y, w - 100, rowH).fill(bg)

    const pColor = item.priority === 1 ? COLORS.critical : item.priority === 2 ? COLORS.high : COLORS.medium
    doc.font('Helvetica-Bold').fontSize(9).fillColor(pColor)
    doc.text(`P${item.priority}`, cols[0].x + 2, y + 8, { width: cols[0].w })

    doc.font('Helvetica-Bold').fontSize(8).fillColor('#333333')
    doc.text(item.category, cols[1].x + 4, y + 8, { width: cols[1].w - 8 })

    doc.font('Helvetica').fontSize(7).fillColor('#444444')
    const actionText = item.action.length > 85 ? item.action.slice(0, 82) + '...' : item.action
    doc.text(actionText, cols[2].x + 4, y + 5, { width: cols[2].w - 8, lineGap: 1 })

    doc.font('Helvetica').fontSize(9).fillColor('#333333')
    doc.text(String(item.findingCount), cols[3].x + 4, y + 8, { width: cols[3].w })

    const effortColor = item.effort === 'LOW' ? '#2e7d32' : item.effort === 'MEDIUM' ? '#f57f17' : COLORS.critical
    doc.font('Helvetica-Bold').fontSize(7).fillColor(effortColor)
    doc.text(item.effort, cols[4].x + 4, y + 8, { width: cols[4].w })

    const impactColor = SEV_COLORS[item.impact] || COLORS.textDim
    doc.font('Helvetica-Bold').fontSize(7).fillColor(impactColor)
    doc.text(item.impact, cols[5].x + 4, y + 8, { width: cols[5].w })

    y += rowH + 2
  }
}

function drawComplianceSummary(doc, report) {
  const w = doc.page.width
  sectionHeader(doc, 'COMPLIANCE POSTURE')

  if (!report.compliance || report.compliance.length === 0) return

  let y = 110
  const cardWidth = (w - 100 - 20) / 2

  report.compliance.forEach((c, i) => {
    const col = i % 2
    const x = 50 + col * (cardWidth + 20)
    if (i > 0 && col === 0) y += 100

    const statusColor = c.status === 'PASS' ? '#e8f5e9' : c.status === 'FAIL' ? '#ffebee' : '#fff8e1'
    doc.rect(x, y, cardWidth, 85).fillAndStroke(statusColor, '#e0e0e0')

    doc.font('Helvetica-Bold').fontSize(10).fillColor('#333333')
    doc.text(c.framework, x + 12, y + 12, { width: cardWidth - 24 })

    const scoreColor = c.score >= 80 ? '#2e7d32' : c.score >= 50 ? '#f57f17' : COLORS.critical
    doc.font('Helvetica-Bold').fontSize(28).fillColor(scoreColor)
    doc.text(`${c.score}%`, x + 12, y + 32, { width: 80 })

    const badgeColor = c.status === 'PASS' ? '#2e7d32' : c.status === 'FAIL' ? COLORS.critical : '#f57f17'
    doc.font('Helvetica-Bold').fontSize(8).fillColor(badgeColor)
    doc.text(c.status, x + 100, y + 42, { width: cardWidth - 112 })

    if (c.failedControls > 0) {
      doc.font('Helvetica').fontSize(8).fillColor('#666666')
      doc.text(`${c.failedControls} controls need attention`, x + 12, y + 68, { width: cardWidth - 24 })
    }
  })
}

// ─── Main ───────────────────────────────────────────────────────────────────

function generatePdf(report) {
  return new Promise((resolve, reject) => {
    const chunks = []
    const doc = new PDFDocument({
      size: 'A4',
      margin: 50,
      bufferPages: true,
      info: {
        Title: report.title,
        Author: 'HemisX SAST',
        Subject: 'Security Assessment Report',
        Creator: 'HemisX Security Platform',
      },
    })

    doc.on('data', (chunk) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    drawCoverPage(doc, report)

    doc.addPage()
    drawExecutiveSummary(doc, report)

    doc.addPage()
    drawRiskBreakdown(doc, report)

    doc.addPage()
    drawTopRisks(doc, report)

    doc.addPage()
    drawRemediationPlan(doc, report)

    if (report.compliance && report.compliance.length > 0) {
      doc.addPage()
      drawComplianceSummary(doc, report)
    }

    const pageCount = doc.bufferedPageRange()
    for (let i = 0; i < pageCount.count; i++) {
      doc.switchToPage(i)
      drawFooter(doc, i + 1, pageCount.count)
    }

    doc.end()
  })
}

// Read JSON from stdin, generate PDF, write to stdout
async function main() {
  const inputChunks = []
  for await (const chunk of process.stdin) {
    inputChunks.push(chunk)
  }
  const input = JSON.parse(Buffer.concat(inputChunks).toString('utf8'))
  const pdfBuffer = await generatePdf(input.report)

  // Write raw binary to stdout
  process.stdout.write(pdfBuffer)
}

main().catch((err) => {
  process.stderr.write(`[PDF] Error: ${err.message}\n`)
  process.exit(1)
})
